import { defineConfig } from 'tsup'

const vueCompilerOptionalTemplateEngines = [
  'atpl',
  'babel-core',
  'bracket-template',
  'coffee-script',
  'dot',
  'dustjs-linkedin',
  'eco',
  'ect',
  'haml-coffee',
  'hamlet',
  'hamljs',
  'handlebars',
  'hogan.js',
  'htmling',
  'jazz',
  'jqtpl',
  'just',
  'liquor',
  'marko',
  'mote',
  'plates',
  'ractive',
  'react',
  'react-dom/server',
  'slm',
  'squirrelly',
  'teacup/lib/express',
  'templayed',
  'toffee',
  'twig',
  'twing',
  'underscore',
  'vash',
  'velocityjs',
  'walrus',
  'whiskers',
]

export default defineConfig({
  entry: ['src/index.ts', 'src/bin/tuff.ts'],
  format: ['esm'],
  dts: true,
  splitting: true,
  clean: true,
  target: 'node18',
  platform: 'node',
  noExternal: [
    '@talex-touch/tuff-cli-core',
    '@talex-touch/utils',
    '@talex-touch/unplugin-export-plugin',
    '@talex-touch/unplugin-export-plugin/vite',
  ],
  external: [
    'chalk',
    'cli-progress',
    'compressing',
    'debug',
    'esbuild',
    'fs-extra',
    'glob',
    'pathe',
    'rollup',
    'unplugin',
    'vite',
    ...vueCompilerOptionalTemplateEngines,
  ],
})
