<script setup lang="ts">
import { computed, ref } from 'vue'
import { TuffInput, TuffSelect, TuffSelectItem, TxButton, TxCardItem, TxSkeleton, TxSpinner, TxTag } from '@talex-touch/tuffex'
import { useDashboardUpdatesData } from '~/composables/useDashboardData'
import { useToast } from '~/composables/useToast'

interface LocalizedText {
  zh: string
  en: string
}

interface DashboardUpdate {
  id: string
  type: 'news' | 'release' | 'announcement' | 'config' | 'data'
  scope: 'web' | 'system' | 'both'
  channels: string[]
  releaseTag: string | null
  title: LocalizedText
  timestamp: string
  summary: LocalizedText
  tags: string[]
  link: string
}

type UpdateTypeFilter = DashboardUpdate['type'] | 'all'
type UpdateScopeFilter = DashboardUpdate['scope'] | 'all'
type UpdateChannelFilter = 'RELEASE' | 'BETA' | 'SNAPSHOT' | 'all'
type UpdateSourceFilter = 'all' | 'auto' | 'manual'
type UpdateDateRangeFilter = 'all' | '7d' | '30d' | '90d'

definePageMeta({
  pageTransition: {
    name: 'fade',
    mode: 'out-in',
  },
})

defineI18nRoute(false)

const { t, locale } = useI18n()
const { user } = useAuthUser()
const toast = useToast()

const { updates, pending: updatesPending, refresh: refreshUpdates } = useDashboardUpdatesData()

const localeTag = computed(() => (locale.value === 'zh' ? 'zh-CN' : 'en-US'))
const dateFormatter = computed(() => new Intl.DateTimeFormat(localeTag.value, { dateStyle: 'medium' }))
const isZh = computed(() => locale.value.startsWith('zh'))
const UPDATE_RELEASE_TAG_COLOR = 'var(--tx-color-primary)'
const UPDATE_KEYWORD_TAG_COLOR = 'var(--tx-text-color-secondary)'

const searchKeyword = ref('')
const selectedType = ref<UpdateTypeFilter>('all')
const selectedScope = ref<UpdateScopeFilter>('all')
const selectedChannel = ref<UpdateChannelFilter>('all')
const selectedSource = ref<UpdateSourceFilter>('all')
const selectedDateRange = ref<UpdateDateRangeFilter>('all')

const isAdmin = computed(() => user.value?.role === 'admin')

const typeOptions = computed(() => [
  { value: 'all', label: isZh.value ? '全部类型' : 'All types' },
  { value: 'release', label: t('dashboard.sections.updates.typeRelease', 'Release') },
  { value: 'news', label: t('dashboard.sections.updates.typeNews', 'News') },
  { value: 'announcement', label: t('dashboard.sections.updates.typeAnnouncement', 'Announcement') },
  { value: 'config', label: t('dashboard.sections.updates.typeConfig', 'Config') },
  { value: 'data', label: t('dashboard.sections.updates.typeData', 'Data') },
])

const scopeOptions = computed(() => [
  { value: 'all', label: isZh.value ? '全部范围' : 'All scopes' },
  { value: 'web', label: isZh.value ? '官网' : 'Web' },
  { value: 'system', label: t('dashboard.sections.updates.scopeSystem', 'System') },
  { value: 'both', label: t('dashboard.sections.updates.scopeBoth', 'Web + System') },
])

const channelOptions = computed(() => [
  { value: 'all', label: isZh.value ? '全部渠道' : 'All channels' },
  { value: 'RELEASE', label: 'RELEASE' },
  { value: 'BETA', label: 'BETA' },
  { value: 'SNAPSHOT', label: 'SNAPSHOT' },
])

const sourceOptions = computed(() => [
  { value: 'all', label: isZh.value ? '全部来源' : 'All sources' },
  { value: 'auto', label: isZh.value ? '自动发布' : 'Auto (release sync)' },
  { value: 'manual', label: isZh.value ? '手动发布' : 'Manual' },
])

const dateRangeOptions = computed(() => [
  { value: 'all', label: isZh.value ? '全部时间' : 'All time' },
  { value: '7d', label: isZh.value ? '近 7 天' : 'Last 7 days' },
  { value: '30d', label: isZh.value ? '近 30 天' : 'Last 30 days' },
  { value: '90d', label: isZh.value ? '近 90 天' : 'Last 90 days' },
])

const hasActiveFilters = computed(() => {
  return searchKeyword.value.trim().length > 0
    || selectedType.value !== 'all'
    || selectedScope.value !== 'all'
    || selectedChannel.value !== 'all'
    || selectedSource.value !== 'all'
    || selectedDateRange.value !== 'all'
})

const filteredUpdates = computed(() => {
  const keyword = searchKeyword.value.trim().toLowerCase()

  return updates.value.filter((update) => {
    if (selectedType.value !== 'all' && update.type !== selectedType.value)
      return false

    if (selectedScope.value !== 'all' && update.scope !== selectedScope.value)
      return false

    if (selectedChannel.value !== 'all') {
      const channels = (update.channels || []).map(channel => channel.toUpperCase())
      if (channels.length > 0 && !channels.includes(selectedChannel.value))
        return false
    }

    const autoGenerated = isAutoGenerated(update)
    if (selectedSource.value === 'auto' && !autoGenerated)
      return false
    if (selectedSource.value === 'manual' && autoGenerated)
      return false

    if (!matchesDateRange(update.timestamp, selectedDateRange.value))
      return false

    if (!keyword)
      return true

    const title = resolveLocalizedText(update.title).toLowerCase()
    const summary = resolveLocalizedText(update.summary).toLowerCase()
    const releaseTag = (update.releaseTag || '').toLowerCase()
    const tags = (update.tags || []).join(' ').toLowerCase()
    const channels = (update.channels || []).join(' ').toLowerCase()

    return title.includes(keyword)
      || summary.includes(keyword)
      || releaseTag.includes(keyword)
      || tags.includes(keyword)
      || channels.includes(keyword)
  })
})

function clearFilters() {
  searchKeyword.value = ''
  selectedType.value = 'all'
  selectedScope.value = 'all'
  selectedChannel.value = 'all'
  selectedSource.value = 'all'
  selectedDateRange.value = 'all'
}

function matchesDateRange(timestamp: string, range: UpdateDateRangeFilter): boolean {
  if (range === 'all')
    return true

  const date = new Date(timestamp)
  if (Number.isNaN(date.getTime()))
    return true

  const now = Date.now()
  const elapsed = now - date.getTime()
  const day = 24 * 60 * 60 * 1000

  if (range === '7d')
    return elapsed <= 7 * day
  if (range === '30d')
    return elapsed <= 30 * day
  return elapsed <= 90 * day
}

function isAutoGenerated(update: DashboardUpdate): boolean {
  return update.type === 'release' || Boolean(update.releaseTag)
}

function sourceLabel(update: DashboardUpdate): string {
  return isAutoGenerated(update)
    ? (isZh.value ? '自动' : 'Auto')
    : (isZh.value ? '手动' : 'Manual')
}

function formatDate(value?: string) {
  if (!value)
    return ''
  const parsed = new Date(value)
  if (Number.isNaN(parsed.getTime()))
    return value
  return dateFormatter.value.format(parsed)
}

function resolveLocalizedText(text: LocalizedText) {
  if (isZh.value)
    return text.zh || text.en
  return text.en || text.zh
}

function updateTypeLabel(update: DashboardUpdate) {
  if (update.type === 'release')
    return t('dashboard.sections.updates.typeRelease', '更新')
  if (update.type === 'announcement')
    return t('dashboard.sections.updates.typeAnnouncement', '公告')
  if (update.type === 'config')
    return t('dashboard.sections.updates.typeConfig', '配置')
  if (update.type === 'data')
    return t('dashboard.sections.updates.typeData', '数据')
  return t('dashboard.sections.updates.typeNews', '要闻')
}

function updateScopeLabel(scope: DashboardUpdate['scope']) {
  if (scope === 'system')
    return t('dashboard.sections.updates.scopeSystem', '系统')
  if (scope === 'both')
    return t('dashboard.sections.updates.scopeBoth', '官网+系统')
  return isZh.value ? '官网' : 'Web'
}

function resolveTypeIcon(type: DashboardUpdate['type']) {
  if (type === 'release')
    return 'i-carbon-version-major'
  if (type === 'announcement')
    return 'i-carbon-bullhorn'
  if (type === 'config')
    return 'i-carbon-settings'
  if (type === 'data')
    return 'i-carbon-data-table'
  return 'i-carbon-notification'
}

function updateTypeTagColor(type: DashboardUpdate['type']) {
  if (type === 'release')
    return 'var(--tx-color-primary)'
  if (type === 'announcement')
    return 'var(--tx-color-warning)'
  if (type === 'config')
    return 'var(--tx-color-success)'
  if (type === 'data')
    return 'var(--tx-color-primary)'
  return 'var(--tx-text-color-secondary)'
}

function updateScopeTagColor(scope: DashboardUpdate['scope']) {
  if (scope === 'both')
    return 'var(--tx-color-primary)'
  if (scope === 'system')
    return 'var(--tx-color-warning)'
  return 'var(--tx-text-color-secondary)'
}

function updateSourceTagColor(update: DashboardUpdate) {
  return isAutoGenerated(update) ? 'var(--tx-color-success)' : 'var(--tx-text-color-secondary)'
}

function updateChannelTagColor(channel: string) {
  const normalized = channel.toUpperCase()
  if (normalized === 'RELEASE')
    return 'var(--tx-color-primary)'
  if (normalized === 'BETA')
    return 'var(--tx-color-warning)'
  if (normalized === 'SNAPSHOT')
    return 'var(--tx-color-danger)'
  return 'var(--tx-text-color-secondary)'
}

function openUpdateLink(link?: string) {
  if (!link)
    return
  if (import.meta.client)
    window.open(link, '_blank', 'noopener')
}

const drawerOpen = ref(false)
const drawerMode = ref<'create' | 'edit'>('create')
const editingUpdate = ref<DashboardUpdate | null>(null)

function openCreate() {
  drawerMode.value = 'create'
  editingUpdate.value = null
  drawerOpen.value = true
}

function openEdit(update: DashboardUpdate) {
  drawerMode.value = 'edit'
  editingUpdate.value = update
  drawerOpen.value = true
}

async function onSaved() {
  await refreshUpdates()
}

const deleteConfirmVisible = ref(false)
const pendingDeleteUpdate = ref<DashboardUpdate | null>(null)

function deleteUpdateItem(update: DashboardUpdate) {
  pendingDeleteUpdate.value = update
  deleteConfirmVisible.value = true
}

async function confirmDeleteUpdate(): Promise<boolean> {
  if (!pendingDeleteUpdate.value)
    return true

  try {
    await $fetch(`/api/dashboard/updates/${pendingDeleteUpdate.value.id}`, {
      method: 'DELETE' as unknown as 'PATCH',
    })
    await refreshUpdates()
  }
  catch (error: unknown) {
    const message = (error as any)?.data?.statusMessage || (error as any)?.message || (isZh.value ? '删除失败' : 'Delete failed')
    toast.warning(message)
  }
  finally {
    pendingDeleteUpdate.value = null
  }

  return true
}

function closeDeleteConfirm() {
  deleteConfirmVisible.value = false
  pendingDeleteUpdate.value = null
}
</script>

<template>
  <div class="mx-auto max-w-5xl space-y-6">
    <div>
      <h2 class="apple-heading-sm">
        {{ t('dashboard.sections.updates.title') }}
      </h2>
      <p class="mt-1 text-sm text-black/50 dark:text-white/50">
        {{ t('dashboard.sections.updates.subtitle') }}
      </p>
    </div>

    <section class="apple-card-lg p-5">
      <div class="flex flex-wrap items-center justify-between gap-3">
        <div>
          <h3 class="text-base font-semibold text-black dark:text-white">
            {{ t('dashboard.sections.updates.listTitle', '更新与要闻') }}
          </h3>
          <p class="mt-1 text-xs text-black/50 dark:text-white/50">
            {{ t('dashboard.sections.updates.listSubtitle', '统一管理要闻与版本更新。') }}
          </p>
        </div>

        <div class="flex flex-wrap items-center gap-2">
          <TxButton
            variant="secondary"
            size="small"
            icon="i-carbon-launch"
            native-type="button"
            @click="openUpdateLink('https://docs.tuff.chat/changelog')"
          >
            {{ isZh ? 'Changelog 文档' : 'Changelog' }}
          </TxButton>
          <TxButton v-if="isAdmin" variant="primary" icon="i-carbon-add" size="small" native-type="button" @click="openCreate">
            {{ t('dashboard.sections.updates.addButton') }}
          </TxButton>
        </div>
      </div>

      <div class="UpdateFilters mt-4">
        <div class="UpdateFilters-Grid">
          <div class="UpdateFilters-Field UpdateFilters-Field--search">
            <label class="UpdateFilters-Label">{{ isZh ? '搜索' : 'Search' }}</label>
            <TuffInput
              v-model="searchKeyword"
              type="text"
              clearable
              :placeholder="isZh ? '标题 / 摘要 / 标签 / 版本号' : 'Title / summary / tags / release tag'"
            />
          </div>

          <div class="UpdateFilters-Field">
            <label class="UpdateFilters-Label">{{ isZh ? '类型' : 'Type' }}</label>
            <TuffSelect v-model="selectedType">
              <TuffSelectItem
                v-for="option in typeOptions"
                :key="option.value"
                :value="option.value"
                :label="option.label"
              />
            </TuffSelect>
          </div>

          <div class="UpdateFilters-Field">
            <label class="UpdateFilters-Label">{{ isZh ? '渠道' : 'Channel' }}</label>
            <TuffSelect v-model="selectedChannel">
              <TuffSelectItem
                v-for="option in channelOptions"
                :key="option.value"
                :value="option.value"
                :label="option.label"
              />
            </TuffSelect>
          </div>

          <div class="UpdateFilters-Field">
            <label class="UpdateFilters-Label">{{ isZh ? '范围' : 'Scope' }}</label>
            <TuffSelect v-model="selectedScope">
              <TuffSelectItem
                v-for="option in scopeOptions"
                :key="option.value"
                :value="option.value"
                :label="option.label"
              />
            </TuffSelect>
          </div>

          <div class="UpdateFilters-Field">
            <label class="UpdateFilters-Label">{{ isZh ? '来源' : 'Source' }}</label>
            <TuffSelect v-model="selectedSource">
              <TuffSelectItem
                v-for="option in sourceOptions"
                :key="option.value"
                :value="option.value"
                :label="option.label"
              />
            </TuffSelect>
          </div>

          <div class="UpdateFilters-Field">
            <label class="UpdateFilters-Label">{{ isZh ? '时间' : 'Date range' }}</label>
            <TuffSelect v-model="selectedDateRange">
              <TuffSelectItem
                v-for="option in dateRangeOptions"
                :key="option.value"
                :value="option.value"
                :label="option.label"
              />
            </TuffSelect>
          </div>
        </div>

        <div class="UpdateFilters-Actions">
          <TxButton
            variant="ghost"
            size="small"
            native-type="button"
            :disabled="!hasActiveFilters"
            @click="clearFilters"
          >
            {{ isZh ? '清空筛选' : 'Clear filters' }}
          </TxButton>
        </div>
      </div>

      <div v-if="updatesPending" class="mt-4 space-y-3 py-6">
        <div class="flex items-center justify-center">
          <TxSpinner :size="18" />
        </div>
        <div class="rounded-2xl bg-black/[0.02] p-4 dark:bg-white/[0.03]">
          <TxSkeleton :loading="true" :lines="2" />
        </div>
        <div class="rounded-2xl bg-black/[0.02] p-4 dark:bg-white/[0.03]">
          <TxSkeleton :loading="true" :lines="2" />
        </div>
      </div>

      <div
        v-else-if="!updates.length"
        class="mt-4 rounded-2xl border border-dashed border-black/[0.08] py-8 text-center text-sm text-black/40 dark:border-white/[0.08] dark:text-white/40"
      >
        {{ t('dashboard.sections.updates.empty') }}
      </div>

      <div
        v-else-if="!filteredUpdates.length"
        class="mt-4 rounded-2xl border border-dashed border-black/[0.08] py-8 text-center text-sm text-black/40 dark:border-white/[0.08] dark:text-white/40"
      >
        {{ isZh ? '没有匹配结果，请调整筛选条件。' : 'No results. Try adjusting the filters.' }}
      </div>

      <div v-else class="UpdateList mt-5">
        <TxCardItem
          v-for="update in filteredUpdates"
          :key="update.id"
          class="UpdateList-Card"
          :title="resolveLocalizedText(update.title)"
          :icon-class="resolveTypeIcon(update.type)"
          :clickable="Boolean(update.link)"
          @click="openUpdateLink(update.link)"
        >
          <template #subtitle>
            <div class="UpdateList-Meta">
              <span class="UpdateList-Date">{{ formatDate(update.timestamp) }}</span>
              <TxTag class="UpdateList-Tag" size="sm" :label="updateTypeLabel(update)" :color="updateTypeTagColor(update.type)" />
              <TxTag
                v-if="update.scope !== 'web'"
                class="UpdateList-Tag"
                size="sm"
                :label="updateScopeLabel(update.scope)"
                :color="updateScopeTagColor(update.scope)"
              />
              <TxTag class="UpdateList-Tag" size="sm" :label="sourceLabel(update)" :color="updateSourceTagColor(update)" />
              <TxTag
                v-if="update.releaseTag"
                class="UpdateList-Tag"
                size="sm"
                :label="update.releaseTag"
                :color="UPDATE_RELEASE_TAG_COLOR"
              />
            </div>
          </template>

          <template #description>
            <p class="UpdateList-Summary line-clamp-2">
              {{ resolveLocalizedText(update.summary) }}
            </p>
            <div v-if="update.channels.length || update.tags.length" class="UpdateList-Tags">
              <TxTag
                v-for="channel in update.channels.slice(0, 3)"
                :key="`${update.id}-channel-${channel}`"
                class="UpdateList-Tag"
                size="sm"
                :label="channel"
                :color="updateChannelTagColor(channel)"
              />
              <TxTag
                v-for="tag in update.tags.slice(0, 3)"
                :key="`${update.id}-tag-${tag}`"
                class="UpdateList-Tag"
                size="sm"
                :label="`#${tag}`"
                :color="UPDATE_KEYWORD_TAG_COLOR"
              />
            </div>
          </template>

          <template #right>
            <div class="UpdateList-Actions">
              <TxButton
                v-if="update.link"
                variant="bare"
                circle
                size="mini"
                native-type="button"
                :title="isZh ? '打开链接' : 'Open link'"
                @click.stop="openUpdateLink(update.link)"
              >
                <span class="i-carbon-launch text-sm" />
              </TxButton>
              <TxButton
                v-if="isAdmin && update.type !== 'release'"
                variant="bare"
                circle
                size="mini"
                native-type="button"
                :title="t('dashboard.sections.updates.editButton')"
                @click.stop="openEdit(update)"
              >
                <span class="i-carbon-edit text-sm" />
              </TxButton>
              <TxButton
                v-if="isAdmin && update.type !== 'release'"
                variant="bare"
                circle
                size="mini"
                native-type="button"
                :title="t('dashboard.sections.updates.delete', 'Delete')"
                @click.stop="deleteUpdateItem(update)"
              >
                <span class="i-carbon-trash-can text-sm" />
              </TxButton>
            </div>
          </template>
        </TxCardItem>
      </div>

      <div
        v-if="!updatesPending && updates.length"
        class="UpdateList-Footer mt-4 text-xs text-black/40 dark:text-white/40"
      >
        {{ isZh ? `共 ${updates.length} 条，当前 ${filteredUpdates.length} 条` : `Total ${updates.length}, showing ${filteredUpdates.length}` }}
      </div>
    </section>

    <DashboardUpdateFormDrawer
      :open="drawerOpen"
      :mode="drawerMode"
      :update="editingUpdate"
      @close="drawerOpen = false"
      @saved="onSaved"
    />

    <TxBottomDialog
      v-if="deleteConfirmVisible"
      :title="t('dashboard.sections.updates.deleteTitle', 'Delete Update')"
      :message="t('dashboard.sections.updates.confirmDelete', { title: resolveLocalizedText(pendingDeleteUpdate?.title || { zh: '', en: '' }) })"
      :btns="[
        { content: t('dashboard.sections.updates.cancel', 'Cancel'), type: 'info', onClick: () => true },
        { content: t('dashboard.sections.updates.delete', 'Delete'), type: 'error', onClick: confirmDeleteUpdate },
      ]"
      :close="closeDeleteConfirm"
    />
  </div>
</template>

<style scoped>
.UpdateFilters {
  border-top: 1px solid color-mix(in srgb, var(--tx-border-color-lighter, rgba(120, 120, 120, 0.24)) 100%, transparent);
  padding-top: 14px;
}

.UpdateFilters-Grid {
  display: grid;
  gap: 10px;
  grid-template-columns: repeat(auto-fit, minmax(160px, 1fr));
}

.UpdateFilters-Field {
  min-width: 0;
  display: flex;
  flex-direction: column;
  gap: 6px;
}

.UpdateFilters-Field--search {
  grid-column: 1 / -1;
}

.UpdateFilters-Field > * {
  min-width: 0;
}

.UpdateFilters-Label {
  font-size: 12px;
  font-weight: 500;
  color: color-mix(in srgb, var(--tx-text-color-secondary, rgba(150, 150, 150, 1)) 88%, transparent);
}

.UpdateFilters-Actions {
  margin-top: 10px;
  display: flex;
  justify-content: flex-end;
}

.UpdateList {
  display: flex;
  flex-direction: column;
  gap: 12px;
}

.UpdateList-Card {
  min-height: 112px;
}

.UpdateList-Meta {
  display: flex;
  flex-wrap: wrap;
  align-items: center;
  gap: 6px;
}

.UpdateList-Date {
  font-size: 12px;
  color: color-mix(in srgb, var(--tx-text-color-secondary, rgba(150, 150, 150, 1)) 90%, transparent);
  margin-right: 2px;
}

.UpdateList-Summary {
  margin-top: 2px;
  font-size: 13px;
  line-height: 1.45;
  color: color-mix(in srgb, var(--tx-text-color-secondary, rgba(150, 150, 150, 1)) 94%, transparent);
}

.UpdateList-Tags {
  margin-top: 8px;
  display: flex;
  flex-wrap: wrap;
  gap: 6px;
}

.UpdateList-Tag {
  letter-spacing: 0;
}

.UpdateList-Actions {
  display: flex;
  align-items: center;
  gap: 2px;
}

.UpdateList-Footer {
  border-top: 1px solid color-mix(in srgb, var(--tx-border-color-lighter, rgba(120, 120, 120, 0.24)) 100%, transparent);
  padding-top: 10px;
}
</style>
