<script setup lang="ts">
import type { DataTableColumn } from '@talex-touch/tuffex/data-table'
import { computed, ref, watch } from 'vue'
import { TxButton } from '@talex-touch/tuffex/button'
import { TxDataTable } from '@talex-touch/tuffex/data-table'
import { TuffInput } from '@talex-touch/tuffex/input'
import { TxPagination } from '@talex-touch/tuffex/pagination'
import { TuffSelect, TuffSelectItem } from '@talex-touch/tuffex/select'
import { TxSkeleton } from '@talex-touch/tuffex/skeleton'
import { TxSpinner } from '@talex-touch/tuffex/spinner'
import { TxTag } from '@talex-touch/tuffex/tag'
import { useDashboardUpdatesData } from '~/composables/useDashboardData'
import { useToast } from '~/composables/useToast'

interface LocalizedText {
  zh: string
  en: string
}

interface DashboardUpdate {
  id: string
  type: 'news' | 'release' | 'announcement' | 'config' | 'data'
  scope: 'web' | 'system' | 'both'
  channels: string[]
  releaseTag: string | null
  title: LocalizedText
  timestamp: string
  summary: LocalizedText
  tags: string[]
  link: string
}

type UpdateTypeFilter = DashboardUpdate['type'] | 'all'
type UpdateScopeFilter = DashboardUpdate['scope'] | 'all'
type UpdateChannelFilter = 'RELEASE' | 'BETA' | 'SNAPSHOT' | 'all'
type UpdateSourceFilter = 'all' | 'auto' | 'manual'
type UpdateDateRangeFilter = 'all' | '7d' | '30d' | '90d'

definePageMeta({
  pageTransition: {
    name: 'fade',
    mode: 'out-in',
  },
})

defineI18nRoute(false)

const { t, locale } = useI18n()
const { user } = useAuthUser()
const toast = useToast()

const { updates, pending: updatesPending, refresh: refreshUpdates } = useDashboardUpdatesData()

const localeTag = computed(() => (locale.value === 'zh' ? 'zh-CN' : 'en-US'))
const dateFormatter = computed(() => new Intl.DateTimeFormat(localeTag.value, { dateStyle: 'medium' }))
const isZh = computed(() => locale.value.startsWith('zh'))
const UPDATE_RELEASE_TAG_COLOR = 'var(--tx-color-primary)'
const UPDATE_KEYWORD_TAG_COLOR = 'var(--tx-text-color-secondary)'
const UPDATES_PAGE_SIZE = 5

const searchKeyword = ref('')
const selectedType = ref<UpdateTypeFilter>('all')
const selectedScope = ref<UpdateScopeFilter>('all')
const selectedChannel = ref<UpdateChannelFilter>('all')
const selectedSource = ref<UpdateSourceFilter>('all')
const selectedDateRange = ref<UpdateDateRangeFilter>('all')
const currentUpdatePage = ref(1)

const isAdmin = computed(() => user.value?.role === 'admin')

const typeOptions = computed(() => [
  { value: 'all', label: isZh.value ? '全部类型' : 'All types' },
  { value: 'release', label: t('dashboard.sections.updates.typeRelease', 'Release') },
  { value: 'news', label: t('dashboard.sections.updates.typeNews', 'News') },
  { value: 'announcement', label: t('dashboard.sections.updates.typeAnnouncement', 'Announcement') },
  { value: 'config', label: t('dashboard.sections.updates.typeConfig', 'Config') },
  { value: 'data', label: t('dashboard.sections.updates.typeData', 'Data') },
])

const scopeOptions = computed(() => [
  { value: 'all', label: isZh.value ? '全部范围' : 'All scopes' },
  { value: 'web', label: isZh.value ? '官网' : 'Web' },
  { value: 'system', label: t('dashboard.sections.updates.scopeSystem', 'System') },
  { value: 'both', label: t('dashboard.sections.updates.scopeBoth', 'Web + System') },
])

const channelOptions = computed(() => [
  { value: 'all', label: isZh.value ? '全部渠道' : 'All channels' },
  { value: 'RELEASE', label: 'RELEASE' },
  { value: 'BETA', label: 'BETA' },
  { value: 'SNAPSHOT', label: 'SNAPSHOT' },
])

const sourceOptions = computed(() => [
  { value: 'all', label: isZh.value ? '全部来源' : 'All sources' },
  { value: 'auto', label: isZh.value ? '自动发布' : 'Auto (release sync)' },
  { value: 'manual', label: isZh.value ? '手动发布' : 'Manual' },
])

const dateRangeOptions = computed(() => [
  { value: 'all', label: isZh.value ? '全部时间' : 'All time' },
  { value: '7d', label: isZh.value ? '近 7 天' : 'Last 7 days' },
  { value: '30d', label: isZh.value ? '近 30 天' : 'Last 30 days' },
  { value: '90d', label: isZh.value ? '近 90 天' : 'Last 90 days' },
])

const hasActiveFilters = computed(() => {
  return searchKeyword.value.trim().length > 0
    || selectedType.value !== 'all'
    || selectedScope.value !== 'all'
    || selectedChannel.value !== 'all'
    || selectedSource.value !== 'all'
    || selectedDateRange.value !== 'all'
})

const filteredUpdates = computed(() => {
  const keyword = searchKeyword.value.trim().toLowerCase()

  return updates.value.filter((update) => {
    if (selectedType.value !== 'all' && update.type !== selectedType.value)
      return false

    if (selectedScope.value !== 'all' && update.scope !== selectedScope.value)
      return false

    if (selectedChannel.value !== 'all') {
      const channels = (update.channels || []).map(channel => channel.toUpperCase())
      if (channels.length > 0 && !channels.includes(selectedChannel.value))
        return false
    }

    const autoGenerated = isAutoGenerated(update)
    if (selectedSource.value === 'auto' && !autoGenerated)
      return false
    if (selectedSource.value === 'manual' && autoGenerated)
      return false

    if (!matchesDateRange(update.timestamp, selectedDateRange.value))
      return false

    if (!keyword)
      return true

    const title = resolveLocalizedText(update.title).toLowerCase()
    const summary = resolveLocalizedText(update.summary).toLowerCase()
    const releaseTag = (update.releaseTag || '').toLowerCase()
    const tags = (update.tags || []).join(' ').toLowerCase()
    const channels = (update.channels || []).join(' ').toLowerCase()

    return title.includes(keyword)
      || summary.includes(keyword)
      || releaseTag.includes(keyword)
      || tags.includes(keyword)
      || channels.includes(keyword)
  })
})

const updateTableColumns = computed<DataTableColumn<DashboardUpdate>[]>(() => [
  { key: 'title', title: isZh.value ? '标题 / 摘要' : 'Title / Summary', width: '36%' },
  { key: 'type', title: isZh.value ? '类型' : 'Type', width: 108 },
  { key: 'channels', title: isZh.value ? '渠道' : 'Channel', width: 150 },
  { key: 'scope', title: isZh.value ? '范围' : 'Scope', width: 120 },
  { key: 'source', title: isZh.value ? '来源' : 'Source', width: 110 },
  { key: 'timestamp', title: isZh.value ? '时间' : 'Date', width: 130 },
  {
    key: 'actions',
    title: isZh.value ? '操作' : 'Actions',
    width: 92,
    align: 'right',
    headerClass: 'UpdateTable-ActionsHeader',
    cellClass: 'UpdateTable-ActionsCell',
  },
])

const updateTotalPages = computed(() => Math.max(1, Math.ceil(filteredUpdates.value.length / UPDATES_PAGE_SIZE)))

const pagedUpdates = computed(() => {
  const page = Math.min(currentUpdatePage.value, updateTotalPages.value)
  const start = (page - 1) * UPDATES_PAGE_SIZE
  return filteredUpdates.value.slice(start, start + UPDATES_PAGE_SIZE)
})

const pagedUpdateSummary = computed(() => {
  if (!filteredUpdates.value.length)
    return isZh.value ? `共 ${updates.value.length} 条，筛选 0 条` : `Total ${updates.value.length}, filtered 0`

  const page = Math.min(currentUpdatePage.value, updateTotalPages.value)
  const start = (page - 1) * UPDATES_PAGE_SIZE + 1
  const end = Math.min(start + UPDATES_PAGE_SIZE - 1, filteredUpdates.value.length)

  return isZh.value
    ? `共 ${updates.value.length} 条，筛选 ${filteredUpdates.value.length} 条，当前 ${start}-${end} 条，每页 ${UPDATES_PAGE_SIZE} 条`
    : `Total ${updates.value.length}, filtered ${filteredUpdates.value.length}, showing ${start}-${end}, ${UPDATES_PAGE_SIZE} per page`
})

watch(filteredUpdates, () => {
  currentUpdatePage.value = 1
})

watch(updateTotalPages, (totalPages) => {
  if (currentUpdatePage.value > totalPages)
    currentUpdatePage.value = totalPages
})

function clearFilters() {
  searchKeyword.value = ''
  selectedType.value = 'all'
  selectedScope.value = 'all'
  selectedChannel.value = 'all'
  selectedSource.value = 'all'
  selectedDateRange.value = 'all'
}

function matchesDateRange(timestamp: string, range: UpdateDateRangeFilter): boolean {
  if (range === 'all')
    return true

  const date = new Date(timestamp)
  if (Number.isNaN(date.getTime()))
    return true

  const now = Date.now()
  const elapsed = now - date.getTime()
  const day = 24 * 60 * 60 * 1000

  if (range === '7d')
    return elapsed <= 7 * day
  if (range === '30d')
    return elapsed <= 30 * day
  return elapsed <= 90 * day
}

function isAutoGenerated(update: DashboardUpdate): boolean {
  return update.type === 'release' || Boolean(update.releaseTag)
}

function sourceLabel(update: DashboardUpdate): string {
  return isAutoGenerated(update)
    ? (isZh.value ? '自动' : 'Auto')
    : (isZh.value ? '手动' : 'Manual')
}

function formatDate(value?: string) {
  if (!value)
    return ''
  const parsed = new Date(value)
  if (Number.isNaN(parsed.getTime()))
    return value
  return dateFormatter.value.format(parsed)
}

function resolveLocalizedText(text: LocalizedText) {
  if (isZh.value)
    return text.zh || text.en
  return text.en || text.zh
}

function updateTypeLabel(update: DashboardUpdate) {
  if (update.type === 'release')
    return t('dashboard.sections.updates.typeRelease', '更新')
  if (update.type === 'announcement')
    return t('dashboard.sections.updates.typeAnnouncement', '公告')
  if (update.type === 'config')
    return t('dashboard.sections.updates.typeConfig', '配置')
  if (update.type === 'data')
    return t('dashboard.sections.updates.typeData', '数据')
  return t('dashboard.sections.updates.typeNews', '要闻')
}

function updateScopeLabel(scope: DashboardUpdate['scope']) {
  if (scope === 'system')
    return t('dashboard.sections.updates.scopeSystem', '系统')
  if (scope === 'both')
    return t('dashboard.sections.updates.scopeBoth', '官网+系统')
  return isZh.value ? '官网' : 'Web'
}

function updateTypeTagColor(type: DashboardUpdate['type']) {
  if (type === 'release')
    return 'var(--tx-color-primary)'
  if (type === 'announcement')
    return 'var(--tx-color-warning)'
  if (type === 'config')
    return 'var(--tx-color-success)'
  if (type === 'data')
    return 'var(--tx-color-primary)'
  return 'var(--tx-text-color-secondary)'
}

function updateScopeTagColor(scope: DashboardUpdate['scope']) {
  if (scope === 'both')
    return 'var(--tx-color-primary)'
  if (scope === 'system')
    return 'var(--tx-color-warning)'
  return 'var(--tx-text-color-secondary)'
}

function updateSourceTagColor(update: DashboardUpdate) {
  return isAutoGenerated(update) ? 'var(--tx-color-success)' : 'var(--tx-text-color-secondary)'
}

function updateChannelTagColor(channel: string) {
  const normalized = channel.toUpperCase()
  if (normalized === 'RELEASE')
    return 'var(--tx-color-primary)'
  if (normalized === 'BETA')
    return 'var(--tx-color-warning)'
  if (normalized === 'SNAPSHOT')
    return 'var(--tx-color-danger)'
  return 'var(--tx-text-color-secondary)'
}

function openUpdateLink(link?: string) {
  if (!link)
    return
  if (import.meta.client)
    window.open(link, '_blank', 'noopener')
}

const drawerOpen = ref(false)
const drawerMode = ref<'create' | 'edit'>('create')
const editingUpdate = ref<DashboardUpdate | null>(null)

function openCreate() {
  drawerMode.value = 'create'
  editingUpdate.value = null
  drawerOpen.value = true
}

function openEdit(update: DashboardUpdate) {
  drawerMode.value = 'edit'
  editingUpdate.value = update
  drawerOpen.value = true
}

async function onSaved() {
  await refreshUpdates()
}

const deleteConfirmVisible = ref(false)
const pendingDeleteUpdate = ref<DashboardUpdate | null>(null)

function deleteUpdateItem(update: DashboardUpdate) {
  pendingDeleteUpdate.value = update
  deleteConfirmVisible.value = true
}

async function confirmDeleteUpdate(): Promise<boolean> {
  if (!pendingDeleteUpdate.value)
    return true

  try {
    await $fetch(`/api/dashboard/updates/${pendingDeleteUpdate.value.id}`, {
      method: 'DELETE' as unknown as 'PATCH',
    })
    await refreshUpdates()
  }
  catch (error: unknown) {
    const message = (error as any)?.data?.statusMessage || (error as any)?.message || (isZh.value ? '删除失败' : 'Delete failed')
    toast.warning(message)
  }
  finally {
    pendingDeleteUpdate.value = null
  }

  return true
}

function closeDeleteConfirm() {
  deleteConfirmVisible.value = false
  pendingDeleteUpdate.value = null
}
</script>

<template>
  <div class="mx-auto max-w-5xl space-y-6">
    <div class="flex flex-wrap items-start justify-between gap-3">
      <div>
        <h2 class="apple-heading-sm">
          {{ t('dashboard.sections.updates.title') }}
        </h2>
        <p class="mt-1 text-sm text-black/50 dark:text-white/50">
          {{ t('dashboard.sections.updates.subtitle') }}
        </p>
      </div>

      <div class="flex flex-wrap items-center justify-end gap-2">
        <TxButton
          variant="secondary"
          size="small"
          icon="i-carbon-launch"
          native-type="button"
          @click="openUpdateLink('https://docs.tuff.chat/changelog')"
        >
          {{ isZh ? 'Changelog 文档' : 'Changelog' }}
        </TxButton>
        <TxButton v-if="isAdmin" variant="primary" icon="i-carbon-add" size="small" native-type="button" @click="openCreate">
          {{ t('dashboard.sections.updates.addButton') }}
        </TxButton>
      </div>
    </div>

    <section class="apple-card-lg p-5">
      <div class="UpdateFilters">
        <div class="UpdateFilters-Grid">
          <div class="UpdateFilters-Field UpdateFilters-Field--search">
            <label class="UpdateFilters-Label">{{ isZh ? '搜索' : 'Search' }}</label>
            <TuffInput
              v-model="searchKeyword"
              type="text"
              clearable
              :placeholder="isZh ? '标题 / 摘要 / 标签 / 版本号' : 'Title / summary / tags / release tag'"
            />
          </div>

          <div class="UpdateFilters-Field">
            <label class="UpdateFilters-Label">{{ isZh ? '类型' : 'Type' }}</label>
            <TuffSelect v-model="selectedType">
              <TuffSelectItem
                v-for="option in typeOptions"
                :key="option.value"
                :value="option.value"
                :label="option.label"
              />
            </TuffSelect>
          </div>

          <div class="UpdateFilters-Field">
            <label class="UpdateFilters-Label">{{ isZh ? '渠道' : 'Channel' }}</label>
            <TuffSelect v-model="selectedChannel">
              <TuffSelectItem
                v-for="option in channelOptions"
                :key="option.value"
                :value="option.value"
                :label="option.label"
              />
            </TuffSelect>
          </div>

          <div class="UpdateFilters-Field">
            <label class="UpdateFilters-Label">{{ isZh ? '范围' : 'Scope' }}</label>
            <TuffSelect v-model="selectedScope">
              <TuffSelectItem
                v-for="option in scopeOptions"
                :key="option.value"
                :value="option.value"
                :label="option.label"
              />
            </TuffSelect>
          </div>

          <div class="UpdateFilters-Field">
            <label class="UpdateFilters-Label">{{ isZh ? '来源' : 'Source' }}</label>
            <TuffSelect v-model="selectedSource">
              <TuffSelectItem
                v-for="option in sourceOptions"
                :key="option.value"
                :value="option.value"
                :label="option.label"
              />
            </TuffSelect>
          </div>

          <div class="UpdateFilters-Field">
            <label class="UpdateFilters-Label">{{ isZh ? '时间' : 'Date range' }}</label>
            <TuffSelect v-model="selectedDateRange">
              <TuffSelectItem
                v-for="option in dateRangeOptions"
                :key="option.value"
                :value="option.value"
                :label="option.label"
              />
            </TuffSelect>
          </div>
        </div>

        <div class="UpdateFilters-Actions">
          <TxButton
            variant="ghost"
            size="small"
            native-type="button"
            :disabled="!hasActiveFilters"
            @click="clearFilters"
          >
            {{ isZh ? '清空筛选' : 'Clear filters' }}
          </TxButton>
        </div>
      </div>

      <div v-if="updatesPending" class="mt-4 space-y-3 py-6">
        <div class="flex items-center justify-center">
          <TxSpinner :size="18" />
        </div>
        <div class="rounded-2xl bg-black/[0.02] p-4 dark:bg-white/[0.03]">
          <TxSkeleton :loading="true" :lines="2" />
        </div>
        <div class="rounded-2xl bg-black/[0.02] p-4 dark:bg-white/[0.03]">
          <TxSkeleton :loading="true" :lines="2" />
        </div>
      </div>

      <div
        v-else-if="!updates.length"
        class="mt-4 rounded-2xl border border-dashed border-black/[0.08] py-8 text-center text-sm text-black/40 dark:border-white/[0.08] dark:text-white/40"
      >
        {{ t('dashboard.sections.updates.empty') }}
      </div>

      <div
        v-else-if="!filteredUpdates.length"
        class="mt-4 rounded-2xl border border-dashed border-black/[0.08] py-8 text-center text-sm text-black/40 dark:border-white/[0.08] dark:text-white/40"
      >
        {{ isZh ? '没有匹配结果，请调整筛选条件。' : 'No results. Try adjusting the filters.' }}
      </div>

      <div v-else class="UpdateTable mt-5">
        <TxDataTable
          :columns="updateTableColumns"
          :data="pagedUpdates"
          row-key="id"
          bordered
          hover
          class="UpdateTable-Data min-w-[920px]"
          @row-click="({ row }) => openUpdateLink(row.link)"
        >
          <template #cell-title="{ row }">
            <div class="UpdateTable-TitleCell">
              <button
                class="UpdateTable-TitleButton"
                type="button"
                :disabled="!row.link"
                @click.stop="openUpdateLink(row.link)"
              >
                {{ resolveLocalizedText(row.title) }}
              </button>
              <p class="UpdateTable-Summary line-clamp-2">
                {{ resolveLocalizedText(row.summary) }}
              </p>
              <div v-if="row.releaseTag || row.tags.length" class="UpdateTable-Tags">
                <TxTag
                  v-if="row.releaseTag"
                  class="UpdateTable-Tag"
                  size="sm"
                  :label="row.releaseTag"
                  :color="UPDATE_RELEASE_TAG_COLOR"
                />
                <TxTag
                  v-for="tag in row.tags.slice(0, 3)"
                  :key="`${row.id}-tag-${tag}`"
                  class="UpdateTable-Tag"
                  size="sm"
                  :label="`#${tag}`"
                  :color="UPDATE_KEYWORD_TAG_COLOR"
                />
              </div>
            </div>
          </template>

          <template #cell-type="{ row }">
            <TxTag class="UpdateTable-Tag" size="sm" :label="updateTypeLabel(row)" :color="updateTypeTagColor(row.type)" />
          </template>

          <template #cell-channels="{ row }">
            <div class="UpdateTable-Tags">
              <TxTag
                v-for="channel in row.channels.slice(0, 2)"
                :key="`${row.id}-channel-${channel}`"
                class="UpdateTable-Tag"
                size="sm"
                :label="channel"
                :color="updateChannelTagColor(channel)"
              />
              <span v-if="!row.channels.length" class="UpdateTable-Muted">-</span>
            </div>
          </template>

          <template #cell-scope="{ row }">
            <TxTag class="UpdateTable-Tag" size="sm" :label="updateScopeLabel(row.scope)" :color="updateScopeTagColor(row.scope)" />
          </template>

          <template #cell-source="{ row }">
            <TxTag class="UpdateTable-Tag" size="sm" :label="sourceLabel(row)" :color="updateSourceTagColor(row)" />
          </template>

          <template #cell-timestamp="{ row }">
            <span class="UpdateTable-Date">{{ formatDate(row.timestamp) }}</span>
          </template>

          <template #cell-actions="{ row }">
            <div class="UpdateTable-Actions">
              <button
                v-if="row.link"
                class="UpdateTable-IconButton"
                type="button"
                :title="isZh ? '打开链接' : 'Open link'"
                :aria-label="isZh ? '打开链接' : 'Open link'"
                @click.stop="openUpdateLink(row.link)"
              >
                <span class="i-carbon-launch" />
              </button>
              <button
                v-if="isAdmin && row.type !== 'release'"
                class="UpdateTable-IconButton"
                type="button"
                :title="t('dashboard.sections.updates.editButton')"
                :aria-label="t('dashboard.sections.updates.editButton')"
                @click.stop="openEdit(row)"
              >
                <span class="i-carbon-edit" />
              </button>
              <button
                v-if="isAdmin && row.type !== 'release'"
                class="UpdateTable-IconButton"
                type="button"
                :title="t('dashboard.sections.updates.delete', 'Delete')"
                :aria-label="t('dashboard.sections.updates.delete', 'Delete')"
                @click.stop="deleteUpdateItem(row)"
              >
                <span class="i-carbon-trash-can" />
              </button>
            </div>
          </template>
        </TxDataTable>
      </div>

      <div
        v-if="!updatesPending && updates.length"
        class="UpdateTable-Footer mt-4"
      >
        <span class="UpdateTable-Count">{{ pagedUpdateSummary }}</span>
        <TxPagination
          v-if="filteredUpdates.length > UPDATES_PAGE_SIZE"
          v-model:current-page="currentUpdatePage"
          :total="filteredUpdates.length"
          :page-size="UPDATES_PAGE_SIZE"
          show-info
          show-first-last
        >
          <template #info="{ currentPage, totalPages: pages }">
            {{ isZh ? `第 ${currentPage} / ${pages} 页` : `Page ${currentPage} of ${pages}` }}
          </template>
        </TxPagination>
      </div>
    </section>

    <DashboardUpdateFormDrawer
      :open="drawerOpen"
      :mode="drawerMode"
      :update="editingUpdate"
      @close="drawerOpen = false"
      @saved="onSaved"
    />

    <TxBottomDialog
      v-if="deleteConfirmVisible"
      :title="t('dashboard.sections.updates.deleteTitle', 'Delete Update')"
      :message="t('dashboard.sections.updates.confirmDelete', { title: resolveLocalizedText(pendingDeleteUpdate?.title || { zh: '', en: '' }) })"
      :btns="[
        { content: t('dashboard.sections.updates.cancel', 'Cancel'), type: 'info', onClick: () => true },
        { content: t('dashboard.sections.updates.delete', 'Delete'), type: 'error', onClick: confirmDeleteUpdate },
      ]"
      :close="closeDeleteConfirm"
    />
  </div>
</template>

<style scoped>
.UpdateFilters {
  min-width: 0;
}

.UpdateFilters-Grid {
  display: grid;
  gap: 10px;
  grid-template-columns: repeat(auto-fit, minmax(160px, 1fr));
}

.UpdateFilters-Field {
  min-width: 0;
  display: flex;
  flex-direction: column;
  gap: 6px;
}

.UpdateFilters-Field--search {
  grid-column: 1 / -1;
}

.UpdateFilters-Field > * {
  min-width: 0;
}

.UpdateFilters-Label {
  font-size: 12px;
  font-weight: 500;
  color: color-mix(in srgb, var(--tx-text-color-secondary, rgba(150, 150, 150, 1)) 88%, transparent);
}

.UpdateFilters-Actions {
  margin-top: 10px;
  display: flex;
  justify-content: flex-end;
}

.UpdateTable {
  overflow-x: auto;
  border-radius: 14px;
}

.UpdateTable-Data {
  --tx-data-table-title-color: var(--tx-text-color-primary, rgba(245, 245, 245, 0.92));
  --update-table-sticky-bg: var(--tx-bg-color, #fff);
  overflow: visible;
}

.UpdateTable-Data :deep(.UpdateTable-ActionsHeader),
.UpdateTable-Data :deep(.UpdateTable-ActionsCell) {
  position: sticky;
  right: 0;
  z-index: 3;
  background-color: var(--update-table-sticky-bg);
  background-image: linear-gradient(
    to right,
    #0000,
    color-mix(in srgb, var(--update-table-sticky-bg) 56%, rgba(0, 0, 0, 0.28)) 54%,
    var(--update-table-sticky-bg)
  );
  background-repeat: no-repeat;
  background-size: 18px 100%;
  box-shadow:
    -1px 0 0 color-mix(in srgb, var(--tx-border-color-lighter, rgba(120, 120, 120, 0.24)) 90%, transparent),
    -5px 0 12px -11px rgba(0, 0, 0, 0.9);
}

.UpdateTable-Data :deep(.UpdateTable-ActionsHeader) {
  z-index: 4;
}

.dark .UpdateTable-Data {
  --update-table-sticky-bg: var(--tx-bg-color, #121212);
}

.UpdateTable-TitleCell {
  min-width: 0;
  display: flex;
  flex-direction: column;
  gap: 5px;
}

.UpdateTable-TitleButton {
  display: inline-flex;
  max-width: 100%;
  padding: 0;
  border: 0;
  background: transparent;
  color: var(--tx-data-table-title-color);
  font: inherit;
  font-weight: 650;
  letter-spacing: 0;
  text-align: left;
  cursor: pointer;
}

.UpdateTable-TitleButton:disabled {
  cursor: default;
}

.UpdateTable-TitleButton:not(:disabled):hover {
  color: var(--tx-color-primary);
}

.UpdateTable-Summary {
  margin: 0;
  max-width: 38rem;
  color: color-mix(in srgb, var(--tx-text-color-secondary, rgba(150, 150, 150, 1)) 94%, transparent);
  font-size: 12px;
  line-height: 1.45;
}

.UpdateTable-Tags {
  display: flex;
  flex-wrap: wrap;
  align-items: center;
  gap: 6px;
}

.UpdateTable-Tag {
  letter-spacing: 0;
}

.UpdateTable-Date,
.UpdateTable-Muted {
  font-size: 12px;
  color: color-mix(in srgb, var(--tx-text-color-secondary, rgba(150, 150, 150, 1)) 90%, transparent);
}

.UpdateTable-Actions {
  display: flex;
  align-items: center;
  justify-content: flex-end;
  gap: 8px;
}

.UpdateTable-IconButton {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  width: 24px;
  height: 24px;
  padding: 0;
  border: 0;
  border-radius: 6px;
  background: transparent;
  color: color-mix(in srgb, var(--tx-text-color-secondary, rgba(150, 150, 150, 1)) 92%, transparent);
  cursor: pointer;
}

.UpdateTable-IconButton:hover {
  color: var(--tx-color-primary);
}

.UpdateTable-IconButton:focus-visible {
  outline: 2px solid color-mix(in srgb, var(--tx-color-primary) 68%, transparent);
  outline-offset: 2px;
}

.UpdateTable-IconButton > span {
  width: 16px;
  height: 16px;
}

.UpdateTable-Footer {
  border-top: 1px solid color-mix(in srgb, var(--tx-border-color-lighter, rgba(120, 120, 120, 0.24)) 100%, transparent);
  display: flex;
  flex-wrap: wrap;
  align-items: center;
  justify-content: space-between;
  gap: 12px;
  padding-top: 10px;
}

.UpdateTable-Count {
  color: color-mix(in srgb, var(--tx-text-color-secondary, rgba(150, 150, 150, 1)) 82%, transparent);
  font-size: 12px;
}

.UpdateTable-Footer :deep(.tx-pagination) {
  align-items: flex-end;
  gap: 6px;
}

.UpdateTable-Footer :deep(.tx-pagination__list) {
  display: flex;
  flex-wrap: wrap;
  justify-content: flex-end;
  gap: 6px;
  margin: 0;
  padding: 0;
  list-style: none;
}

.UpdateTable-Footer :deep(.tx-pagination__item) {
  display: flex;
  flex: 0 0 auto;
  margin: 0;
  padding: 0;
  list-style: none;
}

.UpdateTable-Footer :deep(.tx-pagination__item::marker) {
  content: '';
}

.UpdateTable-Footer :deep(.tx-pagination__info) {
  color: color-mix(in srgb, var(--tx-text-color-secondary, rgba(150, 150, 150, 1)) 82%, transparent);
  font-size: 12px;
}

@media (max-width: 760px) {
  .UpdateTable-Footer {
    align-items: flex-start;
    flex-direction: column;
  }

  .UpdateTable-Footer :deep(.tx-pagination) {
    align-items: flex-start;
  }

  .UpdateTable-Footer :deep(.tx-pagination__list) {
    justify-content: flex-start;
  }
}
</style>
