// Adapted from Amicro (MIT). Copyright (c) 2026 SYED  SUBHAN UDDIN.
import { MOTION_METRIC_INTERACTIONS } from './types'
export const MOTION_METRIC_SOURCE_MAP = [
  { name: 'AnimatedMetricCard', source: 'src/components/metrics/AnimatedMetricCard.tsx:12-1147', variants: ['animated-metric-card'], interactions: MOTION_METRIC_INTERACTIONS, catalog: ['m-cache-bandwidth', 'm-net-matrix', 'm-progress-piano', 'm-server-step', 'm-overview-scrubber', 'm-sales-dual', 'm-sales-arc', 'm-sales-radial-dash', 'm-credit-barcode', 'm-mono-stock', 'm-users-pill', 'm-views-wave', 'm-mono-heatmap', 'm-timer-prep', 'm-noise-level'] },
  { name: 'Budget', source: 'src/components/metrics/Budget.tsx:1-37', variants: ['budget'], catalog: [] },
  { name: 'CacheStatsCard', source: 'src/components/metrics/CacheStatsCard.tsx:3-95', variants: ['cache-stats-card', 'cacheable-bandwidth-cost'], catalog: ['m-cache-bandwidth'] },
  { name: 'CourseProgressCard', source: 'src/components/metrics/CourseProgressCard.tsx:3-91', variants: ['course-progress-card'], catalog: [] },
  { name: 'CreditScoreCards', source: 'src/components/metrics/CreditScoreCards.tsx:10-148', variants: ['credit-score-cards'], catalog: [] },
  { name: 'FeedbackCard', source: 'src/components/metrics/FeedbackCard.tsx:3-78', variants: ['feedback-card'], catalog: [] },
  { name: 'FinanceDashboard', source: 'src/components/metrics/FinanceDashboard.tsx:3-181', variants: ['finance-dashboard'], catalog: ['m-credit-barcode'] },
  { name: 'Growth', source: 'src/components/metrics/Growth.tsx:3-47', variants: ['growth'], catalog: [] },
  { name: 'GrowthCalendar', source: 'src/components/metrics/GrowthCalendar.tsx:3-106', variants: ['growth-calendar', 'users-growth-pill-progress'], catalog: ['m-users-pill'] },
  { name: 'HealthCards', source: 'src/components/metrics/HealthCards.tsx:26-333', variants: ['health-cards'], catalog: [] },
  { name: 'MarketingCards', source: 'src/components/metrics/MarketingCards.tsx:3-76', variants: ['marketing-cards'], catalog: [] },
  { name: 'NetworkTelemetry', source: 'src/components/metrics/NetworkTelemetry.tsx:3-78', variants: ['network-telemetry', 'network-telemetry-matrix'], catalog: ['m-net-matrix'] },
  { name: 'NoiseCards', source: 'src/components/metrics/NoiseCards.tsx:1-67', variants: ['noise-cards', 'noise-decibel-level'], catalog: ['m-noise-level'] },
  { name: 'OverviewChart', source: 'src/components/metrics/OverviewChart.tsx:3-73', variants: ['overview-chart', 'overview-bar-scrubber-card'], catalog: ['m-overview-scrubber'] },
  { name: 'ProgressIndicator', source: 'src/components/metrics/ProgressIndicator.tsx:3-39', variants: ['progress-indicator', 'progress-indicator-piano'], catalog: ['m-progress-piano'] },
  { name: 'PromptsCard', source: 'src/components/metrics/PromptsCard.tsx:1-25', variants: ['prompts-card'], catalog: [] },
  { name: 'RealTimeAlerts', source: 'src/components/metrics/RealTimeAlerts.tsx:1-69', variants: ['real-time-alerts'], catalog: [] },
  { name: 'RunningStatsCard', source: 'src/components/metrics/RunningStatsCard.tsx:1-60', variants: ['running-stats-card'], catalog: [] },
  { name: 'SalesDashboard', source: 'src/components/metrics/SalesDashboard.tsx:3-190', variants: ['sales-dashboard', 'sales-analytics-dual-bars', 'sales-target-segmented-arc'], catalog: ['m-sales-dual', 'm-sales-arc'] },
  { name: 'SalesOverview', source: 'src/components/metrics/SalesOverview.tsx:3-68', variants: ['sales-overview', 'sales-overview-radial-dashboard'], catalog: ['m-sales-radial-dash'] },
  { name: 'SavingsCards', source: 'src/components/metrics/SavingsCards.tsx:14-142', variants: ['savings-cards'], catalog: [] },
  { name: 'ServerPerformance', source: 'src/components/metrics/ServerPerformance.tsx:3-26', variants: ['server-performance', 'server-performance-step-bars'], catalog: ['m-server-step'] },
  { name: 'StatusCards', source: 'src/components/metrics/StatusCards.tsx:3-179', variants: ['status-cards'], catalog: [] },
  { name: 'StockChartCard', source: 'src/components/metrics/StockChartCard.tsx:27-139', variants: ['stock-chart-card', 'mono-stock'], catalog: ['m-mono-stock'] },
  { name: 'SystemMetricsCard', source: 'src/components/metrics/SystemMetricsCard.tsx:3-107', variants: ['system-metrics-card'], catalog: [] },
  { name: 'TimerCard', source: 'src/components/metrics/TimerCard.tsx:3-41', variants: ['timer-card', 'timer-preparation-segmented'], catalog: ['m-timer-prep'] },
  { name: 'UserMetrics', source: 'src/components/metrics/UserMetrics.tsx:3-133', variants: ['user-metrics', 'views-hourly-wave-chart'], catalog: ['m-views-wave'] },
  { name: 'UsersChartCard', source: 'src/components/metrics/UsersChartCard.tsx:22-116', variants: ['users-chart-card'], catalog: [] },
  { name: 'VisitorsChartCard', source: 'src/components/metrics/VisitorsChartCard.tsx:41-170', variants: ['visitors-chart-card'], catalog: [] },
] as const
