name = "tuff-pilot"
compatibility_date = "2024-09-23"
compatibility_flags = [
  "nodejs_compat",
  "enable_nodejs_http_modules",
  "no_nodejs_compat_v2"
]
pages_build_output_dir = "dist"

[vars]
NUXT_PUBLIC_NEXUS_ORIGIN = "https://tuff.tagzxia.com"
NUXT_PILOT_BASE_URL = "https://sub2api-home.tagzxia.com"
NUXT_PUBLIC_ENDS_URL = "https://sub2api-home.tagzxia.com"

[env.preview]
compatibility_date = "2024-09-23"
compatibility_flags = [
  "nodejs_compat",
  "enable_nodejs_http_modules",
  "no_nodejs_compat_v2"
]

[env.preview.vars]
NUXT_PUBLIC_NEXUS_ORIGIN = "https://tuff.tagzxia.com"
NUXT_PILOT_BASE_URL = "https://sub2api-home.tagzxia.com"
NUXT_PUBLIC_ENDS_URL = "https://sub2api-home.tagzxia.com"

[[env.preview.d1_databases]]
binding = "DB"
database_name = "tuff-pilot-preview"
database_id = "d5c88a58-1b85-4e01-b082-48132e513b88"

[[env.preview.r2_buckets]]
binding = "PILOT_ATTACHMENTS"
bucket_name = "tuff-pilot-preview-attachments"

[env.production]
compatibility_date = "2024-09-23"
compatibility_flags = [
  "nodejs_compat",
  "enable_nodejs_http_modules",
  "no_nodejs_compat_v2"
]

[env.production.vars]
NUXT_PUBLIC_NEXUS_ORIGIN = "https://tuff.tagzxia.com"
NUXT_PILOT_BASE_URL = "https://sub2api-home.tagzxia.com"
NUXT_PUBLIC_ENDS_URL = "https://sub2api-home.tagzxia.com"

[[env.production.d1_databases]]
binding = "DB"
database_name = "tuff-pilot-production"
database_id = "116e394c-6bac-4e32-ae9c-438fec188901"

[[env.production.r2_buckets]]
binding = "PILOT_ATTACHMENTS"
bucket_name = "tuff-pilot-production-attachments"
