/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/api/v1/sync/handshake": {
    post: {
      parameters: {
        header: {
          "x-device-id": components["parameters"]["XDeviceId"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": {
              sync_token: string;
              server_cursor: number;
              device_id: string;
              quotas: components["schemas"]["QuotaInfo"];
            };
          };
        };
        /** @description Quota exceeded */
        403: {
          content: {
            "application/json": components["schemas"]["ErrorResponse"];
          };
        };
      };
    };
  };
  "/api/v1/sync/push": {
    post: {
      parameters: {
        header: {
          "x-device-id": components["parameters"]["XDeviceId"];
          "x-sync-token": components["parameters"]["XSyncToken"];
        };
      };
      requestBody: {
        content: {
          "application/json": {
            items: components["schemas"]["SyncItemInput"][];
          };
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": {
              ack_cursor: number;
              conflicts: components["schemas"]["ConflictItem"][];
            };
          };
        };
        /** @description Invalid payload */
        400: {
          content: {
            "application/json": components["schemas"]["ErrorResponse"];
          };
        };
        /** @description Quota exceeded */
        403: {
          content: {
            "application/json": components["schemas"]["ErrorResponse"];
          };
        };
      };
    };
  };
  "/api/v1/sync/pull": {
    get: {
      parameters: {
        query?: {
          cursor?: number;
          limit?: number;
        };
        header: {
          "x-device-id": components["parameters"]["XDeviceId"];
          "x-sync-token": components["parameters"]["XSyncToken"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": {
              items: components["schemas"]["SyncItemOutput"][];
              oplog: components["schemas"]["OplogOutput"][];
              next_cursor: number;
            };
          };
        };
        /** @description Invalid cursor */
        400: {
          content: {
            "application/json": components["schemas"]["ErrorResponse"];
          };
        };
      };
    };
  };
  "/api/v1/sync/blobs/upload": {
    post: {
      parameters: {
        header: {
          "x-device-id": components["parameters"]["XDeviceId"];
          "x-sync-token": components["parameters"]["XSyncToken"];
        };
      };
      requestBody: {
        content: {
          "multipart/form-data": {
            /** Format: binary */
            file: string;
          };
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": {
              blob_id: string;
              object_key: string;
              sha256: string;
              size_bytes: number;
            };
          };
        };
        /** @description Quota exceeded */
        403: {
          content: {
            "application/json": components["schemas"]["ErrorResponse"];
          };
        };
      };
    };
  };
  "/api/v1/quotas": {
    get: {
      parameters: {
        header: {
          "x-device-id": components["parameters"]["XDeviceId"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["QuotaInfo"];
          };
        };
      };
    };
  };
  "/api/v1/quotas/validate": {
    post: {
      parameters: {
        header: {
          "x-device-id": components["parameters"]["XDeviceId"];
        };
      };
      requestBody: {
        content: {
          "application/json": {
            storage_bytes_delta: number;
            objects_delta: number;
          };
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": {
              ok: boolean;
              code?: string | null;
            };
          };
        };
      };
    };
  };
  "/api/v1/keys/register": {
    post: {
      parameters: {
        header: {
          "x-device-id": components["parameters"]["XDeviceId"];
        };
      };
      requestBody: {
        content: {
          "application/json": {
            key_type: string;
            encrypted_key: string;
            recovery_code_hash?: string | null;
          };
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": {
              keyring_id: string;
            };
          };
        };
      };
    };
  };
  "/api/v1/keys/rotate": {
    post: {
      parameters: {
        header: {
          "x-device-id": components["parameters"]["XDeviceId"];
        };
      };
      requestBody: {
        content: {
          "application/json": {
            key_type: string;
            encrypted_key: string;
          };
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": {
              rotated_at: string;
            };
          };
        };
      };
    };
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    ErrorResponse: {
      errorCode: string;
    };
    QuotaInfo: {
      limits: {
        storage_limit_bytes?: number;
        object_limit?: number;
        item_limit?: number;
        device_limit?: number;
      };
      usage: {
        used_storage_bytes?: number;
        used_objects?: number;
        used_devices?: number;
      };
    };
    SyncItemInput: {
      item_id: string;
      type: string;
      schema_version: number;
      payload_enc?: string | null;
      payload_ref?: string | null;
      meta_plain?: {
        [key: string]: unknown;
      } | null;
      payload_size?: number | null;
      updated_at: string;
      deleted_at?: string | null;
      op_seq: number;
      op_hash: string;
      /** @enum {string} */
      op_type: "upsert" | "delete";
    };
    SyncItemOutput: {
      item_id: string;
      type: string;
      schema_version: number;
      payload_enc?: string | null;
      payload_ref?: string | null;
      meta_plain?: {
        [key: string]: unknown;
      } | null;
      payload_size?: number | null;
      updated_at: string;
      deleted_at?: string | null;
      device_id?: string | null;
    };
    OplogOutput: {
      cursor: number;
      item_id: string;
      op_seq: number;
      op_hash: string;
      /** @enum {string} */
      op_type: "upsert" | "delete";
      updated_at: string;
      device_id: string;
    };
    ConflictItem: {
      item_id: string;
      server_updated_at: string;
      server_device_id?: string | null;
    };
  };
  responses: never;
  parameters: {
    XDeviceId: string;
    XSyncToken: string;
  };
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export type operations = Record<string, never>;
