import { readFileSync } from 'node:fs'
import { describe, expect, it } from 'vitest'

const page = readFileSync(new URL('./[...slug].vue', import.meta.url), 'utf8')
const docsOutline = readFileSync(new URL('../../components/DocsOutline.vue', import.meta.url), 'utf8')
const docsSidebar = readFileSync(new URL('../../components/DocsSidebar.vue', import.meta.url), 'utf8')
const docSection = readFileSync(new URL('../../components/docs/DocSection.vue', import.meta.url), 'utf8')
const docsAsideCards = readFileSync(new URL('../../components/docs/DocsAsideCards.vue', import.meta.url), 'utf8')
const docsAsideCardsShell = readFileSync(new URL('../../components/docs/DocsAsideCardsShell.vue', import.meta.url), 'utf8')
const touchAurora = readFileSync(new URL('../../components/tuff/background/TouchAurora.vue', import.meta.url), 'utf8')
const avatarVariantsDemo = readFileSync(new URL('../../components/content/demos/AvatarVariantsAvatarVariantsGalleryDemo.vue', import.meta.url), 'utf8')
const docsPageClientCache = readFileSync(new URL('../../utils/docs-page-client-cache.ts', import.meta.url), 'utf8')
const docsLayout = readFileSync(new URL('../../layouts/docs.vue', import.meta.url), 'utf8')
const theHeader = readFileSync(new URL('../../components/TheHeader.vue', import.meta.url), 'utf8')
const tuffFooter = readFileSync(new URL('../../components/TuffFooter.vue', import.meta.url), 'utf8')
const docHero = readFileSync(new URL('../../components/docs/DocHero.vue', import.meta.url), 'utf8')
const vortexBackground = readFileSync(new URL('../../components/tuff/VortexBackground.vue', import.meta.url), 'utf8')
const headerControls = readFileSync(new URL('../../components/HeaderControls.vue', import.meta.url), 'utf8')
const globalSearchState = readFileSync(new URL('../../composables/useGlobalSearchState.ts', import.meta.url), 'utf8')
const globalSearch = readFileSync(new URL('../../composables/useGlobalSearch.ts', import.meta.url), 'utf8')
const languageToggle = readFileSync(new URL('../../components/LanguageToggle.vue', import.meta.url), 'utf8')
const languageToggleMenu = readFileSync(new URL('../../components/LanguageToggleMenu.vue', import.meta.url), 'utf8')
const darkToggle = readFileSync(new URL('../../components/DarkToggle.vue', import.meta.url), 'utf8')
const iconComposer = readFileSync(new URL('../../components/icon/IconComposer.vue', import.meta.url), 'utf8')
const backToTop = readFileSync(new URL('../../components/ui/BackToTop.vue', import.meta.url), 'utf8')
const appRoot = readFileSync(new URL('../../app.vue', import.meta.url), 'utf8')
const pageView = readFileSync(new URL('../../components/PageView.vue', import.meta.url), 'utf8')
const constants = readFileSync(new URL('../../constants/index.ts', import.meta.url), 'utf8')
const toastHost = readFileSync(new URL('../../components/ui/ToastHost.vue', import.meta.url), 'utf8')
const useToast = readFileSync(new URL('../../composables/useToast.ts', import.meta.url), 'utf8')
const tuffDemoWrapper = readFileSync(new URL('../../components/content/TuffDemoWrapper.vue', import.meta.url), 'utf8')
const tuffCodeBlock = readFileSync(new URL('../../components/content/TuffCodeBlock.vue', import.meta.url), 'utf8')
const tuffPropsTable = readFileSync(new URL('../../components/content/TuffPropsTable.vue', import.meta.url), 'utf8')
const mermaidRenderer = readFileSync(new URL('../../utils/mermaid-renderer.ts', import.meta.url), 'utf8')
const docsPageApi = readFileSync(new URL('../../../server/api/docs/page.get.ts', import.meta.url), 'utf8')
const nuxtConfig = readFileSync(new URL('../../../nuxt.config.ts', import.meta.url), 'utf8')
const packageJson = readFileSync(new URL('../../../package.json', import.meta.url), 'utf8')

describe('docs page performance boundaries', () => {
  it('keys catch-all docs pages by route path to avoid stale content on client navigation', () => {
    expect(page).toMatch(/definePageMeta\(\{[\s\S]*key: route => route\.path[\s\S]*\}\)/)
    expect(page).toContain('const router = useRouter()')
    expect(page).toContain('const activeRoutePath = ref(route.path)')
    expect(page).toMatch(/activeRoutePath\.value = router\.currentRoute\.value\.path \|\| route\.path[\s\S]*const removeRouteSync = router\.afterEach\(\(to\) => \{[\s\S]*activeRoutePath\.value = to\.path[\s\S]*onBeforeUnmount\(removeRouteSync\)/)
    expect(page).toContain('const docsLocale = computed(() => resolveDocsLocaleFromRoute(activeRoutePath.value))')
    expect(page).toContain('const docPath = computed(() => normalizeDocsPagePath(activeRoutePath.value))')
    expect(page).toContain("const shouldSplitDocBody = computed(() => normalizeDocsPagePath(activeRoutePath.value).includes('/docs/dev/components'))")
  })

  it('keeps bottom engagement panels behind near-viewport activation', () => {
    expect(page).toContain('shouldMountDocEngagementPanels')
    expect(page).toContain('docEngagementAnchorRef')
    expect(page).toContain('IntersectionObserver')
    expect(page).toContain('requestIdleCallback')
    expect(page).toContain('DOC_ENGAGEMENT_PANEL_DELAY_MS = 3200')
    expect(page).toContain('DOC_ENGAGEMENT_PANEL_IDLE_TIMEOUT_MS = 5000')
    expect(page).toMatch(/setTimeout\(\(\) => \{[\s\S]*IntersectionObserver[\s\S]*DOC_ENGAGEMENT_PANEL_DELAY_MS/)
    expect(page).toMatch(/engagementPanelObserver\.observe\(anchor\)[\s\S]*return[\s\S]*requestIdleCallback/)
    expect(page).toContain('<LazyDocsFeedback v-if="shouldMountDocEngagementPanels"')
    expect(page).toContain('<LazyDocsComments v-if="shouldMountDocEngagementPanels"')
  })

  it('keeps footer aurora behind near-viewport activation', () => {
    expect(tuffFooter).toContain("const LazyTouchAurora = defineAsyncComponent(() => import('./tuff/background/TouchAurora.vue'))")
    expect(tuffFooter).toContain("FOOTER_AURORA_ROOT_MARGIN = '480px 0px'")
    expect(tuffFooter).toContain('const footerRef = ref<HTMLElement | null>(null)')
    expect(tuffFooter).toMatch(/new IntersectionObserver\([\s\S]*FOOTER_AURORA_ROOT_MARGIN[\s\S]*auroraObserver\.observe\(footer\)[\s\S]*return[\s\S]*scheduleAuroraFallback\(\)/)
    expect(tuffFooter).toContain('<footer ref="footerRef"')
    expect(tuffFooter).toContain('<LazyTouchAurora')
    expect(tuffFooter).toContain('v-if="shouldMountAurora"')
  })

  it('keeps docs hero decoration static instead of mounting a canvas animation', () => {
    expect(docHero).not.toContain('FlickeringGrid')
    expect(docHero).not.toContain('<canvas')
    expect(docHero).not.toContain('ResizeObserver')
    expect(docHero).not.toContain('IntersectionObserver')
    expect(docHero).not.toContain('requestAnimationFrame')
    expect(docHero).toContain('.docs-hero::before')
    expect(docHero).toContain('.docs-hero::after')
    expect(docHero).toContain('radial-gradient(circle at center')
  })

  it('keeps lightweight docs tracking separate from bottom engagement widgets', () => {
    expect(page).toContain('DOC_CLIENT_PANEL_IDLE_TIMEOUT_MS = 2500')
    expect(page).toContain('DOC_CLIENT_PANEL_INTENT_EVENTS')
    expect(page).toContain('bindDocClientPanelIntentListeners')
    expect(page).toContain('handleDocClientPanelIntent')
    expect(page).toContain('scheduleDocClientPanels')
    expect(page).toMatch(/window\.addEventListener\(eventName, handleDocClientPanelIntent, \{ passive: true \}\)/)
    expect(page).toMatch(/if \('requestIdleCallback' in window\) \{[\s\S]*DOC_CLIENT_PANEL_IDLE_TIMEOUT_MS/)
    expect(page).toMatch(/if \(!isReady \|\| !docsClientPanelsMounted\.value\)[\s\S]*bindDocClientPanelIntentListeners\(\)/)
    expect(page).toMatch(/if \(!isMounted \|\| !isDocsContentReady\.value\)[\s\S]*bindDocClientPanelIntentListeners\(\)/)
    expect(page).toContain('<LazyDocsEngagementClient')
    expect(page).toContain('v-if="shouldMountDocClientPanels"')
    expect(page).toContain('<LazyDocsFeedback v-if="shouldMountDocEngagementPanels"')
    expect(page).toContain('<LazyDocsComments v-if="shouldMountDocEngagementPanels"')
  })

  it('keeps docs chrome controls off first-paint TuffEx button imports', () => {
    expect(page).not.toContain("from '@talex-touch/tuffex/button'")
    expect(page).not.toContain("from '@talex-touch/tuffex/loading-state'")
    expect(page).not.toContain('h(TxButton')
    expect(page).not.toContain('<TxLoadingState')
    expect(page).toContain("h(\n        'button'")
    expect(page).toContain('class="docs-loading-state"')

    expect(docsLayout).not.toContain("import Drawer from '~/components/ui/Drawer.vue'")
    expect(docsLayout).not.toContain("import BackToTop from '~/components/ui/BackToTop.vue'")
    expect(docsLayout).toContain("import DocsAsideCardsShell from '~/components/docs/DocsAsideCardsShell.vue'")
    expect(docsLayout).toContain("const DocsDrawer = defineAsyncComponent(() => import('~/components/ui/Drawer.vue'))")
    expect(docsLayout).toContain("const LazyDocsAsideCards = defineAsyncComponent(() => import('~/components/docs/DocsAsideCards.vue'))")
    expect(docsLayout).toContain("const LazyBackToTop = defineAsyncComponent(() => import('~/components/ui/BackToTop.vue'))")
    expect(docsLayout).toContain("const LazyTuffFooter = defineAsyncComponent(() => import('~/components/TuffFooter.vue'))")
    expect(docsLayout).toContain("DOCS_FOOTER_ROOT_MARGIN = '1200px 0px'")
    expect(docsLayout).toContain('const docsFooterSentinelRef = ref<HTMLElement | null>(null)')
    expect(docsLayout).toContain('const shouldMountDocsFooter = ref(false)')
    expect(docsLayout).toContain('let docsFooterObserver: IntersectionObserver | null = null')
    expect(docsLayout).toMatch(/new IntersectionObserver\([\s\S]*DOCS_FOOTER_ROOT_MARGIN[\s\S]*docsFooterObserver\.observe\(sentinel\)/)
    expect(docsLayout).toMatch(/if \(!\('IntersectionObserver' in window\)\) \{[\s\S]*mountDocsFooter\(\)/)
    expect(docsLayout).toContain('BACK_TO_TOP_MOUNT_SCROLL_Y = 240')
    expect(docsLayout).toContain('const shouldMountBackToTop = ref(false)')
    expect(docsLayout).toMatch(/window\.addEventListener\('scroll', scheduleBackToTopMountCheck, \{ passive: true \}\)/)
    expect(docsLayout).toContain('class="docs-mobile-action"')
    expect(docsLayout).not.toContain('<TxButton')
    expect(docsLayout).toContain('const sidebarDrawerMounted = ref(false)')
    expect(docsLayout).toContain('const outlineDrawerMounted = ref(false)')
    expect(docsLayout).toContain('const shouldMountDocsAsideCards = ref(false)')
    expect(docsLayout).toContain('const docsAssistantOpenRequest = ref(0)')
    expect(docsLayout).toContain('const docsAssistantSource = shallowRef<HTMLElement | null>(null)')
    expect(docsLayout).toContain('const docMetaState = useState<Record<string, any>>(\'docs-meta\'')
    expect(docsLayout).toContain('const shouldShowDocsAsideAiNotice = computed(() => {')
    expect(docsLayout).toContain('function openDocsAssistantFromShell(source: HTMLElement | null)')
    expect(docsLayout).toMatch(/watch\(shouldShowDocsAsideAiNotice,[\s\S]*shouldMountDocsAsideCards\.value = true[\s\S]*\{ immediate: true \}/)
    expect(docsLayout).toContain('function openSidebarDrawer()')
    expect(docsLayout).toContain('function openOutlineDrawer()')
    expect(docsLayout).toContain('@click="openSidebarDrawer"')
    expect(docsLayout).toContain('@click="openOutlineDrawer"')
    expect(docsLayout).toContain('<LazyDocsAsideCards\n                  v-if="shouldMountDocsAsideCards"')
    expect(docsLayout).toContain(':assistant-open-request="docsAssistantOpenRequest"')
    expect(docsLayout).toContain(':assistant-source="docsAssistantSource"')
    expect(docsLayout).toContain('<DocsAsideCardsShell @open-assistant="openDocsAssistantFromShell" />')
    expect(docsLayout).not.toContain('<DocsAsideCards />')
    expect(docsLayout).toContain('<DocsDrawer\n        v-if="sidebarDrawerMounted"')
    expect(docsLayout).toContain('<DocsDrawer\n        v-if="outlineDrawerMounted"')
    expect(docsLayout).toContain('<LazyBackToTop v-if="shouldMountBackToTop"')
    expect(docsLayout).toContain('ref="docsFooterSentinelRef"')
    expect(docsLayout).toContain('<LazyTuffFooter v-if="shouldMountDocsFooter"')
    expect(docsLayout).not.toContain('<TuffFooter class="docs-layout-footer"')

    expect(docSection).not.toContain('@talex-touch/tuffex/button')
    expect(docSection).not.toContain('@talex-touch/tuffex/auto-sizer')
    expect(docSection).not.toContain('<TxButton')
    expect(docSection).not.toContain('<TxAutoSizer')
    expect(docSection).toContain('<button\n      v-else')
    expect(docSection).toContain('class="DocSection-Header bg-transparent"')
    expect(docSection).toContain('class="DocSection-Body"')
    expect(docSection).toContain('grid-template-rows: 0fr')
    expect(docSection).toContain('grid-template-rows: 1fr')

    expect(docsAsideCards).not.toContain('@talex-touch/tuffex/button')
    expect(docsAsideCards).not.toContain('<TxButton')
    expect(docsAsideCards).toContain("const LazyDocsAssistantDialog = defineAsyncComponent(() => import('./DocsAssistantDialog.vue'))")
    expect(docsAsideCards).toContain('assistantOpenRequest?: number')
    expect(docsAsideCards).toContain('assistantSource?: HTMLElement | null')
    expect(docsAsideCards).toContain('() => props.assistantOpenRequest')
    expect(docsAsideCards).toContain('assistantOpen.value = true')
    expect(docsAsideCards).not.toContain('class="docs-aside-assistant"')

    expect(docsAsideCardsShell).not.toContain("DocsAssistantDialog")
    expect(docsAsideCardsShell).not.toContain('docs-meta')
    expect(docsAsideCardsShell).toContain('class="docs-aside-assistant"')
    expect(docsAsideCardsShell).toContain('emit(\'openAssistant\', assistantTriggerRef.value)')

    expect(theHeader).toContain("const HeaderUserMenu = defineAsyncComponent(() => import('./HeaderUserMenu.vue'))")
    expect(theHeader).not.toContain("import HeaderUserMenu from './HeaderUserMenu.vue'")
    expect(theHeader).toContain('<HeaderUserMenu />')

    expect(headerControls).not.toContain('@talex-touch/tuffex/button')
    expect(headerControls).not.toContain('<TxButton')
    expect(headerControls).not.toContain('<TxDivider')
    expect(headerControls).toContain('class="HeaderControls-IconButton"')
    expect(headerControls).toContain('class="HeaderControls-Divider"')

    expect(languageToggle).not.toContain('@talex-touch/tuffex/icon-button')
    expect(languageToggle).not.toContain('<TxIconButton')
    expect(languageToggle).toContain('class="LanguageToggle-Trigger"')
    expect(languageToggle).not.toContain('@floating-ui/vue')
    expect(languageToggle).not.toContain("import Icon from './icon/Icon.vue'")
    expect(languageToggle).toContain("defineAsyncComponent(() => import('./LanguageToggleMenu.vue'))")
    expect(languageToggle).toContain('<LazyLanguageToggleMenu')
    expect(languageToggle).toContain('v-if="isMenuRequested"')
    expect(languageToggle).toContain('function requestMenu()')
    expect(languageToggle).toContain('function handleTriggerClick()')
    expect(languageToggle).toContain('@focus="requestMenu"')
    expect(languageToggleMenu).toContain('@floating-ui/vue')

    expect(darkToggle).not.toContain('@talex-touch/tuffex/icon-button')
    expect(darkToggle).not.toContain('<TxIconButton')
    expect(darkToggle).toContain('class="DarkToggle"')

    expect(iconComposer).not.toContain('fonts.googleapis.com')
    expect(iconComposer).not.toContain('Space Grotesk')
    expect(iconComposer).toContain('font-nexus-display')

    expect(backToTop).not.toContain('<TxButton')
    expect(backToTop).toContain('<button v-show="visible"')
    expect(backToTop).toContain('class="back-to-top"')

    expect(toastHost).not.toContain('@talex-touch/tuffex/button')
    expect(toastHost).not.toContain('<TxButton')
    expect(toastHost).toContain('class="toast-dismiss"')

    expect(tuffDemoWrapper).not.toContain('<TxButton')
    expect(tuffDemoWrapper).toContain('class="tuff-demo__reset-btn"')
    expect(tuffDemoWrapper).toContain('class="tuff-demo__toggle-btn"')
    expect(tuffDemoWrapper).toContain('class="tuff-demo__run-btn"')
    expect(tuffDemoWrapper).toContain('<LazyTuffDemoClientRenderer')
    expect(tuffDemoWrapper).not.toContain('<TuffDemoClientRenderer')
    expect(tuffDemoWrapper).toContain('<LazyTuffCodeBlock')
    expect(tuffDemoWrapper).toContain('v-if="showCode"')
    expect(tuffDemoWrapper).not.toContain('<TuffCodeBlock')
    expect(tuffDemoWrapper).not.toContain('IntersectionObserver')
    expect(tuffDemoWrapper).not.toContain('scheduleDemoActivation')

    expect(tuffCodeBlock).not.toContain("from '~/utils/highlight'")
    expect(tuffCodeBlock).toContain("await import('~/utils/highlight')")
    expect(tuffCodeBlock).toContain("await import('~/utils/mermaid-renderer')")
    expect(tuffCodeBlock).not.toContain('<TxButton')
    expect(tuffCodeBlock).toContain('class="tuff-code-block__copy"')

    expect(tuffPropsTable).not.toContain("from 'vue-sonner'")
    expect(tuffPropsTable).not.toContain('<TxButton')
    expect(tuffPropsTable).not.toContain('<TxTag')
    expect(tuffPropsTable).toContain('class="tuff-props-table__copy-status"')
    expect(tuffPropsTable).toContain('class="tuff-props-table__tag"')
    expect(tuffPropsTable).toContain('class="tuff-props-table__mono"')
  })

  it('keeps Mermaid rendering out of the global first-paint plugin list', () => {
    expect(nuxtConfig).toContain("'app/plugins/mermaid.client.ts'")
    expect(page).toContain('function renderMermaidBlocks()')
    expect(page).toContain("await import('~/utils/mermaid-renderer')")

    expect(mermaidRenderer).toContain("await import('mermaid')")
    expect(mermaidRenderer).toContain('renderMermaidInDocument')
    expect(mermaidRenderer).not.toContain("from 'mermaid'")
  })

  it('keeps global search indexes behind explicit search intent', () => {
    expect(appRoot).not.toContain('useGlobalSearch()')
    expect(appRoot).toContain('useGlobalSearchState()')
    expect(headerControls).not.toContain("import { useGlobalSearch } from '~/composables/useGlobalSearch'")
    expect(headerControls).toContain('~/composables/useGlobalSearchState')

    expect(globalSearchState).not.toContain('@talex-touch/utils/search')
    expect(globalSearchState).not.toContain('~/data/search/featureIndex')
    expect(globalSearchState).not.toContain('~/data/search/pageIndex')
    expect(globalSearchState).not.toContain('queryCollection')

    expect(globalSearch).not.toContain("from '@talex-touch/utils/search'")
    expect(globalSearch).not.toContain("import('@talex-touch/utils/search')")
    expect(globalSearch).not.toContain("from '~/data/search/featureIndex'")
    expect(globalSearch).not.toContain("from '~/data/search/pageIndex'")
    expect(globalSearch).toContain("import('@talex-touch/utils/search/feature-matcher')")
    expect(globalSearch).toContain("import('~/data/search/featureIndex')")
    expect(globalSearch).toContain("import('~/data/search/pageIndex')")
  })

  it('keeps the global toast host out of first-paint docs modules', () => {
    expect(constants).toContain("toastHostRequestedEvent = 'nexus:toast-host-requested'")
    expect(appRoot).not.toContain('<ToastContainer />')
    expect(appRoot).toContain("const LazyToastContainer = defineAsyncComponent(() => import('~/components/ToastContainer.vue'))")
    expect(appRoot).toContain('const toastHostMounted = ref(false)')
    expect(appRoot).toContain('function mountToastHost()')
    expect(appRoot).toMatch(/window\.addEventListener\(toastHostRequestedEvent, mountToastHost\)/)
    expect(appRoot).toMatch(/window\.removeEventListener\(toastHostRequestedEvent, mountToastHost\)/)
    expect(appRoot).toContain('<LazyToastContainer v-if="toastHostMounted"')
    expect(useToast).toContain("import { toastHostRequestedEvent } from '~/constants'")
    expect(useToast).toContain('function requestToastHost()')
    expect(useToast).toContain('window.dispatchEvent(new CustomEvent(toastHostRequestedEvent))')
    expect(useToast).toMatch(/toastItems\.value = \[\.\.\.toastItems\.value, toast\][\s\S]*requestToastHost\(\)[\s\S]*scheduleDismiss\(id, toast\.duration\)/)
  })

  it('keeps the browser title reactive when a reused docs route changes', () => {
    expect(page).toMatch(/useHead\(\(\) => \(\{[\s\S]*title: docSeoHead\.value\.pageTitle[\s\S]*\}\)\)/)
  })

  it('preserves Vue Router history state when syncing the outline hash', () => {
    expect(docsOutline).not.toContain("history.replaceState(null, '', next)")
    expect(docsOutline).toMatch(/history\.replaceState\(history\.state, '', `\$\{window\.location\.pathname\}\$\{window\.location\.search\}\$\{next\}`\)/)
  })

  it('keeps docs outline scroll behavior off first-paint VueUse imports', () => {
    expect(docsOutline).not.toContain('@vueuse/core')
    expect(docsOutline).not.toContain('useEventListener')
    expect(docsOutline).not.toContain('useResizeObserver')
    expect(docsOutline).not.toContain('useThrottleFn')
    expect(docsOutline).toContain('function createThrottleFn')
    expect(docsOutline).toContain("window.addEventListener('scroll', onScroll, { passive: true })")
    expect(docsOutline).toContain('new ResizeObserver')
    expect(docsOutline).toContain("window.removeEventListener('scroll', onScroll)")
  })

  it('does not register VueUse as a global Nuxt module for docs first paint', () => {
    expect(nuxtConfig).not.toContain("'@vueuse/nuxt'")
    expect(packageJson).not.toContain('"@vueuse/nuxt"')
    expect(packageJson).toContain('"@vueuse/core"')
    expect(page).not.toContain('@vueuse/core')
    expect(page).not.toContain('useTimeAgoIntl')
    expect(page).toContain('function formatRelativeTimeFromNow(date: Date, locale: string)')
    expect(page).toContain('new Intl.RelativeTimeFormat(locale, { numeric: \'auto\' })')
    expect(pageView).toContain("import { useTimeAgo } from '@vueuse/core'")
    expect(vortexBackground).toContain("import { templateRef, useDebounceFn } from '@vueuse/core'")
  })

  it('requests component sidebar metadata by locale instead of downloading both languages', () => {
    expect(docsSidebar).toContain("'/api/docs/sidebar-components'")
    expect(docsSidebar).toMatch(/key: computed\(\(\) => `docs-components-meta:\$\{docsLocale\.value\}`\)/)
    expect(docsSidebar).toMatch(/query: computed\(\(\) => \(\{[\s\S]*locale: docsLocale\.value,[\s\S]*\}\)\)/)
    expect(docsSidebar).toContain('immediate: false')
    expect(docsSidebar).toContain('COMPONENT_DOCS_METADATA_DELAY_MS = 8000')
    expect(docsSidebar).toContain('function requestComponentDocsMetadata()')
    expect(docsSidebar).toContain('function scheduleComponentDocsMetadata()')
    expect(docsSidebar).toContain('@pointerenter="requestComponentDocsMetadata"')
    expect(docsSidebar).toContain('@focusin="requestComponentDocsMetadata"')
    expect(docsSidebar).toContain('@touchstart.passive="requestComponentDocsMetadata"')
    expect(docsSidebar).toContain('const componentItems = computed(() => coerceJsonArray<SidebarComponentDoc>(componentDocsPayload.value) as any[])')
  })

  it('requests docs navigation by locale instead of hydrating both language trees', () => {
    expect(page).toContain("'/api/docs/navigation'")
    expect(docsSidebar).toContain("'/api/docs/navigation'")
    expect(page).toMatch(/key: computed\(\(\) => `docs-navigation:\$\{docsLocale\.value\}`\)/)
    expect(docsSidebar).toMatch(/key: computed\(\(\) => `docs-navigation:\$\{docsLocale\.value\}`\)/)
    expect(page).toMatch(/query: computed\(\(\) => \(\{[\s\S]*locale: docsLocale\.value,[\s\S]*\}\)/)
    expect(docsSidebar).toMatch(/query: computed\(\(\) => \(\{[\s\S]*locale: docsLocale\.value,[\s\S]*\}\)/)
  })

  it('warms component docs links on sidebar intent without enabling bulk NuxtLink prefetch', () => {
    expect(docsSidebar).toContain("import { requestDocsPage } from '~/utils/docs-page-client-cache'")
    expect(docsSidebar).toContain("import { useTypedFetch } from '~/utils/request'")
    expect(docsSidebar).toContain('const prefetchedDocsTargets = new Set<string>()')
    expect(docsSidebar).toMatch(/function shouldPrefetchDocsTarget\(path: string \| null \| undefined\) \{[\s\S]*normalized\?\.startsWith\('\/docs\/dev\/components\/'\)/)
    expect(docsSidebar).toMatch(/function prefetchDocsTarget\(path: string \| null \| undefined\) \{[\s\S]*if \(import\.meta\.server \|\| !shouldPrefetchDocsTarget\(path\)\)[\s\S]*return/)
    expect(docsSidebar).toMatch(/const cacheKey = `\$\{normalized\}:\$\{locale\}`[\s\S]*if \(prefetchedDocsTargets\.has\(cacheKey\)\)[\s\S]*prefetchedDocsTargets\.add\(cacheKey\)/)
    expect(docsSidebar).toMatch(/void preloadRouteComponents\(routeTarget\)/)
    expect(docsSidebar).toContain("requestDocsPage({ path: normalized, locale, body: '0' })")
    expect(docsSidebar).toContain("requestDocsPage({ path: normalized, locale, body: '1' })")
    expect(docsSidebar).toContain('@mouseenter="prefetchDocsTarget(linkTarget(child))"')
    expect(docsSidebar).toContain('@focus="prefetchDocsTarget(linkTarget(child))"')
    expect(docsSidebar).toContain('@touchstart.passive="prefetchDocsTarget(linkTarget(child))"')
    expect(docsSidebar).toContain(':prefetch="false"')
  })

  it('keeps decorative footer aurora from throwing when WebGL2 is unavailable', () => {
    expect(touchAurora).toContain('let auroraDisabled = false')
    expect(touchAurora).toContain("const gl = canvas.getContext('webgl2')")
    expect(touchAurora).toContain('function hasAuroraWebglSupport()')
    expect(touchAurora).toMatch(/if \(!hasAuroraWebglSupport\(\)\) \{[\s\S]*auroraDisabled = true[\s\S]*return[\s\S]*\}/)
    expect(touchAurora).toMatch(/try \{[\s\S]*renderer = new Renderer[\s\S]*\}[\s\S]*catch \{[\s\S]*auroraDisabled = true[\s\S]*renderer = null[\s\S]*return[\s\S]*\}/)
  })

  it('keeps migrated avatar variants demos self-contained for client rendering', () => {
    expect(avatarVariantsDemo).toContain("import AvatarVariantCard from './AvatarVariantCard.vue'")
    expect(avatarVariantsDemo).toContain('<AvatarVariantCard')
  })

  it('caches split full-body docs on the client without deep AST reactivity', () => {
    expect(page).toContain("import { primeDocsPageRequestCache, requestDocsPage } from '~/utils/docs-page-client-cache'")
    expect(page).toContain("import { useTypedFetch } from '~/utils/request'")
    expect(page).toContain('DOCS_FULL_BODY_CACHE_LIMIT = 24')
    expect(page).toContain("DOCS_CURRENT_PAGE_FETCH_KEY = 'docs-current-page'")
    expect(page).not.toContain('DOCS_CURRENT_FULL_BODY_FETCH_KEY')
    expect(page).toContain('const docsFullBodyCache = new Map<string, Record<string, any> | null>()')
    expect(page).toContain('function resolveFullDocCacheKey(value: Record<string, any> | null)')
    expect(page).toContain("const localeMatch = rawPath.match(/\\.(en|zh)$/)")
    expect(page).toContain('function readCachedFullDoc(key: string)')
    expect(page).toContain('function hasCachedFullDoc(key: string)')
    expect(page).toContain('function cacheFullDoc(value: Record<string, any> | null)')
    expect(page).toMatch(/return `doc-full:\$\{normalizedPath\}:\$\{locale\}`/)
    expect(page).toContain('while (docsFullBodyCache.size > DOCS_FULL_BODY_CACHE_LIMIT)')
    expect(page).toMatch(/const fullDocCacheKey = computed\(\(\) => `doc-full:\$\{docPath\.value\}:\$\{docsLocale\.value\}`\)/)
    expect(page).toContain('const fullDoc = shallowRef<Record<string, any> | null>(null)')
    expect(page).toContain('const fullDocLoading = ref(false)')
    expect(page).toContain('key: DOCS_CURRENT_PAGE_FETCH_KEY')
    expect(page).toMatch(/key: DOCS_CURRENT_PAGE_FETCH_KEY,[\s\S]*immediate: import\.meta\.server \|\| !shouldSplitDocBody\.value,[\s\S]*watch: false/)
    expect(page).toMatch(/body: shouldSplitDocBody\.value && import\.meta\.client \? '0' : '1'/)
    expect(page).toMatch(/const renderDoc = computed\(\(\) => \(shouldSplitDocBody\.value \? fullDoc\.value \?\? doc\.value : doc\.value\)\)/)
    expect(page).toContain('let activeDocFetchId = 0')
    expect(page).toContain('async function loadFullDocForRoute(fetchId: number, path: string, locale: \'en\' | \'zh\')')
    expect(page).toMatch(/const cacheKey = `doc-full:\$\{path\}:\$\{locale\}`[\s\S]*if \(hasCachedFullDoc\(cacheKey\)\) \{[\s\S]*fullDoc\.value = readCachedFullDoc\(cacheKey\) \?\? null/)
    expect(page).toMatch(/fullDocLoading\.value = true[\s\S]*requestDocsPage\(\{ path, locale, body: '1' \}\)/)
    expect(page).toMatch(/const cachedFullDoc = cacheFullDoc\(nextFullDoc\)[\s\S]*fullDoc\.value = cachedFullDoc[\s\S]*if \(!doc\.value\) \{[\s\S]*doc\.value = cachedFullDoc[\s\S]*isLoading\.value = false[\s\S]*\}/)
    expect(page).toContain('function seedFullDocFromCurrentDoc()')
    expect(page).toMatch(/function seedFullDocFromCurrentDoc\(\) \{[\s\S]*if \(!shouldSplitDocBody\.value \|\| !doc\.value\?\.body\)[\s\S]*return false[\s\S]*fullDoc\.value = cacheFullDoc\(doc\.value as Record<string, any>\)[\s\S]*return true[\s\S]*\}/)
    expect(page).toContain('function startFullDocFetchForRoute()')
    expect(page).toMatch(/function startFullDocFetchForRoute\(\) \{[\s\S]*if \(seedFullDocFromCurrentDoc\(\)\)[\s\S]*return[\s\S]*const fetchId = \+\+activeDocFetchId[\s\S]*void loadFullDocForRoute\(fetchId, docPath\.value, docsLocale\.value\)[\s\S]*\}/)
    expect(page).toContain('async function loadActiveDocForRoute()')
    expect(page).toMatch(/const fetchId = \+\+activeDocFetchId[\s\S]*const path = docPath\.value[\s\S]*const locale = docsLocale\.value/)
    expect(page).toContain('const hasCachedBody = splitBody && cachedFullDoc !== undefined')
    expect(page).toMatch(/doc\.value = hasCachedBody \? cachedFullDoc : null[\s\S]*fullDoc\.value = hasCachedBody \? cachedFullDoc : null[\s\S]*isLoading\.value = !hasCachedBody[\s\S]*fullDocLoading\.value = splitBody && !hasCachedBody/)
    expect(page).toMatch(/const fullDocRequest = splitBody && !hasCachedBody[\s\S]*\? loadFullDocForRoute\(fetchId, path, locale\)[\s\S]*: null[\s\S]*try \{[\s\S]*requestDocsPage\(\{ path, locale, body: splitBody \? '0' : '1' \}\)/)
    expect(page).toMatch(/if \(fetchId !== activeDocFetchId \|\| path !== docPath\.value \|\| locale !== docsLocale\.value\)[\s\S]*return/)
    expect(page).toMatch(/fullDoc\.value = cachedFullDoc/)
    expect(page).toContain('void fullDocRequest')
    expect(page).toMatch(/if \(import\.meta\.client\)[\s\S]*startFullDocFetchForRoute\(\)/)
    expect(page).toMatch(/watch\(requestKey, \(\) => \{[\s\S]*void loadActiveDocForRoute\(\)[\s\S]*\}\)/)
    expect(page).toMatch(/onMounted\(\(\) => \{[\s\S]*startFullDocFetchForRoute\(\)[\s\S]*\}\)/)
    expect(page).toMatch(/return `\$\{path\}:\$\{docsLocale\.value\}:\$\{source\?\.body \? 'body' : 'meta'\}`/)
    expect(page).not.toContain('shouldClientRenderDocBody')
    expect(page).not.toContain('<ClientOnly v-if="shouldClientRenderDocBody">')
    expect(page).toMatch(/<ContentRenderer[\s\S]*v-if="renderDoc\?\.body"[\s\S]*:value="renderDoc \?\? \{\}"/)
  })

  it('keeps dev fallback metadata requests off full Markdown body parsing', () => {
    expect(docsPageApi).toContain('function parseFrontmatterMetadata(raw: string)')
    expect(docsPageApi).toContain('async function readDevDocsPageFromFile(contentPath: string, includeBody: boolean)')
    expect(docsPageApi).toMatch(/if \(!includeBody\) \{[\s\S]*parseFrontmatterMetadata\(raw\)[\s\S]*metaDoc = doc[\s\S]*return doc[\s\S]*\}/)
    expect(docsPageApi).toMatch(/const \{ parseMarkdown \} = await import\('@nuxtjs\/mdc\/runtime'\)/)
    expect(docsPageApi).not.toContain("import('@nuxtjs/mdc/runtime'),")
    expect(docsPageApi).toContain('fullDoc?: DocsPageRecord')
    expect(docsPageApi).toContain('metaDoc?: DocsPageRecord')
  })

  it('warms pager docs targets into the split-body cache on user intent', () => {
    expect(page).toContain('const prefetchedDocTargets = new Set<string>()')
    expect(page).toContain('function prefetchDocForPath(path: string | null | undefined)')
    expect(page).toMatch(/const cacheKey = `doc-full:\$\{normalized\}:\$\{locale\}`[\s\S]*const prefetchKey = `\$\{normalized\}:\$\{locale\}`/)
    expect(page).toMatch(/void preloadRouteComponents\(toLocalizedDocsPath\(normalized, locale\)\)/)
    expect(page).toContain("requestDocsPage({ path: normalized, locale, body: '0' })")
    expect(page).toMatch(/if \(hasCachedFullDoc\(cacheKey\)\)[\s\S]*return[\s\S]*requestDocsPage\(\{ path: normalized, locale, body: '1' \}\)/)
    expect(page).toMatch(/then\(\(nextFullDoc\) => \{[\s\S]*cacheFullDoc\(nextFullDoc\)/)
    expect(page).toContain('@mouseenter="prefetchDocForPath(pagerPrevPath)"')
    expect(page).toContain('@focus="prefetchDocForPath(pagerPrevPath)"')
    expect(page).toContain('@touchstart.passive="prefetchDocForPath(pagerPrevPath)"')
    expect(page).toContain('@mouseenter="prefetchDocForPath(pagerNextPath)"')
    expect(page).toContain('@focus="prefetchDocForPath(pagerNextPath)"')
    expect(page).toContain('@touchstart.passive="prefetchDocForPath(pagerNextPath)"')
  })

  it('dedupes docs page client requests shared by sidebar prefetch and route loads', () => {
    expect(docsPageClientCache).toContain('const docsPageRequestPending = new Map<string, Promise<DocsPageRecord>>()')
    expect(docsPageClientCache).toContain('const docsPageRequestCache = new Map<string, DocsPageRequestCacheEntry>()')
    expect(docsPageClientCache).toContain('DOCS_PAGE_REQUEST_CACHE_TTL_MS = 30_000')
    expect(docsPageClientCache).toContain('export function resolveDocsPageRequestCacheKey')
    expect(docsPageClientCache).toContain('export function primeDocsPageRequestCache')
    expect(docsPageClientCache).toContain('export function requestDocsPage')
    expect(docsPageClientCache).toMatch(/const pending = docsPageRequestPending\.get\(cacheKey\)[\s\S]*if \(pending\)[\s\S]*return pending/)
    expect(docsPageClientCache).toMatch(/requestJson<DocsPageRecord>\('\/api\/docs\/page'[\s\S]*path,[\s\S]*locale,[\s\S]*body/)
    expect(docsPageClientCache).toMatch(/docsPageRequestPending\.set\(cacheKey, request\)/)
    expect(page).toContain('primeDocsPageRequestCache({')
    expect(page).toContain("requestDocsPage({ path, locale, body: '1' })")
    expect(docsSidebar).toContain("requestDocsPage({ path: normalized, locale, body: '1' })")
  })
})
