import { readFileSync } from 'node:fs'
import { describe, expect, it } from 'vitest'

const page = readFileSync(new URL('./[...slug].vue', import.meta.url), 'utf8')
const docsOutline = readFileSync(new URL('../../components/DocsOutline.vue', import.meta.url), 'utf8')
const docsSidebar = readFileSync(new URL('../../components/DocsSidebar.vue', import.meta.url), 'utf8')
const docSection = readFileSync(new URL('../../components/docs/DocSection.vue', import.meta.url), 'utf8')
const docsAsideCards = readFileSync(new URL('../../components/docs/DocsAsideCards.vue', import.meta.url), 'utf8')
const docsAsideCardsShell = readFileSync(new URL('../../components/docs/DocsAsideCardsShell.vue', import.meta.url), 'utf8')
const touchAurora = readFileSync(new URL('../../components/tuff/background/TouchAurora.vue', import.meta.url), 'utf8')
const avatarVariantsDemo = readFileSync(new URL('../../components/content/demos/AvatarVariantsAvatarVariantsGalleryDemo.vue', import.meta.url), 'utf8')
const docsPageClientCache = readFileSync(new URL('../../utils/docs-page-client-cache.ts', import.meta.url), 'utf8')
const docsLayout = readFileSync(new URL('../../layouts/docs.vue', import.meta.url), 'utf8')
const theHeader = readFileSync(new URL('../../components/TheHeader.vue', import.meta.url), 'utf8')
const tuffFooter = readFileSync(new URL('../../components/TuffFooter.vue', import.meta.url), 'utf8')
const docHero = readFileSync(new URL('../../components/docs/DocHero.vue', import.meta.url), 'utf8')
const docsProseHeading = readFileSync(new URL('../../components/docs/DocsProseHeading.vue', import.meta.url), 'utf8')
const vortexBackground = readFileSync(new URL('../../components/tuff/VortexBackground.vue', import.meta.url), 'utf8')
const headerControls = readFileSync(new URL('../../components/HeaderControls.vue', import.meta.url), 'utf8')
const globalSearchState = readFileSync(new URL('../../composables/useGlobalSearchState.ts', import.meta.url), 'utf8')
const globalSearch = readFileSync(new URL('../../composables/useGlobalSearch.ts', import.meta.url), 'utf8')
const languageToggle = readFileSync(new URL('../../components/LanguageToggle.vue', import.meta.url), 'utf8')
const languageToggleMenu = readFileSync(new URL('../../components/LanguageToggleMenu.vue', import.meta.url), 'utf8')
const darkToggle = readFileSync(new URL('../../components/DarkToggle.vue', import.meta.url), 'utf8')
const iconComposer = readFileSync(new URL('../../components/icon/IconComposer.vue', import.meta.url), 'utf8')
const backToTop = readFileSync(new URL('../../components/ui/BackToTop.vue', import.meta.url), 'utf8')
const appRoot = readFileSync(new URL('../../app.vue', import.meta.url), 'utf8')
const nexusPwaManifest = readFileSync(new URL('../../components/NexusPwaManifest.vue', import.meta.url), 'utf8')
const pageView = readFileSync(new URL('../../components/PageView.vue', import.meta.url), 'utf8')
const constants = readFileSync(new URL('../../constants/index.ts', import.meta.url), 'utf8')
const toastHost = readFileSync(new URL('../../components/ui/ToastHost.vue', import.meta.url), 'utf8')
const useToast = readFileSync(new URL('../../composables/useToast.ts', import.meta.url), 'utf8')
const tuffDemoWrapper = readFileSync(new URL('../../components/content/TuffDemoWrapper.vue', import.meta.url), 'utf8')
const tuffCodeBlock = readFileSync(new URL('../../components/content/TuffCodeBlock.vue', import.meta.url), 'utf8')
const tuffCodeBlockRenderer = readFileSync(new URL('../../components/content/TuffCodeBlockRenderer.vue', import.meta.url), 'utf8')
const tuffPropsTable = readFileSync(new URL('../../components/content/TuffPropsTable.vue', import.meta.url), 'utf8')
const mermaidRenderer = readFileSync(new URL('../../utils/mermaid-renderer.ts', import.meta.url), 'utf8')
const i18nConfig = readFileSync(new URL('../../i18n.config.ts', import.meta.url), 'utf8')
const i18nEn = readFileSync(new URL('../../../i18n/locales/en.ts', import.meta.url), 'utf8')
const i18nZh = readFileSync(new URL('../../../i18n/locales/zh.ts', import.meta.url), 'utf8')
const routeLocaleChunks = readFileSync(new URL('../../utils/route-locale-chunks.ts', import.meta.url), 'utf8')
const routeLocaleMiddleware = readFileSync(new URL('../../middleware/i18n-route-chunks.global.ts', import.meta.url), 'utf8')
const routeLocaleComposable = readFileSync(new URL('../../composables/useRouteLocaleChunks.ts', import.meta.url), 'utf8')
const localeOrchestrator = readFileSync(new URL('../../composables/useLocaleOrchestrator.ts', import.meta.url), 'utf8')
const vueDevtoolsApiNoop = readFileSync(new URL('../../utils/vue-devtools-api-noop.ts', import.meta.url), 'utf8')
const docsPageApi = readFileSync(new URL('../../../server/api/docs/page.get.ts', import.meta.url), 'utf8')
const nuxtConfig = readFileSync(new URL('../../../nuxt.config.ts', import.meta.url), 'utf8')
const packageJson = readFileSync(new URL('../../../package.json', import.meta.url), 'utf8')
const licensePage = readFileSync(new URL('../license.vue', import.meta.url), 'utf8')
const privacyPage = readFileSync(new URL('../privacy.vue', import.meta.url), 'utf8')
const protocolPage = readFileSync(new URL('../protocol.vue', import.meta.url), 'utf8')

describe('docs page performance boundaries', () => {
  it('keys catch-all docs pages by route path to avoid stale content on client navigation', () => {
    expect(page).toMatch(/definePageMeta\(\{[\s\S]*key: route => route\.path[\s\S]*\}\)/)
    expect(page).toContain('const router = useRouter()')
    expect(page).toContain('const activeRoutePath = ref(route.path)')
    expect(page).toMatch(/activeRoutePath\.value = router\.currentRoute\.value\.path \|\| route\.path[\s\S]*const removeRouteSync = router\.afterEach\(\(to\) => \{[\s\S]*activeRoutePath\.value = to\.path[\s\S]*onBeforeUnmount\(removeRouteSync\)/)
    expect(page).toContain('const docsLocale = computed(() => resolveDocsLocaleFromRoute(activeRoutePath.value))')
    expect(page).toContain('const docPath = computed(() => normalizeDocsPagePath(activeRoutePath.value))')
    expect(page).toContain("const shouldSplitDocBody = computed(() => normalizeDocsPagePath(activeRoutePath.value).includes('/docs/dev/components'))")
  })

  it('keeps bottom engagement panels behind near-viewport activation', () => {
    expect(page).toContain('shouldMountDocEngagementPanels')
    expect(page).toContain('docEngagementAnchorRef')
    expect(page).toContain('IntersectionObserver')
    expect(page).toContain('requestIdleCallback')
    expect(page).toContain('DOC_ENGAGEMENT_PANEL_DELAY_MS = 3200')
    expect(page).toContain('DOC_ENGAGEMENT_PANEL_IDLE_TIMEOUT_MS = 5000')
    expect(page).toMatch(/setTimeout\(\(\) => \{[\s\S]*IntersectionObserver[\s\S]*DOC_ENGAGEMENT_PANEL_DELAY_MS/)
    expect(page).toMatch(/engagementPanelObserver\.observe\(anchor\)[\s\S]*return[\s\S]*requestIdleCallback/)
    expect(page).toContain('<LazyDocsFeedback v-if="shouldMountDocEngagementPanels"')
    expect(page).toContain('<LazyDocsComments v-if="shouldMountDocEngagementPanels"')
  })

  it('keeps footer aurora behind near-viewport activation', () => {
    expect(tuffFooter).toContain("const LazyTouchAurora = defineAsyncComponent(() => import('./tuff/background/TouchAurora.vue'))")
    expect(tuffFooter).toContain("FOOTER_AURORA_ROOT_MARGIN = '480px 0px'")
    expect(tuffFooter).toContain('const footerRef = ref<HTMLElement | null>(null)')
    expect(tuffFooter).toMatch(/new IntersectionObserver\([\s\S]*FOOTER_AURORA_ROOT_MARGIN[\s\S]*auroraObserver\.observe\(footer\)[\s\S]*return[\s\S]*scheduleAuroraFallback\(\)/)
    expect(tuffFooter).toContain('<footer ref="footerRef"')
    expect(tuffFooter).toContain('<LazyTouchAurora')
    expect(tuffFooter).toContain('v-if="shouldMountAurora"')
  })

  it('keeps docs hero decoration static instead of mounting a canvas animation', () => {
    expect(docHero).not.toContain('FlickeringGrid')
    expect(docHero).not.toContain('<canvas')
    expect(docHero).not.toContain('ResizeObserver')
    expect(docHero).not.toContain('IntersectionObserver')
    expect(docHero).not.toContain('requestAnimationFrame')
    expect(docHero).toContain('.docs-hero::before')
    expect(docHero).toContain('.docs-hero::after')
    expect(docHero).toContain('radial-gradient(circle at center')
  })

  it('keeps lightweight docs tracking separate from bottom engagement widgets', () => {
    expect(page).toContain('DOC_CLIENT_PANEL_IDLE_TIMEOUT_MS = 2500')
    expect(page).toContain('DOC_CLIENT_PANEL_INTENT_EVENTS')
    expect(page).toContain('bindDocClientPanelIntentListeners')
    expect(page).toContain('handleDocClientPanelIntent')
    expect(page).toContain('scheduleDocClientPanels')
    expect(page).toMatch(/window\.addEventListener\(eventName, handleDocClientPanelIntent, \{ passive: true \}\)/)
    expect(page).toMatch(/if \('requestIdleCallback' in window\) \{[\s\S]*DOC_CLIENT_PANEL_IDLE_TIMEOUT_MS/)
    expect(page).toMatch(/if \(!isReady \|\| !docsClientPanelsMounted\.value\)[\s\S]*bindDocClientPanelIntentListeners\(\)/)
    expect(page).toMatch(/if \(!isMounted \|\| !isDocsContentReady\.value\)[\s\S]*bindDocClientPanelIntentListeners\(\)/)
    expect(page).toContain('<LazyDocsEngagementClient')
    expect(page).toContain('v-if="shouldMountDocClientPanels"')
    expect(page).toContain('<LazyDocsFeedback v-if="shouldMountDocEngagementPanels"')
    expect(page).toContain('<LazyDocsComments v-if="shouldMountDocEngagementPanels"')
  })

  it('builds docs assistant context only after assistant intent', () => {
    expect(docsLayout).toContain("const docsAssistantContextRequestState = useState<number>('docs-assistant-context-request'")
    expect(docsLayout).toMatch(/function openDocsAssistantFromShell\(source: HTMLElement \| null\) \{[\s\S]*docsAssistantContextRequestState\.value \+= 1[\s\S]*docsAssistantOpenRequest\.value \+= 1/)

    expect(page).toContain("const docAssistantContextRequestState = useState<number>('docs-assistant-context-request'")
    expect(page).toContain('const pendingAssistantContextRequest = ref(0)')
    expect(page).toContain('function requestAssistantContextBuild(requestId: number)')
    expect(page).toMatch(/watch\([\s\S]*docAssistantContextRequestState,[\s\S]*requestAssistantContextBuild\(requestId\)[\s\S]*\)/)
    expect(page).toMatch(/if \(!body\) \{[\s\S]*startFullDocFetchForRoute\(\)[\s\S]*return[\s\S]*\}/)
    expect(page).toMatch(/if \(pendingAssistantContextRequest\.value > 0\)[\s\S]*requestAssistantContextBuild\(pendingAssistantContextRequest\.value\)/)
    expect(page).not.toContain('scheduleAssistantContextBuild(renderDoc.value?.body, 700)')
  })

  it('keeps docs chrome controls off first-paint TuffEx button imports', () => {
    expect(page).not.toContain("from '@talex-touch/tuffex/button'")
    expect(page).not.toContain("from '@talex-touch/tuffex/loading-state'")
    expect(page).not.toContain('h(TxButton')
    expect(page).not.toContain('<TxLoadingState')
    expect(page).toContain("h(\n        'button'")
    expect(page).toContain('class="docs-loading-state"')

    expect(docsLayout).not.toContain("import Drawer from '~/components/ui/Drawer.vue'")
    expect(docsLayout).not.toContain("import BackToTop from '~/components/ui/BackToTop.vue'")
    expect(docsLayout).toContain("const DocsDrawer = defineAsyncComponent(() => import('~/components/ui/Drawer.vue'))")
    expect(docsLayout).toContain("const LazyDocsAsideCards = defineAsyncComponent(() => import('~/components/docs/DocsAsideCards.vue'))")
    expect(docsLayout).toContain("const LazyDocsAsideCardsShell = defineAsyncComponent(() => import('~/components/docs/DocsAsideCardsShell.vue'))")
    expect(docsLayout).toContain("const LazyDocsOutline = defineAsyncComponent(() => import('~/components/DocsOutline.vue'))")
    expect(docsLayout).toContain("const LazyBackToTop = defineAsyncComponent(() => import('~/components/ui/BackToTop.vue'))")
    expect(docsLayout).toContain("const LazyTuffFooter = defineAsyncComponent(() => import('~/components/TuffFooter.vue'))")
    expect(docsLayout).toContain("DOCS_FOOTER_ROOT_MARGIN = '1200px 0px'")
    expect(docsLayout).toContain('DOCS_ASIDE_SHELL_MOUNT_DELAY_MS = 2400')
    expect(docsLayout).toContain('DOCS_ASIDE_SHELL_IDLE_TIMEOUT_MS = 3600')
    expect(docsLayout).toContain('DOCS_OUTLINE_MOUNT_DELAY_MS = 2000')
    expect(docsLayout).toContain('DOCS_OUTLINE_IDLE_TIMEOUT_MS = 3200')
    expect(docsLayout).toContain('const docsFooterSentinelRef = ref<HTMLElement | null>(null)')
    expect(docsLayout).toContain('const shouldMountDocsFooter = ref(false)')
    expect(docsLayout).toContain('let docsFooterObserver: IntersectionObserver | null = null')
    expect(docsLayout).toMatch(/new IntersectionObserver\([\s\S]*DOCS_FOOTER_ROOT_MARGIN[\s\S]*docsFooterObserver\.observe\(sentinel\)/)
    expect(docsLayout).toMatch(/if \(!\('IntersectionObserver' in window\)\) \{[\s\S]*mountDocsFooter\(\)/)
    expect(docsLayout).toContain('BACK_TO_TOP_MOUNT_SCROLL_Y = 240')
    expect(docsLayout).toContain('const shouldMountBackToTop = ref(false)')
    expect(docsLayout).toMatch(/window\.addEventListener\('scroll', scheduleBackToTopMountCheck, \{ passive: true \}\)/)
    expect(docsLayout).toContain('class="docs-mobile-action"')
    expect(docsLayout).not.toContain('<TxButton')
    expect(docsLayout).toContain('const sidebarDrawerMounted = ref(false)')
    expect(docsLayout).toContain('const outlineDrawerMounted = ref(false)')
    expect(docsLayout).toContain('const shouldMountDocsAsideCards = ref(false)')
    expect(docsLayout).toContain('const shouldMountDocsAsideShell = ref(false)')
    expect(docsLayout).toContain('const shouldMountDocsOutline = ref(false)')
    expect(docsLayout).toContain('const docsAssistantShellTriggerRef = ref<HTMLElement | null>(null)')
    expect(docsLayout).toContain('function clearDocsAsideShellSchedule()')
    expect(docsLayout).toContain('function mountDocsAsideShell()')
    expect(docsLayout).toContain('function scheduleDocsAsideShellMount()')
    expect(docsLayout).toMatch(/docsAsideShellTimer = setTimeout\(\(\) => \{[\s\S]*window\.requestIdleCallback\(mount, \{ timeout: DOCS_ASIDE_SHELL_IDLE_TIMEOUT_MS \}\)[\s\S]*DOCS_ASIDE_SHELL_MOUNT_DELAY_MS/)
    expect(docsLayout).toContain("const outlineTocState = useState<any[]>('docs-toc'")
    expect(docsLayout).toContain("const outlineLoadingState = useState<boolean>('docs-outline-loading'")
    expect(docsLayout).toContain('function clearDocsOutlineSchedule()')
    expect(docsLayout).toContain('function mountDocsOutline()')
    expect(docsLayout).toContain('function scheduleDocsOutlineMount()')
    expect(docsLayout).toMatch(/docsOutlineTimer = setTimeout\(\(\) => \{[\s\S]*window\.requestIdleCallback\(mount, \{ timeout: DOCS_OUTLINE_IDLE_TIMEOUT_MS \}\)[\s\S]*DOCS_OUTLINE_MOUNT_DELAY_MS/)
    expect(docsLayout).toMatch(/watch\(shouldShowAsideOutline,[\s\S]*scheduleDocsOutlineMount\(\)[\s\S]*clearDocsOutlineSchedule\(\)/)
    expect(docsLayout).toContain('const docsAssistantOpenRequest = ref(0)')
    expect(docsLayout).toContain('const docsAssistantSource = shallowRef<HTMLElement | null>(null)')
    expect(docsLayout).toContain('const docMetaState = useState<Record<string, any>>(\'docs-meta\'')
    expect(docsLayout).toContain('const shouldShowDocsAsideAiNotice = computed(() => {')
    expect(docsLayout).toContain("const docsAsideAiNoticeTitle = computed(() => t('docs.aiNotice.title'))")
    expect(docsLayout).toContain("const docsAsideAiNoticeDescription = computed(() => t('docs.aiNotice.description'))")
    expect(docsLayout).toContain('function openDocsAssistantFromShell(source: HTMLElement | null)')
    expect(docsLayout).toContain('function openDocsAssistantFromPlaceholder()')
    expect(docsLayout).toMatch(/function openDocsAssistantFromShell\(source: HTMLElement \| null\) \{[\s\S]*mountDocsAsideShell\(\)[\s\S]*docsAssistantOpenRequest\.value \+= 1/)
    expect(docsLayout).not.toContain('watch(shouldShowDocsAsideAiNotice')
    expect(docsLayout).toContain('class="docs-aside-ai-notice"')
    expect(docsLayout).toContain('{{ docsAsideAiNoticeTitle }}')
    expect(docsLayout).toContain('{{ docsAsideAiNoticeDescription }}')
    expect(docsLayout).toContain('function openSidebarDrawer()')
    expect(docsLayout).toContain('function openOutlineDrawer()')
    expect(docsLayout).toMatch(/function openOutlineDrawer\(\) \{[\s\S]*mountDocsOutline\(\)[\s\S]*outlineVisible\.value = true/)
    expect(docsLayout).toContain('@click="openSidebarDrawer"')
    expect(docsLayout).toContain('@click="openOutlineDrawer"')
    expect(docsLayout).toContain('<LazyDocsOutline v-if="shouldMountDocsOutline"')
    expect(docsLayout).toContain('v-else class="docs-outline-shell"')
    expect(docsLayout).toContain('.docs-outline-shell__line')
    expect(docsLayout).toContain('<LazyDocsOutline v-if="outlineVisible && shouldMountDocsOutline"')
    expect(docsLayout).not.toContain('<DocsOutline />')
    expect(docsLayout).not.toContain('<DocsOutline v-if="outlineVisible"')
    expect(docsLayout).toContain('<LazyDocsAsideCards\n                  v-if="shouldMountDocsAsideCards"')
    expect(docsLayout).toContain(':assistant-open-request="docsAssistantOpenRequest"')
    expect(docsLayout).toContain(':assistant-source="docsAssistantSource"')
    expect(docsLayout).toMatch(/<section[\s\S]*v-if="shouldShowDocsAsideAiNotice"[\s\S]*class="docs-aside-ai-notice"[\s\S]*<\/section>/)
    expect(docsLayout).toContain('<LazyDocsAsideCardsShell')
    expect(docsLayout).toContain('v-if="shouldMountDocsAsideShell"')
    expect(docsLayout).toContain('@open-assistant="openDocsAssistantFromShell"')
    expect(docsLayout).toContain('class="docs-aside-assistant-shell"')
    expect(docsLayout).toContain('@click="openDocsAssistantFromPlaceholder"')
    expect(docsLayout).not.toContain('<DocsAsideCardsShell')
    expect(docsLayout).not.toContain('<DocsAsideCards />')
    expect(docsLayout).toContain('<DocsDrawer\n        v-if="sidebarDrawerMounted"')
    expect(docsLayout).toContain('<DocsDrawer\n        v-if="outlineDrawerMounted"')
    expect(docsLayout).toContain('<LazyBackToTop v-if="shouldMountBackToTop"')
    expect(docsLayout).toContain('ref="docsFooterSentinelRef"')
    expect(docsLayout).toContain('<LazyTuffFooter v-if="shouldMountDocsFooter"')
    expect(docsLayout).not.toContain('<TuffFooter class="docs-layout-footer"')

    expect(docSection).not.toContain('@talex-touch/tuffex/button')
    expect(docSection).not.toContain('@talex-touch/tuffex/auto-sizer')
    expect(docSection).not.toContain('<TxButton')
    expect(docSection).not.toContain('<TxAutoSizer')
    expect(docSection).toContain('<button\n      v-else')
    expect(docSection).toContain('class="DocSection-Header bg-transparent"')
    expect(docSection).toContain('class="DocSection-Body"')
    expect(docSection).toContain('grid-template-rows: 0fr')
    expect(docSection).toContain('grid-template-rows: 1fr')

    expect(docsAsideCards).not.toContain('@talex-touch/tuffex/button')
    expect(docsAsideCards).not.toContain('<TxButton')
    expect(docsAsideCards).toContain("const LazyDocsAssistantDialog = defineAsyncComponent(() => import('./DocsAssistantDialog.vue'))")
    expect(docsAsideCards).toContain('assistantOpenRequest?: number')
    expect(docsAsideCards).toContain('assistantSource?: HTMLElement | null')
    expect(docsAsideCards).toContain('() => props.assistantOpenRequest')
    expect(docsAsideCards).toContain('assistantOpen.value = true')
    expect(docsAsideCards).not.toContain('class="docs-aside-assistant"')
    expect(docsAsideCards).not.toContain('syncStatus')
    expect(docsAsideCards).not.toContain('showAiNotice')
    expect(docsAsideCards).not.toContain('docs-aside-card--notice')

    expect(docsAsideCardsShell).not.toContain("DocsAssistantDialog")
    expect(docsAsideCardsShell).not.toContain('docs-meta')
    expect(docsAsideCardsShell).toContain('class="docs-aside-assistant"')
    expect(docsAsideCardsShell).toContain('emit(\'openAssistant\', assistantTriggerRef.value)')

    expect(theHeader).toContain("const HeaderUserMenu = defineAsyncComponent(() => import('./HeaderUserMenu.vue'))")
    expect(theHeader).not.toContain("import HeaderUserMenu from './HeaderUserMenu.vue'")
    expect(theHeader).toContain('<HeaderUserMenu />')

    expect(headerControls).not.toContain('@talex-touch/tuffex/button')
    expect(headerControls).not.toContain('<TxButton')
    expect(headerControls).not.toContain('<TxDivider')
    expect(headerControls).toContain('class="HeaderControls-IconButton"')
    expect(headerControls).toContain('class="HeaderControls-Divider"')

    expect(languageToggle).not.toContain('@talex-touch/tuffex/icon-button')
    expect(languageToggle).not.toContain('<TxIconButton')
    expect(languageToggle).toContain('class="LanguageToggle-Trigger"')
    expect(languageToggle).not.toContain('@floating-ui/vue')
    expect(languageToggle).not.toContain("import Icon from './icon/Icon.vue'")
    expect(languageToggle).toContain("defineAsyncComponent(() => import('./LanguageToggleMenu.vue'))")
    expect(languageToggle).toContain('<LazyLanguageToggleMenu')
    expect(languageToggle).toContain('v-if="isMenuRequested"')
    expect(languageToggle).toContain('function requestMenu()')
    expect(languageToggle).toContain('function handleTriggerClick()')
    expect(languageToggle).toContain('@focus="requestMenu"')
    expect(languageToggleMenu).toContain('@floating-ui/vue')

    expect(darkToggle).not.toContain('@talex-touch/tuffex/icon-button')
    expect(darkToggle).not.toContain('<TxIconButton')
    expect(darkToggle).toContain('class="DarkToggle"')

    expect(iconComposer).not.toContain('fonts.googleapis.com')
    expect(iconComposer).not.toContain('Space Grotesk')
    expect(iconComposer).toContain('font-nexus-display')

    expect(backToTop).not.toContain('<TxButton')
    expect(backToTop).toContain('<button v-show="visible"')
    expect(backToTop).toContain('class="back-to-top"')

    expect(toastHost).not.toContain('@talex-touch/tuffex/button')
    expect(toastHost).not.toContain('<TxButton')
    expect(toastHost).toContain('class="toast-dismiss"')

    expect(tuffDemoWrapper).not.toContain('<TxButton')
    expect(tuffDemoWrapper).toContain('class="tuff-demo__reset-btn"')
    expect(tuffDemoWrapper).toContain('class="tuff-demo__toggle-btn"')
    expect(tuffDemoWrapper).toContain('class="tuff-demo__run-btn"')
    expect(tuffDemoWrapper).toContain('<LazyTuffDemoClientRenderer')
    expect(tuffDemoWrapper).not.toContain('<TuffDemoClientRenderer')
    expect(tuffDemoWrapper).toContain("const LazyEmbeddedCodeBlock = defineAsyncComponent(() => import('./TuffCodeBlock.vue'))")
    expect(tuffDemoWrapper).toContain('<LazyEmbeddedCodeBlock')
    expect(tuffDemoWrapper).toContain('v-if="hasCode && showCode"')
    expect(tuffDemoWrapper).not.toContain('<LazyTuffCodeBlock')
    expect(tuffDemoWrapper).not.toContain('<TuffCodeBlock')
    expect(tuffDemoWrapper).not.toContain('IntersectionObserver')
    expect(tuffDemoWrapper).not.toContain('scheduleDemoActivation')

    expect(tuffCodeBlock).not.toContain("from '~/utils/highlight'")
    expect(tuffCodeBlock).toContain("const LazyTuffCodeBlockRenderer = defineAsyncComponent(() => import('./TuffCodeBlockRenderer.vue'))")
    expect(tuffCodeBlock).not.toContain('<style')
    expect(tuffCodeBlockRenderer).toContain("await import('~/utils/highlight')")
    expect(tuffCodeBlockRenderer).toContain("await import('~/utils/mermaid-renderer')")
    expect(tuffCodeBlock).not.toContain('<TxButton')
    expect(tuffCodeBlockRenderer).not.toContain('<TxButton')
    expect(tuffCodeBlockRenderer).toContain('class="tuff-code-block__copy"')

    expect(tuffPropsTable).not.toContain("from 'vue-sonner'")
    expect(tuffPropsTable).not.toContain('<TxButton')
    expect(tuffPropsTable).not.toContain('<TxTag')
    expect(tuffPropsTable).toContain('class="tuff-props-table__copy-status"')
    expect(tuffPropsTable).toContain('class="tuff-props-table__tag"')
    expect(tuffPropsTable).toContain('class="tuff-props-table__mono"')
  })

  it('keeps route-local locale payloads out of the docs base i18n chunk', () => {
    expect(i18nEn).not.toContain('\n  dashboard: {')
    expect(i18nEn).not.toContain('\n  landing: {')
    expect(i18nZh).not.toContain('\n  dashboard: {')
    expect(i18nZh).not.toContain('\n  landing: {')

    expect(routeLocaleChunks).toContain("dashboard: () => import('../../i18n/locales/route/en/dashboard')")
    expect(routeLocaleChunks).toContain("landing: () => import('../../i18n/locales/route/en/landing')")
    expect(routeLocaleChunks).toContain("dashboard: () => import('../../i18n/locales/route/zh/dashboard')")
    expect(routeLocaleChunks).toContain("landing: () => import('../../i18n/locales/route/zh/landing')")
    expect(routeLocaleChunks).toContain('loadingChunks')
    expect(routeLocaleChunks).not.toContain('loadedChunks')

    expect(routeLocaleComposable).toContain('mergeLocaleMessage')
    expect(routeLocaleComposable).toContain('[chunk]: messages')

    expect(routeLocaleChunks).toContain("normalized === '/' || normalized === '/new' || normalized.startsWith('/new/')")
    expect(routeLocaleChunks).toContain("normalized === '/dashboard'")
    expect(routeLocaleChunks).toContain("normalized.startsWith('/dashboard/')")
    expect(routeLocaleChunks).toContain("normalized === '/store'")
    expect(routeLocaleChunks).toContain("normalized === '/team/join'")
    expect(routeLocaleMiddleware).toContain("import { resolveRouteLocaleChunks } from '~/utils/route-locale-chunks'")
    expect(localeOrchestrator).toContain("import { resolveRouteLocaleChunks } from '~/utils/route-locale-chunks'")
    expect(localeOrchestrator).toContain('await ensureCurrentRouteLocaleChunks(normalized)')
    expect(localeOrchestrator).toContain("const chunks = resolveRouteLocaleChunks(route.path || '/')")
    expect(routeLocaleMiddleware).not.toMatch(/docs[^\\n]*push\\('(dashboard|landing)'\\)/)

    expect(tuffFooter).toContain("await ensureRouteLocaleChunk(normalizeLocale(locale.value) || 'en', 'landing')")
  })

  it('keeps syntax and diagram rendering out of the global first-paint plugin list', () => {
    expect(nuxtConfig).toContain("'app/plugins/highlight.client.ts'")
    expect(nuxtConfig).toContain("'app/plugins/mermaid.client.ts'")
    expect(tuffCodeBlock).toContain("defineAsyncComponent(() => import('./TuffCodeBlockRenderer.vue'))")
    expect(tuffCodeBlock).not.toContain("await import('~/utils/highlight')")
    expect(tuffCodeBlockRenderer).toContain("await import('~/utils/highlight')")
    expect(page).toContain('function renderMermaidBlocks()')
    expect(page).toContain("await import('~/utils/mermaid-renderer')")

    expect(mermaidRenderer).toContain("await import('mermaid')")
    expect(mermaidRenderer).toContain('renderMermaidInDocument')
    expect(mermaidRenderer).not.toContain("from 'mermaid'")
  })

  it('keeps global search indexes behind explicit search intent', () => {
    expect(appRoot).not.toContain('useGlobalSearch()')
    expect(appRoot).toContain('useGlobalSearchState()')
    expect(headerControls).not.toContain("import { useGlobalSearch } from '~/composables/useGlobalSearch'")
    expect(headerControls).toContain('~/composables/useGlobalSearchState')

    expect(globalSearchState).not.toContain('@talex-touch/utils/search')
    expect(globalSearchState).not.toContain('~/data/search/featureIndex')
    expect(globalSearchState).not.toContain('~/data/search/pageIndex')
    expect(globalSearchState).not.toContain('queryCollection')

    expect(globalSearch).not.toContain("from '@talex-touch/utils/search'")
    expect(globalSearch).not.toContain("import('@talex-touch/utils/search')")
    expect(globalSearch).not.toContain("from '~/data/search/featureIndex'")
    expect(globalSearch).not.toContain("from '~/data/search/pageIndex'")
    expect(globalSearch).toContain("import('@talex-touch/utils/search/feature-matcher')")
    expect(globalSearch).toContain("import('~/data/search/featureIndex')")
    expect(globalSearch).toContain("import('~/data/search/pageIndex')")
  })

  it('keeps the global toast host out of first-paint docs modules', () => {
    expect(constants).toContain("toastHostRequestedEvent = 'nexus:toast-host-requested'")
    expect(appRoot).not.toContain('<ToastContainer />')
    expect(appRoot).toContain("const LazyToastContainer = defineAsyncComponent(() => import('~/components/ToastContainer.vue'))")
    expect(appRoot).toContain('const toastHostMounted = ref(false)')
    expect(appRoot).toContain('function mountToastHost()')
    expect(appRoot).toMatch(/window\.addEventListener\(toastHostRequestedEvent, mountToastHost\)/)
    expect(appRoot).toMatch(/window\.removeEventListener\(toastHostRequestedEvent, mountToastHost\)/)
    expect(appRoot).toContain('<LazyToastContainer v-if="toastHostMounted"')
    expect(useToast).toContain("import { toastHostRequestedEvent } from '~/constants'")
    expect(useToast).toContain('function requestToastHost()')
    expect(useToast).toContain('window.dispatchEvent(new CustomEvent(toastHostRequestedEvent))')
    expect(useToast).toMatch(/toastItems\.value = \[\.\.\.toastItems\.value, toast\][\s\S]*requestToastHost\(\)[\s\S]*scheduleDismiss\(id, toast\.duration\)/)
  })

  it('lets Nuxt i18n lazy load locale messages instead of bundling both languages into first paint', () => {
    expect(i18nConfig).not.toContain('../i18n/locales/en')
    expect(i18nConfig).not.toContain('../i18n/locales/zh')
    expect(i18nConfig).not.toMatch(/\bmessages\s*:/)
    expect(nuxtConfig).toMatch(/i18n: \{[\s\S]*locales: \[[\s\S]*\{ code: 'en', file: 'en\.ts' \}[\s\S]*\{ code: 'zh', file: 'zh\.ts' \}[\s\S]*langDir: 'locales'[\s\S]*defaultLocale: 'en'/)
  })

  it('keeps the browser title reactive when a reused docs route changes', () => {
    expect(page).toMatch(/useHead\(\(\) => \(\{[\s\S]*title: docSeoHead\.value\.pageTitle[\s\S]*\}\)\)/)
  })

  it('preserves Vue Router history state when syncing the outline hash', () => {
    expect(docsOutline).not.toContain("history.replaceState(null, '', next)")
    expect(docsOutline).toMatch(/history\.replaceState\(history\.state, '', `\$\{window\.location\.pathname\}\$\{window\.location\.search\}\$\{next\}`\)/)
  })

  it('keeps docs outline scroll behavior off first-paint VueUse imports', () => {
    expect(docsOutline).not.toContain('@vueuse/core')
    expect(docsOutline).not.toContain('useEventListener')
    expect(docsOutline).not.toContain('useResizeObserver')
    expect(docsOutline).not.toContain('useThrottleFn')
    expect(docsOutline).toContain('function createThrottleFn')
    expect(docsOutline).toContain("window.addEventListener('scroll', onScroll, { passive: true })")
    expect(docsOutline).toContain('new ResizeObserver')
    expect(docsOutline).toContain("window.removeEventListener('scroll', onScroll)")
  })

  it('does not register VueUse as a global Nuxt module for docs first paint', () => {
    expect(nuxtConfig).not.toContain("'@vueuse/nuxt'")
    expect(packageJson).not.toContain('"@vueuse/nuxt"')
    expect(packageJson).toContain('"@vueuse/core"')
    expect(page).not.toContain('@vueuse/core')
    expect(page).not.toContain('useTimeAgoIntl')
    expect(page).toContain('function formatRelativeTimeFromNow(date: Date, locale: string)')
    expect(page).toContain('new Intl.RelativeTimeFormat(locale, { numeric: \'auto\' })')
    expect(pageView).toContain("import { useTimeAgo } from '@vueuse/core'")
    expect(vortexBackground).toContain("import { templateRef, useDebounceFn } from '@vueuse/core'")
  })

  it('keeps Vue devtools API bridge modules out of docs dev first paint by default', () => {
    expect(nuxtConfig).toContain('NUXT_DISABLE_VUE_DEVTOOLS_API_NOOP')
    expect(nuxtConfig).toMatch(/const useVueDevtoolsApiNoop = isDev && process\.env\.NUXT_DISABLE_VUE_DEVTOOLS_API_NOOP !== 'true'/)
    expect(nuxtConfig).toContain("const vueDevtoolsApiNoopEntry = resolve(currentDir, 'app/utils/vue-devtools-api-noop.ts')")
    expect(nuxtConfig).toMatch(/\.\.\.\(useVueDevtoolsApiNoop \? \[\{ find: \/\^@vue\\\/devtools-api\$\/, replacement: vueDevtoolsApiNoopEntry \}\] : \[\]\)/)

    expect(vueDevtoolsApiNoop).toContain('export function setupDevToolsPlugin()')
    expect(vueDevtoolsApiNoop).toContain('export const setupDevtoolsPlugin = setupDevToolsPlugin')
    expect(vueDevtoolsApiNoop).toContain('export function addCustomCommand()')
    expect(vueDevtoolsApiNoop).toContain('export function addCustomTab()')
    expect(vueDevtoolsApiNoop).not.toContain('@vue/devtools-kit')
  })

  it('keeps the PWA client plugin out of normal docs dev first paint', () => {
    expect(nuxtConfig).toContain("const enablePwaModule = isProd || process.env.VITE_PLUGIN_PWA === 'true'")
    expect(nuxtConfig).toMatch(/\.\.\.\(enablePwaModule \? \['@vite-pwa\/nuxt'\] : \[\]\)/)
    expect(nuxtConfig).not.toMatch(/^[\s]*'@vite-pwa\/nuxt',/m)
    expect(packageJson).toContain('"dev:pwa": "VITE_PLUGIN_PWA=true nuxt dev"')
    expect(appRoot).toContain("import NexusPwaManifest from '~/components/NexusPwaManifest.vue'")
    expect(appRoot).toContain('<NexusPwaManifest />')
    expect(appRoot).not.toContain('<VitePwaManifest />')
    expect(nexusPwaManifest).toContain("const shouldRenderPwaManifest = import.meta.env.PROD || import.meta.env.VITE_PLUGIN_PWA === 'true'")
    expect(nexusPwaManifest).toContain("resolveComponent('VitePwaManifest')")
    expect(nexusPwaManifest).not.toContain("from '@vite-pwa/nuxt")
  })

  it('requests component sidebar metadata by locale instead of downloading both languages', () => {
    expect(docsSidebar).toContain("'/api/docs/sidebar-components'")
    expect(docsSidebar).toMatch(/key: computed\(\(\) => `docs-components-meta:\$\{docsLocale\.value\}`\)/)
    expect(docsSidebar).toMatch(/query: computed\(\(\) => \(\{[\s\S]*locale: docsLocale\.value,[\s\S]*\}\)\)/)
    expect(docsSidebar).toContain('immediate: false')
    expect(docsSidebar).toContain('COMPONENT_DOCS_METADATA_DELAY_MS = 360')
    expect(docsSidebar).toContain('COMPONENT_DOCS_METADATA_INTENT_DELAY_MS = 180')
    expect(docsSidebar).toContain('function requestComponentDocsMetadata()')
    expect(docsSidebar).toContain('function requestComponentDocsMetadataOnIntent()')
    expect(docsSidebar).toContain('function scheduleComponentDocsMetadata()')
    expect(docsSidebar).toMatch(/componentDocsMetadataTimer = setTimeout\(\(\) => \{[\s\S]*requestComponentDocsMetadata\(\)[\s\S]*COMPONENT_DOCS_METADATA_INTENT_DELAY_MS/)
    expect(docsSidebar).toContain('@pointerenter="requestComponentDocsMetadataOnIntent"')
    expect(docsSidebar).toContain('@focusin="requestComponentDocsMetadataOnIntent"')
    expect(docsSidebar).toContain('@touchstart.passive="requestComponentDocsMetadataOnIntent"')
    expect(docsSidebar).toContain('const componentItems = computed(() => coerceJsonArray<SidebarComponentDoc>(componentDocsPayload.value) as any[])')
  })

  it('requests scoped docs navigation for component pages instead of hydrating the full docs tree', () => {
    expect(page).toContain("'/api/docs/navigation'")
    expect(docsSidebar).toContain("'/api/docs/navigation'")
    expect(page).toContain("const docsNavigationScope = computed(() => (shouldSplitDocBody.value ? 'components' : undefined))")
    expect(docsSidebar).toContain("const docsNavigationScope = computed(() => (isComponentDocsRoute.value ? 'components' : undefined))")
    expect(page).toMatch(/key: computed\(\(\) => `docs-navigation:\$\{docsLocale\.value\}:\$\{docsNavigationScope\.value \?\? 'all'\}`\)/)
    expect(docsSidebar).toMatch(/key: computed\(\(\) => `docs-navigation:\$\{docsLocale\.value\}:\$\{docsNavigationScope\.value \?\? 'all'\}`\)/)
    expect(page).toMatch(/query: computed\(\(\) => \(\{[\s\S]*locale: docsLocale\.value,[\s\S]*\}\)/)
    expect(docsSidebar).toMatch(/query: computed\(\(\) => \(\{[\s\S]*locale: docsLocale\.value,[\s\S]*\}\)/)
    expect(page).toContain("...(docsNavigationScope.value ? { scope: docsNavigationScope.value } : {})")
    expect(docsSidebar).toContain("...(docsNavigationScope.value ? { scope: docsNavigationScope.value } : {})")
  })

  it('warms component docs links on sidebar intent without enabling bulk NuxtLink prefetch', () => {
    expect(docsSidebar).toContain("import { requestDocsPage } from '~/utils/docs-page-client-cache'")
    expect(docsSidebar).toContain("import { useTypedFetch } from '~/utils/request'")
    expect(docsSidebar).toContain('COMPONENT_DOCS_FULL_BODY_PREFETCH_DELAY_MS = 900')
    expect(docsSidebar).toContain('COMPONENT_DOCS_FULL_BODY_PREFETCH_IDLE_TIMEOUT_MS = 2400')
    expect(docsSidebar).toContain('const prefetchedDocsMetadataTargets = new Set<string>()')
    expect(docsSidebar).toContain('const prefetchedDocsFullBodyTargets = new Set<string>()')
    expect(docsSidebar).toContain('const pendingDocsFullBodyPrefetchTimers = new Map<string, ReturnType<typeof setTimeout>>()')
    expect(docsSidebar).toContain('const pendingDocsFullBodyPrefetchIdleIds = new Map<string, number>()')
    expect(docsSidebar).toMatch(/function shouldPrefetchDocsTarget\(path: string \| null \| undefined\) \{[\s\S]*normalized\?\.startsWith\('\/docs\/dev\/components\/'\)/)
    expect(docsSidebar).toMatch(/function prefetchDocsMetadataTarget\(normalized: string, locale: 'en' \| 'zh'\) \{[\s\S]*prefetchedDocsMetadataTargets\.has\(cacheKey\)[\s\S]*prefetchedDocsMetadataTargets\.add\(cacheKey\)[\s\S]*void preloadRouteComponents\(routeTarget\)[\s\S]*requestDocsPage\(\{ path: normalized, locale, body: '0' \}\)/)
    expect(docsSidebar).toMatch(/function scheduleDocsFullBodyPrefetch\(normalized: string, locale: 'en' \| 'zh'\) \{[\s\S]*pendingDocsFullBodyPrefetchTimers\.has\(cacheKey\)[\s\S]*const timer = setTimeout\(\(\) => \{[\s\S]*window\.requestIdleCallback\(prefetchFullDoc, \{ timeout: COMPONENT_DOCS_FULL_BODY_PREFETCH_IDLE_TIMEOUT_MS \}\)[\s\S]*COMPONENT_DOCS_FULL_BODY_PREFETCH_DELAY_MS/)
    expect(docsSidebar).toMatch(/function prefetchDocsTarget\(path: string \| null \| undefined\) \{[\s\S]*if \(import\.meta\.server \|\| !shouldPrefetchDocsTarget\(path\)\)[\s\S]*return/)
    expect(docsSidebar).toMatch(/prefetchDocsMetadataTarget\(normalized, locale\)[\s\S]*scheduleDocsFullBodyPrefetch\(normalized, locale\)/)
    expect(docsSidebar).toMatch(/function cancelDocsFullBodyPrefetch\(path: string \| null \| undefined\) \{[\s\S]*clearTimeout\(timer\)[\s\S]*window\.cancelIdleCallback\(idleId\)/)
    expect(docsSidebar).toContain('@mouseenter="prefetchDocsTarget(linkTarget(child))"')
    expect(docsSidebar).toContain('@mouseleave="cancelDocsFullBodyPrefetch(linkTarget(child))"')
    expect(docsSidebar).toContain('@focus="prefetchDocsTarget(linkTarget(child))"')
    expect(docsSidebar).toContain('@blur="cancelDocsFullBodyPrefetch(linkTarget(child))"')
    expect(docsSidebar).toContain('@touchstart.passive="prefetchDocsTarget(linkTarget(child))"')
    expect(docsSidebar).toContain(':prefetch="false"')
  })

  it('keeps decorative footer aurora from throwing when WebGL2 is unavailable', () => {
    expect(touchAurora).toContain('let auroraDisabled = false')
    expect(touchAurora).toContain("const gl = canvas.getContext('webgl2')")
    expect(touchAurora).toContain('function hasAuroraWebglSupport()')
    expect(touchAurora).toMatch(/if \(!hasAuroraWebglSupport\(\)\) \{[\s\S]*auroraDisabled = true[\s\S]*return[\s\S]*\}/)
    expect(touchAurora).toMatch(/try \{[\s\S]*renderer = new Renderer[\s\S]*\}[\s\S]*catch \{[\s\S]*auroraDisabled = true[\s\S]*renderer = null[\s\S]*return[\s\S]*\}/)
  })

  it('keeps migrated avatar variants demos self-contained for client rendering', () => {
    expect(avatarVariantsDemo).toContain("import AvatarVariantCard from './AvatarVariantCard.vue'")
    expect(avatarVariantsDemo).toContain('<AvatarVariantCard')
  })

  it('caches split full-body docs on the client without deep AST reactivity', () => {
    expect(page).toContain("import { primeDocsPageRequestCache, requestDocsPage } from '~/utils/docs-page-client-cache'")
    expect(page).toContain("import { useTypedFetch } from '~/utils/request'")
    expect(page).toContain('DOCS_FULL_BODY_CACHE_LIMIT = 24')
    expect(page).toContain('DOCS_FULL_BODY_IDLE_DELAY_MS = 180')
    expect(page).toContain('DOCS_FULL_BODY_IDLE_TIMEOUT_MS = 1200')
    expect(page).toContain('DOCS_PAGER_FULL_BODY_PREFETCH_DELAY_MS = 900')
    expect(page).toContain('DOCS_PAGER_FULL_BODY_PREFETCH_IDLE_TIMEOUT_MS = 2400')
    expect(page).toContain("DOCS_CURRENT_PAGE_FETCH_KEY = 'docs-current-page'")
    expect(page).not.toContain('DOCS_CURRENT_FULL_BODY_FETCH_KEY')
    expect(page).toContain('const docsFullBodyCache = new Map<string, Record<string, any> | null>()')
    expect(page).toContain('const shouldRequestMetadataOnlyDocBody = computed(() => shouldSplitDocBody.value && (import.meta.client || import.meta.dev))')
    expect(page).toContain('function resolveFullDocCacheKey(value: Record<string, any> | null)')
    expect(page).toContain("const localeMatch = rawPath.match(/\\.(en|zh)$/)")
    expect(page).toContain('function readCachedFullDoc(key: string)')
    expect(page).toContain('function hasCachedFullDoc(key: string)')
    expect(page).toContain('function cacheFullDoc(value: Record<string, any> | null)')
    expect(page).toMatch(/return `doc-full:\$\{normalizedPath\}:\$\{locale\}`/)
    expect(page).toContain('while (docsFullBodyCache.size > DOCS_FULL_BODY_CACHE_LIMIT)')
    expect(page).toMatch(/const fullDocCacheKey = computed\(\(\) => `doc-full:\$\{docPath\.value\}:\$\{docsLocale\.value\}`\)/)
    expect(page).toContain('const fullDoc = shallowRef<Record<string, any> | null>(null)')
    expect(page).toContain('const fullDocLoading = ref(false)')
    expect(page).toContain('key: DOCS_CURRENT_PAGE_FETCH_KEY')
    expect(page).toMatch(/key: DOCS_CURRENT_PAGE_FETCH_KEY,[\s\S]*immediate: import\.meta\.server \|\| !shouldSplitDocBody\.value,[\s\S]*watch: false/)
    expect(page).toMatch(/body: shouldRequestMetadataOnlyDocBody\.value \? '0' : '1'/)
    expect(page).toMatch(/const renderDoc = computed\(\(\) => \(shouldSplitDocBody\.value \? fullDoc\.value \?\? doc\.value : doc\.value\)\)/)
    expect(page).toContain('let activeDocFetchId = 0')
    expect(page).toContain('let fullDocIdleId: number | null = null')
    expect(page).toContain('let fullDocTimer: ReturnType<typeof setTimeout> | null = null')
    expect(page).toContain('function clearFullDocFetchSchedule()')
    expect(page).toMatch(/if \(fullDocIdleId !== null && 'cancelIdleCallback' in window\) \{[\s\S]*window\.cancelIdleCallback\(fullDocIdleId\)[\s\S]*fullDocIdleId = null/)
    expect(page).toMatch(/if \(fullDocTimer\) \{[\s\S]*clearTimeout\(fullDocTimer\)[\s\S]*fullDocTimer = null/)
    expect(page).toContain('async function loadFullDocForRoute(fetchId: number, path: string, locale: \'en\' | \'zh\')')
    expect(page).toMatch(/const cacheKey = `doc-full:\$\{path\}:\$\{locale\}`[\s\S]*if \(hasCachedFullDoc\(cacheKey\)\) \{[\s\S]*fullDoc\.value = readCachedFullDoc\(cacheKey\) \?\? null/)
    expect(page).toMatch(/fullDocLoading\.value = true[\s\S]*requestDocsPage\(\{ path, locale, body: '1' \}\)/)
    expect(page).toMatch(/const cachedFullDoc = cacheFullDoc\(nextFullDoc\)[\s\S]*fullDoc\.value = cachedFullDoc[\s\S]*if \(!doc\.value\) \{[\s\S]*doc\.value = cachedFullDoc[\s\S]*isLoading\.value = false[\s\S]*\}/)
    expect(page).toContain('function seedFullDocFromCurrentDoc()')
    expect(page).toMatch(/function seedFullDocFromCurrentDoc\(\) \{[\s\S]*if \(!shouldSplitDocBody\.value \|\| !doc\.value\?\.body\)[\s\S]*return false[\s\S]*fullDoc\.value = cacheFullDoc\(doc\.value as Record<string, any>\)[\s\S]*return true[\s\S]*\}/)
    expect(page).toContain('function scheduleFullDocFetchForRoute(fetchId: number, path: string, locale: \'en\' | \'zh\')')
    expect(page).toMatch(/function scheduleFullDocFetchForRoute\(fetchId: number, path: string, locale: 'en' \| 'zh'\) \{[\s\S]*clearFullDocFetchSchedule\(\)[\s\S]*const load = \(\) => \{[\s\S]*if \(fetchId !== activeDocFetchId \|\| path !== docPath\.value \|\| locale !== docsLocale\.value\)[\s\S]*return[\s\S]*void loadFullDocForRoute\(fetchId, path, locale\)/)
    expect(page).toMatch(/fullDocTimer = setTimeout\(\(\) => \{[\s\S]*window\.requestIdleCallback\(load, \{ timeout: DOCS_FULL_BODY_IDLE_TIMEOUT_MS \}\)[\s\S]*load\(\)[\s\S]*DOCS_FULL_BODY_IDLE_DELAY_MS/)
    expect(page).toContain('function startFullDocFetchForRoute()')
    expect(page).toMatch(/function startFullDocFetchForRoute\(\) \{[\s\S]*if \(seedFullDocFromCurrentDoc\(\)\)[\s\S]*return[\s\S]*const fetchId = \+\+activeDocFetchId[\s\S]*scheduleFullDocFetchForRoute\(fetchId, docPath\.value, docsLocale\.value\)[\s\S]*\}/)
    expect(page).toContain('async function loadActiveDocForRoute()')
    expect(page).toMatch(/const fetchId = \+\+activeDocFetchId[\s\S]*const path = docPath\.value[\s\S]*const locale = docsLocale\.value/)
    expect(page).toContain('const hasCachedBody = splitBody && cachedFullDoc !== undefined')
    expect(page).toMatch(/clearFullDocFetchSchedule\(\)[\s\S]*doc\.value = hasCachedBody \? cachedFullDoc : null[\s\S]*fullDoc\.value = hasCachedBody \? cachedFullDoc : null[\s\S]*isLoading\.value = !hasCachedBody[\s\S]*fullDocLoading\.value = false/)
    expect(page).toMatch(/try \{[\s\S]*requestDocsPage\(\{ path, locale, body: splitBody \? '0' : '1' \}\)/)
    expect(page).toMatch(/if \(fetchId !== activeDocFetchId \|\| path !== docPath\.value \|\| locale !== docsLocale\.value\)[\s\S]*return/)
    expect(page).toMatch(/fullDoc\.value = cachedFullDoc/)
    expect(page).not.toContain('const fullDocRequest = splitBody && !hasCachedBody')
    expect(page).not.toContain('void fullDocRequest')
    expect(page).toMatch(/if \(hasCachedBody\)[\s\S]*return[\s\S]*scheduleFullDocFetchForRoute\(fetchId, path, locale\)/)
    expect(page).toMatch(/catch \{[\s\S]*fullDocLoading\.value = false[\s\S]*clearFullDocFetchSchedule\(\)/)
    expect(page).toMatch(/if \(import\.meta\.client\)[\s\S]*startFullDocFetchForRoute\(\)/)
    expect(page).toMatch(/watch\(requestKey, \(\) => \{[\s\S]*void loadActiveDocForRoute\(\)[\s\S]*\}\)/)
    expect(page).toMatch(/onMounted\(\(\) => \{[\s\S]*startFullDocFetchForRoute\(\)[\s\S]*\}\)/)
    expect(page).toMatch(/onBeforeUnmount\(\(\) => \{[\s\S]*clearFullDocFetchSchedule\(\)/)
    expect(page).toMatch(/return `\$\{path\}:\$\{docsLocale\.value\}:\$\{source\?\.body \? 'body' : 'meta'\}`/)
    expect(page).not.toContain('shouldClientRenderDocBody')
    expect(page).not.toContain('<ClientOnly v-if="shouldClientRenderDocBody">')
    expect(page).toMatch(/<ContentRenderer[\s\S]*v-if="renderDoc\?\.body"[\s\S]*:value="renderDoc \?\? \{\}"/)
    expect(page).toContain(':prose="false"')
    expect(page).toContain(':components="docsProseComponents"')
    expect(page).toContain("import DocsProseHeading from '~/components/docs/DocsProseHeading.vue'")
    expect(page).toContain("function createDocsProseHeading(tag: 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6')")
    expect(page).toContain("h1: createDocsProseHeading('h1')")
    expect(page).toContain("h6: createDocsProseHeading('h6')")
    expect(docsProseHeading).toContain('<component :is="props.tag"')
    expect(docsProseHeading).toContain(':href="`#${props.id')
    expect(page).not.toContain('proseComponentMap')
  })

  it('keeps default MDC prose wrappers out of content renderer routes', () => {
    expect(nuxtConfig).toContain("'/@nuxtjs/mdc/dist/runtime/components/prose/'")
    expect(nuxtConfig).toContain("'/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/'")

    for (const contentPage of [page, licensePage, privacyPage, protocolPage]) {
      expect(contentPage).toContain('<ContentRenderer')
      expect(contentPage).toContain(':prose="false"')
    }
  })

  it('keeps dev fallback metadata requests off full Markdown body parsing', () => {
    expect(docsPageApi).toContain('function parseFrontmatterMetadata(raw: string)')
    expect(docsPageApi).toContain('async function readDevDocsPageFromFile(contentPath: string, includeBody: boolean)')
    expect(docsPageApi).toContain('function shouldPreferDevDocsMetadataFileLookup(docPath: string, includeBody: boolean)')
    expect(docsPageApi).toMatch(/function shouldPreferDevDocsMetadataFileLookup\(docPath: string, includeBody: boolean\) \{[\s\S]*return process\.env\.NODE_ENV === 'development' && !includeBody && docPath\.includes\('\/docs\/dev\/components'\)[\s\S]*\}/)
    expect(docsPageApi).toMatch(/if \(shouldPreferDevDocsMetadataFileLookup\(docPath, includeBody\)\) \{[\s\S]*readDevDocsPageFallback\(lookupPaths, includeBody\)[\s\S]*return serializeDoc\(fallbackDoc, includeBody\)[\s\S]*\}/)
    expect(docsPageApi).toMatch(/if \(!includeBody\) \{[\s\S]*parseFrontmatterMetadata\(raw\)[\s\S]*metaDoc = doc[\s\S]*return doc[\s\S]*\}/)
    expect(docsPageApi).toMatch(/const \{ parseMarkdown \} = await import\('@nuxtjs\/mdc\/runtime'\)/)
    expect(docsPageApi).not.toContain("import('@nuxtjs/mdc/runtime'),")
    expect(docsPageApi).toContain('fullDoc?: DocsPageRecord')
    expect(docsPageApi).toContain('metaDoc?: DocsPageRecord')
  })

  it('warms pager docs targets with cancelable full-body prefetch on sustained user intent', () => {
    expect(page).toContain('const prefetchedDocMetadataTargets = new Set<string>()')
    expect(page).toContain('const prefetchedDocFullBodyTargets = new Set<string>()')
    expect(page).toContain('const pendingPagerFullBodyPrefetchTimers = new Map<string, ReturnType<typeof setTimeout>>()')
    expect(page).toContain('const pendingPagerFullBodyPrefetchIdleIds = new Map<string, number>()')
    expect(page).toContain('function prefetchDocMetadataForTarget(normalized: string, locale: \'en\' | \'zh\')')
    expect(page).toMatch(/function prefetchDocMetadataForTarget\(normalized: string, locale: 'en' \| 'zh'\) \{[\s\S]*prefetchedDocMetadataTargets\.has\(prefetchKey\)[\s\S]*prefetchedDocMetadataTargets\.add\(prefetchKey\)[\s\S]*void preloadRouteComponents\(toLocalizedDocsPath\(normalized, locale\)\)[\s\S]*requestDocsPage\(\{ path: normalized, locale, body: '0' \}\)/)
    expect(page).toContain('function clearPagerFullBodyPrefetchSchedule(prefetchKey: string)')
    expect(page).toMatch(/function clearPagerFullBodyPrefetchSchedule\(prefetchKey: string\) \{[\s\S]*clearTimeout\(timer\)[\s\S]*window\.cancelIdleCallback\(idleId\)/)
    expect(page).toContain('function clearPagerFullBodyPrefetchSchedules()')
    expect(page).toContain('function schedulePagerFullDocPrefetch(normalized: string, locale: \'en\' | \'zh\')')
    expect(page).toMatch(/function schedulePagerFullDocPrefetch\(normalized: string, locale: 'en' \| 'zh'\) \{[\s\S]*hasCachedFullDoc\(cacheKey\)[\s\S]*pendingPagerFullBodyPrefetchTimers\.has\(prefetchKey\)[\s\S]*const timer = setTimeout\(\(\) => \{[\s\S]*window\.requestIdleCallback\(prefetchFullDoc, \{ timeout: DOCS_PAGER_FULL_BODY_PREFETCH_IDLE_TIMEOUT_MS \}\)[\s\S]*DOCS_PAGER_FULL_BODY_PREFETCH_DELAY_MS/)
    expect(page).toContain('function prefetchDocForPath(path: string | null | undefined)')
    expect(page).toMatch(/prefetchDocMetadataForTarget\(normalized, locale\)[\s\S]*schedulePagerFullDocPrefetch\(normalized, locale\)/)
    expect(page).toContain('function cancelPrefetchDocForPath(path: string | null | undefined)')
    expect(page).toMatch(/function cancelPrefetchDocForPath\(path: string \| null \| undefined\) \{[\s\S]*clearPagerFullBodyPrefetchSchedule\(`\$\{normalized\}:\$\{docsLocale\.value\}`\)/)
    expect(page).toMatch(/watch\(requestKey, \(\) => \{[\s\S]*clearPagerFullBodyPrefetchSchedules\(\)/)
    expect(page).toMatch(/onBeforeUnmount\(\(\) => \{[\s\S]*clearPagerFullBodyPrefetchSchedules\(\)/)
    expect(page).toContain('@mouseenter="prefetchDocForPath(pagerPrevPath)"')
    expect(page).toContain('@mouseleave="cancelPrefetchDocForPath(pagerPrevPath)"')
    expect(page).toContain('@focus="prefetchDocForPath(pagerPrevPath)"')
    expect(page).toContain('@blur="cancelPrefetchDocForPath(pagerPrevPath)"')
    expect(page).toContain('@touchstart.passive="prefetchDocForPath(pagerPrevPath)"')
    expect(page).toContain('@mouseenter="prefetchDocForPath(pagerNextPath)"')
    expect(page).toContain('@mouseleave="cancelPrefetchDocForPath(pagerNextPath)"')
    expect(page).toContain('@focus="prefetchDocForPath(pagerNextPath)"')
    expect(page).toContain('@blur="cancelPrefetchDocForPath(pagerNextPath)"')
    expect(page).toContain('@touchstart.passive="prefetchDocForPath(pagerNextPath)"')
  })

  it('dedupes docs page client requests shared by sidebar prefetch and route loads', () => {
    expect(docsPageClientCache).toContain('const docsPageRequestPending = new Map<string, Promise<DocsPageRecord>>()')
    expect(docsPageClientCache).toContain('const docsPageRequestCache = new Map<string, DocsPageRequestCacheEntry>()')
    expect(docsPageClientCache).toContain('DOCS_PAGE_REQUEST_CACHE_TTL_MS = 30_000')
    expect(docsPageClientCache).toContain('export function resolveDocsPageRequestCacheKey')
    expect(docsPageClientCache).toContain('export function primeDocsPageRequestCache')
    expect(docsPageClientCache).toContain('export function requestDocsPage')
    expect(docsPageClientCache).toMatch(/const pending = docsPageRequestPending\.get\(cacheKey\)[\s\S]*if \(pending\)[\s\S]*return pending/)
    expect(docsPageClientCache).toMatch(/requestJson<DocsPageRecord>\('\/api\/docs\/page'[\s\S]*path,[\s\S]*locale,[\s\S]*body/)
    expect(docsPageClientCache).toMatch(/docsPageRequestPending\.set\(cacheKey, request\)/)
    expect(page).toContain('primeDocsPageRequestCache({')
    expect(page).toContain("requestDocsPage({ path, locale, body: '1' })")
    expect(docsSidebar).toContain("requestDocsPage({ path: normalized, locale, body: '1' })")
    expect(docsSidebar).toMatch(/const prefetchFullDoc = \(\) => \{[\s\S]*void requestDocsPage\(\{ path: normalized, locale, body: '1' \}\)/)
    expect(docsSidebar).not.toMatch(/void requestDocsPage\(\{ path: normalized, locale, body: '0' \}\)\.catch\(\(\) => \{\}\)\n\s*void requestDocsPage\(\{ path: normalized, locale, body: '1' \}\)/)
  })
})
