import { readFileSync } from 'node:fs'
import { describe, expect, it } from 'vitest'

const page = readFileSync(new URL('./[...slug].vue', import.meta.url), 'utf8')
const docsOutline = readFileSync(new URL('../../components/DocsOutline.vue', import.meta.url), 'utf8')
const docsSidebar = readFileSync(new URL('../../components/DocsSidebar.vue', import.meta.url), 'utf8')
const docSection = readFileSync(new URL('../../components/docs/DocSection.vue', import.meta.url), 'utf8')
const docsAsideCards = readFileSync(new URL('../../components/docs/DocsAsideCards.vue', import.meta.url), 'utf8')
const docsAsideCardsShell = readFileSync(new URL('../../components/docs/DocsAsideCardsShell.vue', import.meta.url), 'utf8')
const touchAurora = readFileSync(new URL('../../components/tuff/background/TouchAurora.vue', import.meta.url), 'utf8')
const avatarVariantsDemo = readFileSync(new URL('../../components/content/demos/AvatarVariantsAvatarVariantsGalleryDemo.vue', import.meta.url), 'utf8')
const docsPageClientCache = readFileSync(new URL('../../utils/docs-page-client-cache.ts', import.meta.url), 'utf8')
const docsLayout = readFileSync(new URL('../../layouts/docs.vue', import.meta.url), 'utf8')
const theHeader = readFileSync(new URL('../../components/TheHeader.vue', import.meta.url), 'utf8')
const tuffFooter = readFileSync(new URL('../../components/TuffFooter.vue', import.meta.url), 'utf8')
const docHero = readFileSync(new URL('../../components/docs/DocHero.vue', import.meta.url), 'utf8')
const docsProseHeading = readFileSync(new URL('../../components/docs/DocsProseHeading.vue', import.meta.url), 'utf8')
const vortexBackground = readFileSync(new URL('../../components/tuff/VortexBackground.vue', import.meta.url), 'utf8')
const headerControls = readFileSync(new URL('../../components/HeaderControls.vue', import.meta.url), 'utf8')
const globalSearchState = readFileSync(new URL('../../composables/useGlobalSearchState.ts', import.meta.url), 'utf8')
const globalSearch = readFileSync(new URL('../../composables/useGlobalSearch.ts', import.meta.url), 'utf8')
const policyMarkdown = readFileSync(new URL('../../composables/usePolicyMarkdown.ts', import.meta.url), 'utf8')
const legacySearch = readFileSync(new URL('../../components/Search.vue', import.meta.url), 'utf8')
const docEngagementTracker = readFileSync(new URL('../../composables/useDocEngagementTracker.ts', import.meta.url), 'utf8')
const languageToggle = readFileSync(new URL('../../components/LanguageToggle.vue', import.meta.url), 'utf8')
const languageToggleMenu = readFileSync(new URL('../../components/LanguageToggleMenu.vue', import.meta.url), 'utf8')
const darkToggle = readFileSync(new URL('../../components/DarkToggle.vue', import.meta.url), 'utf8')
const iconComposer = readFileSync(new URL('../../components/icon/IconComposer.vue', import.meta.url), 'utf8')
const backToTop = readFileSync(new URL('../../components/ui/BackToTop.vue', import.meta.url), 'utf8')
const appRoot = readFileSync(new URL('../../app.vue', import.meta.url), 'utf8')
const nexusPwaManifest = readFileSync(new URL('../../components/NexusPwaManifest.vue', import.meta.url), 'utf8')
const pageView = readFileSync(new URL('../../components/PageView.vue', import.meta.url), 'utf8')
const dashboardPage = readFileSync(new URL('../dashboard.vue', import.meta.url), 'utf8')
const dashboardOverviewPage = readFileSync(new URL('../dashboard/overview.vue', import.meta.url), 'utf8')
const providerRegistryPage = readFileSync(new URL('../dashboard/admin/provider-registry.vue', import.meta.url), 'utf8')
const governancePage = readFileSync(new URL('../dashboard/admin/governance.vue', import.meta.url), 'utf8')
const storePage = readFileSync(new URL('../store.vue', import.meta.url), 'utf8')
const storeLayout = readFileSync(new URL('../../layouts/store.vue', import.meta.url), 'utf8')
const landingPage = readFileSync(new URL('../index.vue', import.meta.url), 'utf8')
const newLandingPage = readFileSync(new URL('../new/index.vue', import.meta.url), 'utf8')
const teamJoinPage = readFileSync(new URL('../team/join.vue', import.meta.url), 'utf8')
const signInPage = readFileSync(new URL('../sign-in/index.vue', import.meta.url), 'utf8')
const signInCallbackPage = readFileSync(new URL('../sign-in/[...slug].vue', import.meta.url), 'utf8')
const appCallbackPage = readFileSync(new URL('../auth/app-callback.vue', import.meta.url), 'utf8')
const adminBootstrapPage = readFileSync(new URL('../auth/admin-bootstrap.vue', import.meta.url), 'utf8')
const constants = readFileSync(new URL('../../constants/index.ts', import.meta.url), 'utf8')
const toastHost = readFileSync(new URL('../../components/ui/ToastHost.vue', import.meta.url), 'utf8')
const useToast = readFileSync(new URL('../../composables/useToast.ts', import.meta.url), 'utf8')
const tuffDemoWrapper = readFileSync(new URL('../../components/content/TuffDemoWrapper.vue', import.meta.url), 'utf8')
const tuffCodeBlock = readFileSync(new URL('../../components/content/TuffCodeBlock.vue', import.meta.url), 'utf8')
const tuffCodeBlockRenderer = readFileSync(new URL('../../components/content/TuffCodeBlockRenderer.vue', import.meta.url), 'utf8')
const tuffPropsTable = readFileSync(new URL('../../components/content/TuffPropsTable.vue', import.meta.url), 'utf8')
const mermaidRenderer = readFileSync(new URL('../../utils/mermaid-renderer.ts', import.meta.url), 'utf8')
const i18nConfig = readFileSync(new URL('../../i18n.config.ts', import.meta.url), 'utf8')
const i18nEn = readFileSync(new URL('../../../i18n/locales/en.ts', import.meta.url), 'utf8')
const i18nZh = readFileSync(new URL('../../../i18n/locales/zh.ts', import.meta.url), 'utf8')
const routeLocaleChunks = readFileSync(new URL('../../utils/route-locale-chunks.ts', import.meta.url), 'utf8')
const routeLocaleMiddleware = readFileSync(new URL('../../middleware/i18n-route-chunks.global.ts', import.meta.url), 'utf8')
const routeLocaleComposable = readFileSync(new URL('../../composables/useRouteLocaleChunks.ts', import.meta.url), 'utf8')
const localeOrchestrator = readFileSync(new URL('../../composables/useLocaleOrchestrator.ts', import.meta.url), 'utf8')
const nexusAuth = readFileSync(new URL('../../composables/useNexusAuth.ts', import.meta.url), 'utf8')
const authApi = readFileSync(new URL('../../../server/api/auth/[...].ts', import.meta.url), 'utf8')
const vueDevtoolsApiNoop = readFileSync(new URL('../../utils/vue-devtools-api-noop.ts', import.meta.url), 'utf8')
const docsPageApi = readFileSync(new URL('../../../server/api/docs/page.get.ts', import.meta.url), 'utf8')
const nuxtConfig = readFileSync(new URL('../../../nuxt.config.ts', import.meta.url), 'utf8')
const packageJson = readFileSync(new URL('../../../package.json', import.meta.url), 'utf8')
const licensePage = readFileSync(new URL('../license.vue', import.meta.url), 'utf8')
const privacyPage = readFileSync(new URL('../privacy.vue', import.meta.url), 'utf8')
const protocolPage = readFileSync(new URL('../protocol.vue', import.meta.url), 'utf8')

describe('docs page performance boundaries', () => {
  it('keys catch-all docs pages by route path to avoid stale content on client navigation', () => {
    expect.soft(page).toMatch(/definePageMeta\(\{[\s\S]*key: route => route\.path[\s\S]*\}\)/)
    expect.soft(page).toContain('const router = useRouter()')
    expect.soft(page).toContain('const activeRoutePath = ref(route.path)')
    expect.soft(page).toMatch(/activeRoutePath\.value = router\.currentRoute\.value\.path \|\| route\.path[\s\S]*const removeRouteSync = router\.afterEach\(\(to\) => \{[\s\S]*activeRoutePath\.value = to\.path[\s\S]*onBeforeUnmount\(removeRouteSync\)/)
    expect.soft(page).toContain('const docsLocale = computed(() => resolveDocsLocaleFromRoute(activeRoutePath.value))')
    expect.soft(page).toContain('const docPath = computed(() => normalizeDocsPagePath(activeRoutePath.value))')
    expect.soft(page).toContain('function shouldSplitDocsPageBody(path: string)')
    expect.soft(page).toContain("return normalized.startsWith('/docs/') && normalized !== '/docs/index'")
    expect.soft(page).toContain('const shouldSplitDocBody = computed(() => shouldSplitDocsPageBody(activeRoutePath.value))')
  })

  it('keeps bottom engagement panels behind near-viewport activation', () => {
    expect.soft(page).toContain('shouldMountDocEngagementPanels')
    expect.soft(page).toContain('docEngagementAnchorRef')
    expect.soft(page).toContain('IntersectionObserver')
    expect.soft(page).toContain('requestIdleCallback')
    expect.soft(page).toContain('DOC_ENGAGEMENT_PANEL_DELAY_MS = 3200')
    expect.soft(page).toContain('DOC_ENGAGEMENT_PANEL_IDLE_TIMEOUT_MS = 5000')
    expect.soft(page).toMatch(/setTimeout\(\(\) => \{[\s\S]*IntersectionObserver[\s\S]*DOC_ENGAGEMENT_PANEL_DELAY_MS/)
    expect.soft(page).toMatch(/engagementPanelObserver\.observe\(anchor\)[\s\S]*return[\s\S]*requestIdleCallback/)
    expect.soft(page).toContain('<LazyDocsFeedback v-if="shouldMountDocEngagementPanels"')
    expect.soft(page).toContain('<LazyDocsComments v-if="shouldMountDocEngagementPanels"')
  })

  it('keeps footer aurora behind near-viewport activation', () => {
    expect.soft(tuffFooter).toContain("const LazyTouchAurora = defineAsyncComponent(() => import('./tuff/background/TouchAurora.vue'))")
    expect.soft(tuffFooter).toContain("FOOTER_AURORA_ROOT_MARGIN = '480px 0px'")
    expect.soft(tuffFooter).toContain('const footerRef = ref<HTMLElement | null>(null)')
    expect.soft(tuffFooter).toMatch(/new IntersectionObserver\([\s\S]*FOOTER_AURORA_ROOT_MARGIN[\s\S]*auroraObserver\.observe\(footer\)[\s\S]*return[\s\S]*scheduleAuroraFallback\(\)/)
    expect.soft(tuffFooter).toContain('<footer ref="footerRef"')
    expect.soft(tuffFooter).toContain('<LazyTouchAurora')
    expect.soft(tuffFooter).toContain('v-if="shouldMountAurora"')
  })

  it('keeps docs hero decoration static instead of mounting a canvas animation', () => {
    expect.soft(docHero).not.toContain('FlickeringGrid')
    expect.soft(docHero).not.toContain('<canvas')
    expect.soft(docHero).not.toContain('ResizeObserver')
    expect.soft(docHero).not.toContain('IntersectionObserver')
    expect.soft(docHero).not.toContain('requestAnimationFrame')
    expect.soft(docHero).not.toContain('.docs-hero__glow')
    expect.soft(docHero).not.toContain('radial-gradient')
    expect.soft(docHero).toContain('font-size: 3.5rem')
    expect.soft(docHero).toContain('font-size: 2.35rem')
  })

  it('keeps code block copy headers out of the SSR Vue render graph', () => {
    expect.soft(page).toContain('function renderCodeHeader(target: HTMLElement, language: string, codeText: string)')
    expect.soft(page).toContain("document.createElement('button')")
    expect.soft(page).toContain("copyButton.className = 'docs-code-copy'")
    expect.soft(page).toContain('copyButton.addEventListener(\'click\'')
    expect.soft(page).toContain('target.append(languageLabel, copyButton)')
    expect.soft(page).toContain('target.replaceChildren()')
    expect.soft(page).not.toContain('const CodeHeader = defineComponent')
    expect.soft(page).not.toContain('render(vnode, target)')
    expect.soft(page).not.toContain('const nuxtApp = useNuxtApp()')
    expect.soft(page).not.toMatch(/import \{[^}]*defineComponent[^}]*render[^}]*\} from 'vue'/)
  })

  it('loads docs toast feedback only after copy or share intent', () => {
    expect.soft(page).toContain("async function showDocsToast(type: 'success' | 'error', title: string)")
    expect.soft(page).toContain("const { useToast } = await import('~/composables/useToast')")
    expect.soft(page).toContain("await showDocsToast('success', copyLabels.value.copied)")
    expect.soft(page).toContain("await showDocsToast('error', copyLabels.value.failed)")
    expect.soft(page).toContain("await showDocsToast('success', t('docs.shareCopied', 'Link copied!'))")
    expect.soft(page).toContain("await showDocsToast('error', t('docs.shareFailed', 'Copy failed'))")
    expect.soft(page).toContain('const { t, setLocale } = useI18n()\nconst activeRoutePath = ref(route.path)')
    expect.soft(page).not.toContain('toast.success(')
    expect.soft(page).not.toContain('toast.error(')
  })

  it('reads docs admin state without pulling auth composables into the docs setup graph', () => {
    expect.soft(page).toContain("const authUserState = useState<{ role?: string } | null>('auth-user', () => null)")
    expect.soft(page).toContain("const isAdmin = computed(() => authUserState.value?.role === 'admin')")
    expect.soft(page).not.toContain('useAuthUser({ fetchOnAuth: false, server: false })')
    expect.soft(page).not.toContain('const { user } = useAuthUser')

    expect.soft(appRoot).toContain("const authUserState = useState<AppAuthUserState | null>('auth-user', () => null)")
    expect.soft(appRoot).toContain("const authUserPending = useState<boolean>('auth-user-pending', () => false)")
    expect.soft(appRoot).toContain('async function fetchProtectedAuthUser()')
    expect.soft(appRoot).toContain("const { fetchCurrentUserProfile } = await import('~/composables/useCurrentUserApi')")
    expect.soft(appRoot).toMatch(/if \(currentStatus === 'authenticated' && protectedRoute\) \{[\s\S]*void fetchProtectedAuthUser\(\)/)
    expect.soft(appRoot).not.toContain('const { user, pending: authUserPending } = useAuthUser')
    expect.soft(appRoot).not.toContain('useAuthUser({')

    expect.soft(localeOrchestrator).not.toContain("import { fetchCurrentUserProfile, patchCurrentUserProfile } from '~/composables/useCurrentUserApi'")
    expect.soft(localeOrchestrator).toContain("const { patchCurrentUserProfile } = await import('~/composables/useCurrentUserApi')")
    expect.soft(localeOrchestrator).toContain("const { fetchCurrentUserProfile } = await import('~/composables/useCurrentUserApi')")
  })

  it('keeps the sidebase auth client plugin out of the public docs app shell', () => {
    expect.soft(nuxtConfig).toContain('function isSidebaseAuthClientPlugin')
    expect.soft(nuxtConfig).toContain('function isSidebaseAuthMiddleware')
    expect.soft(nuxtConfig).toContain('function removeSidebaseAuthAppRuntime')
    expect.soft(nuxtConfig).toContain("replace(/\\.js$/, '')")
    expect.soft(nuxtConfig).toContain("normalized.endsWith('/@sidebase/nuxt-auth/dist/runtime/middleware/auth')")
    expect.soft(nuxtConfig).toMatch(/function removeSidebaseAuthAppRuntime[\s\S]*isSidebaseAuthClientPlugin\(app\.plugins\[index\]\?\.src\)[\s\S]*isSidebaseAuthMiddleware\(middleware\?\.name, middleware\?\.path\)/)
    expect.soft(nuxtConfig).toMatch(/'app:resolve'\(app\) \{[\s\S]*removeSidebaseAuthAppRuntime\(app\)/)
    expect.soft(nuxtConfig).toMatch(/'app:templates'\(app\) \{[\s\S]*removeSidebaseAuthAppRuntime\(app\)/)

    expect.soft(appRoot).toContain('const { status, getSession } = useNexusAuth()')
    expect.soft(theHeader).toContain('const { status } = useNexusAuth()')
    expect.soft(appRoot).not.toContain('useAuth()')
    expect.soft(theHeader).not.toContain('useAuth()')

    expect.soft(nexusAuth).toContain("const AUTH_BASE_URL = '/api/auth'")
    expect.soft(nexusAuth).not.toContain('@sidebase/nuxt-auth')
    expect.soft(nexusAuth).not.toContain('dist/runtime/plugin')
  })

  it('keeps auth runtime coverage on explicit auth and protected route matrix after removing sidebase client plugin', () => {
    expect.soft(nuxtConfig).toContain("'@sidebase/nuxt-auth'")
    expect.soft(nuxtConfig).toContain("baseURL: '/api/auth'")
    expect.soft(nuxtConfig).toContain("type: 'authjs'")
    expect.soft(nuxtConfig).toContain("const nextAuthCoreEntry = resolve(currentDir, 'node_modules/next-auth/core/index.js')")
    expect.soft(nuxtConfig).toMatch(/alias: \{[\s\S]*'next-auth\/core': nextAuthCoreEntry/)
    expect.soft(packageJson).toContain('"#auth": "./node_modules/@sidebase/nuxt-auth/dist/runtime/server/services/index.js"')
    expect.soft(authApi).toContain('const createRequestAuthEvent = () => createAuthEvent()')
    expect.soft(authApi).toContain('let cachedAuthHandler')
    expect.soft(authApi).toContain('function getCachedAuthHandler(event: H3Event)')
    expect.soft(authApi).toContain('cachedAuthHandler ??= NuxtAuthHandler(getAuthOptions(resolveSessionAuthSecret(event)))')
    expect.soft(authApi).toContain('const authHandler = getCachedAuthHandler(event)')
    expect.soft(authApi).toContain('bindings?.AUTH_SECRET')
    expect.soft(authApi).toContain('selectRuntimeCredential(')
    expect.soft(authApi).not.toContain('NuxtAuthHandler(getAuthOptions(event))')
    expect.soft(authApi).not.toContain('function getAuthOptions(event')

    expect.soft(signInPage).toContain('useSignIn()')
    expect.soft(signInCallbackPage).toContain("path: '/sign-in'")
    expect.soft(appCallbackPage).toContain('const { status: sessionStatus, getSession } = useNexusAuth()')
    expect.soft(appCallbackPage).toContain('ensureAuthenticatedSession')
    expect.soft(appCallbackPage).toContain("'x-device-client': 'app'")

    expect.soft(dashboardPage).toContain('requiresAuth: true')
    expect.soft(dashboardPage).toContain('const { isAuthenticated } = useAuthUser()')
    expect.soft(teamJoinPage).toContain('requiresAuth: true')
    expect.soft(teamJoinPage).toContain('fetchCurrentUserProfile')
    expect.soft(adminBootstrapPage).toContain('requiresAuth: true')
    expect.soft(adminBootstrapPage).toContain('const { signOut } = useNexusAuth()')

    expect.soft(appRoot).toContain('const isProtectedRoute = computed(() => route.meta.requiresAuth === true)')
    expect.soft(appRoot).toMatch(/if \(!protectedSessionRecheckDone\.value && !protectedSessionRecheckRunning\.value\) \{[\s\S]*void getSession\(\)[\s\S]*protectedSessionRecheckDone\.value = true/)
    expect.soft(appRoot).toMatch(/router\.replace\(\{[\s\S]*path: '\/sign-in'[\s\S]*redirect_url: redirectTarget\.value/)

    expect.soft(theHeader).toContain("const HeaderUserMenu = defineAsyncComponent(() => import('./HeaderUserMenu.vue'))")
    expect.soft(theHeader).toContain('const isAuthenticated = computed(() => status.value === \'authenticated\')')
  })

  it('keeps docs, store, dashboard, and landing source boundaries split before production chunking', () => {
    expect.soft(page).not.toContain("~/components/dashboard/")
    expect.soft(page).not.toContain("~/components/store/")
    expect.soft(page).not.toContain("~/components/tuff/landing/")
    expect.soft(page).not.toContain("from '@talex-touch/tuffex/button'")
    expect.soft(page).not.toContain("from '@talex-touch/tuffex/tabs'")

    expect.soft(storePage).not.toContain("~/components/docs/")
    expect.soft(storePage).not.toContain("~/components/tuff/landing/")
    expect.soft(storePage).not.toContain("~/components/dashboard/")
    expect.soft(storePage).toContain("~/components/plugin/PluginMetaHeader.vue")
    expect.soft(storeLayout).not.toContain("~/components/docs/")
    expect.soft(storeLayout).not.toContain("~/components/dashboard/")

    expect.soft(dashboardPage).not.toContain("~/components/docs/")
    expect.soft(dashboardPage).not.toContain("~/components/store/")
    expect.soft(dashboardOverviewPage).not.toContain("~/components/docs/")
    expect.soft(dashboardOverviewPage).not.toContain("~/components/store/")
    expect.soft(providerRegistryPage).toContain('<ClientOnly>')
    expect.soft(providerRegistryPage).toContain('<LazyDashboardProviderRegistryAdminPanel />')
    expect.soft(providerRegistryPage).not.toContain("import ProviderRegistryAdminPanel")
    expect.soft(governancePage).not.toContain("~/components/docs/")
    expect.soft(governancePage).not.toContain("~/components/store/")

    expect.soft(landingPage).toContain("defineAsyncComponent(() => import('~/components/tuff/TuffHome.vue'))")
    expect.soft(landingPage).not.toContain("~/components/dashboard/")
    expect.soft(landingPage).not.toContain("~/components/docs/")
    expect.soft(landingPage).not.toContain("~/components/store/")
    expect.soft(newLandingPage).toContain("defineAsyncComponent(() => import('~/components/tuff/landing/TuffLandingPlugins.vue'))")
    expect.soft(newLandingPage).not.toContain("~/components/dashboard/")
    expect.soft(newLandingPage).not.toContain("~/components/docs/")
    expect.soft(newLandingPage).not.toContain("~/components/store/")
  })

  it('keeps lightweight docs tracking separate from bottom engagement widgets', () => {
    expect.soft(page).toContain('DOC_CLIENT_PANEL_IDLE_TIMEOUT_MS = 2500')
    expect.soft(page).toContain('DOC_CLIENT_PANEL_INTENT_EVENTS')
    expect.soft(page).toContain('bindDocClientPanelIntentListeners')
    expect.soft(page).toContain('handleDocClientPanelIntent')
    expect.soft(page).toContain('scheduleDocClientPanels')
    expect.soft(page).toMatch(/window\.addEventListener\(eventName, handleDocClientPanelIntent, \{ passive: true \}\)/)
    expect.soft(page).toMatch(/if \('requestIdleCallback' in window\) \{[\s\S]*DOC_CLIENT_PANEL_IDLE_TIMEOUT_MS/)
    expect.soft(page).toMatch(/if \(!isReady \|\| !docsClientPanelsMounted\.value\)[\s\S]*bindDocClientPanelIntentListeners\(\)/)
    expect.soft(page).toMatch(/if \(!isMounted \|\| !isDocsContentReady\.value\)[\s\S]*bindDocClientPanelIntentListeners\(\)/)
    expect.soft(page).toContain('<LazyDocsEngagementClient')
    expect.soft(page).toContain('v-if="shouldMountDocClientPanels"')
    expect.soft(page).toContain('<LazyDocsFeedback v-if="shouldMountDocEngagementPanels"')
    expect.soft(page).toContain('<LazyDocsComments v-if="shouldMountDocEngagementPanels"')
  })

  it('keeps docs engagement tracking bfcache-friendly', () => {
    expect.soft(docEngagementTracker).toContain("useEventListener(document, 'visibilitychange'")
    expect.soft(docEngagementTracker).toContain("useEventListener(window, 'pagehide'")
    expect.soft(docEngagementTracker).not.toContain('beforeunload')
  })

  it('builds docs assistant context only after assistant intent', () => {
    expect.soft(docsLayout).toContain("const docsAssistantContextRequestState = useState<number>('docs-assistant-context-request'")
    expect.soft(docsLayout).toMatch(/function openDocsAssistantFromShell\(source: HTMLElement \| null\) \{[\s\S]*docsAssistantContextRequestState\.value \+= 1[\s\S]*docsAssistantOpenRequest\.value \+= 1/)

    expect.soft(page).toContain("const docAssistantContextRequestState = useState<number>('docs-assistant-context-request'")
    expect.soft(page).toContain('const pendingAssistantContextRequest = ref(0)')
    expect.soft(page).toContain('function requestAssistantContextBuild(requestId: number)')
    expect.soft(page).toMatch(/watch\([\s\S]*docAssistantContextRequestState,[\s\S]*requestAssistantContextBuild\(requestId\)[\s\S]*\)/)
    expect.soft(page).toMatch(/if \(!body\) \{[\s\S]*startFullDocFetchForRoute\(\)[\s\S]*return[\s\S]*\}/)
    expect.soft(page).toMatch(/if \(pendingAssistantContextRequest\.value > 0\)[\s\S]*requestAssistantContextBuild\(pendingAssistantContextRequest\.value\)/)
    expect.soft(page).not.toContain('scheduleAssistantContextBuild(renderDoc.value?.body, 700)')
  })

  it('keeps docs chrome controls off first-paint TuffEx button imports', () => {
    expect.soft(page).not.toContain("from '@talex-touch/tuffex/button'")
    expect.soft(page).not.toContain("from '@talex-touch/tuffex/loading-state'")
    expect.soft(page).not.toContain('h(TxButton')
    expect.soft(page).not.toContain('<TxLoadingState')
    expect.soft(page).toContain("document.createElement('button')")
    expect.soft(page).toContain('class="docs-loading-state"')

    expect.soft(docsLayout).not.toContain("import Drawer from '~/components/ui/Drawer.vue'")
    expect.soft(docsLayout).not.toContain("import BackToTop from '~/components/ui/BackToTop.vue'")
    expect.soft(docsLayout).toContain("const DocsDrawer = defineAsyncComponent(() => import('~/components/ui/Drawer.vue'))")
    expect.soft(docsLayout).toContain("const LazyDocsAsideCards = defineAsyncComponent(() => import('~/components/docs/DocsAsideCards.vue'))")
    expect.soft(docsLayout).toContain("const LazyDocsAsideCardsShell = defineAsyncComponent(() => import('~/components/docs/DocsAsideCardsShell.vue'))")
    expect.soft(docsLayout).toContain("const LazyDocsOutline = defineAsyncComponent(() => import('~/components/DocsOutline.vue'))")
    expect.soft(docsLayout).toContain("const LazyBackToTop = defineAsyncComponent(() => import('~/components/ui/BackToTop.vue'))")
    expect.soft(docsLayout).toContain("const LazyTuffFooter = defineAsyncComponent(() => import('~/components/TuffFooter.vue'))")
    expect.soft(docsLayout).toContain("DOCS_FOOTER_ROOT_MARGIN = '1200px 0px'")
    expect.soft(docsLayout).toContain('DOCS_ASIDE_SHELL_MOUNT_DELAY_MS = 2400')
    expect.soft(docsLayout).toContain('DOCS_ASIDE_SHELL_IDLE_TIMEOUT_MS = 3600')
    expect.soft(docsLayout).toContain('DOCS_OUTLINE_MOUNT_DELAY_MS = 2000')
    expect.soft(docsLayout).toContain('DOCS_OUTLINE_IDLE_TIMEOUT_MS = 3200')
    expect.soft(docsLayout).toContain('const docsFooterSentinelRef = ref<HTMLElement | null>(null)')
    expect.soft(docsLayout).toContain('const shouldMountDocsFooter = ref(false)')
    expect.soft(docsLayout).toContain('let docsFooterObserver: IntersectionObserver | null = null')
    expect.soft(docsLayout).toMatch(/new IntersectionObserver\([\s\S]*DOCS_FOOTER_ROOT_MARGIN[\s\S]*docsFooterObserver\.observe\(sentinel\)/)
    expect.soft(docsLayout).toMatch(/if \(!\('IntersectionObserver' in window\)\) \{[\s\S]*mountDocsFooter\(\)/)
    expect.soft(docsLayout).toContain('BACK_TO_TOP_MOUNT_SCROLL_Y = 240')
    expect.soft(docsLayout).toContain('const shouldMountBackToTop = ref(false)')
    expect.soft(docsLayout).toMatch(/window\.addEventListener\('scroll', scheduleBackToTopMountCheck, \{ passive: true \}\)/)
    expect.soft(docsLayout).toContain('class="docs-mobile-action"')
    expect.soft(docsLayout).not.toContain('<TxButton')
    expect.soft(docsLayout).toContain('const sidebarDrawerMounted = ref(false)')
    expect.soft(docsLayout).toContain('const outlineDrawerMounted = ref(false)')
    expect.soft(docsLayout).toContain('const shouldMountDocsAsideCards = ref(false)')
    expect.soft(docsLayout).toContain('const shouldMountDocsAsideShell = ref(false)')
    expect.soft(docsLayout).toContain('const shouldMountDocsOutline = ref(false)')
    expect.soft(docsLayout).toContain('const docsAssistantShellTriggerRef = ref<HTMLElement | null>(null)')
    expect.soft(docsLayout).toContain('function clearDocsAsideShellSchedule()')
    expect.soft(docsLayout).toContain('function mountDocsAsideShell()')
    expect.soft(docsLayout).toContain('function scheduleDocsAsideShellMount()')
    expect.soft(docsLayout).toMatch(/docsAsideShellTimer = setTimeout\(\(\) => \{[\s\S]*window\.requestIdleCallback\(mount, \{ timeout: DOCS_ASIDE_SHELL_IDLE_TIMEOUT_MS \}\)[\s\S]*DOCS_ASIDE_SHELL_MOUNT_DELAY_MS/)
    expect.soft(docsLayout).toContain("const outlineTocState = useState<any[]>('docs-toc'")
    expect.soft(docsLayout).toContain("const outlineLoadingState = useState<boolean>('docs-outline-loading'")
    expect.soft(docsLayout).toContain('function clearDocsOutlineSchedule()')
    expect.soft(docsLayout).toContain('function mountDocsOutline()')
    expect.soft(docsLayout).toContain('function scheduleDocsOutlineMount()')
    expect.soft(docsLayout).toMatch(/docsOutlineTimer = setTimeout\(\(\) => \{[\s\S]*window\.requestIdleCallback\(mount, \{ timeout: DOCS_OUTLINE_IDLE_TIMEOUT_MS \}\)[\s\S]*DOCS_OUTLINE_MOUNT_DELAY_MS/)
    expect.soft(docsLayout).toMatch(/watch\(shouldShowAsideOutline,[\s\S]*scheduleDocsOutlineMount\(\)[\s\S]*clearDocsOutlineSchedule\(\)/)
    expect.soft(docsLayout).toContain('const docsAssistantOpenRequest = ref(0)')
    expect.soft(docsLayout).toContain('const docsAssistantSource = shallowRef<HTMLElement | null>(null)')
    expect.soft(docsLayout).toContain('const docMetaState = useState<Record<string, any>>(\'docs-meta\'')
    expect.soft(docsLayout).toContain('const shouldShowDocsAsideAiNotice = computed(() => {')
    expect.soft(docsLayout).toContain("const docsAsideAiNoticeTitle = computed(() => t('docs.aiNotice.title'))")
    expect.soft(docsLayout).toContain("const docsAsideAiNoticeDescription = computed(() => t('docs.aiNotice.description'))")
    expect.soft(docsLayout).toContain('function openDocsAssistantFromShell(source: HTMLElement | null)')
    expect.soft(docsLayout).toContain('function openDocsAssistantFromPlaceholder()')
    expect.soft(docsLayout).toMatch(/function openDocsAssistantFromShell\(source: HTMLElement \| null\) \{[\s\S]*mountDocsAsideShell\(\)[\s\S]*docsAssistantOpenRequest\.value \+= 1/)
    expect.soft(docsLayout).not.toContain('watch(shouldShowDocsAsideAiNotice')
    expect.soft(docsLayout).toContain('class="docs-aside-ai-notice"')
    expect.soft(docsLayout).toContain('{{ docsAsideAiNoticeTitle }}')
    expect.soft(docsLayout).toContain('{{ docsAsideAiNoticeDescription }}')
    expect.soft(docsLayout).toContain('function openSidebarDrawer()')
    expect.soft(docsLayout).toContain('function openOutlineDrawer()')
    expect.soft(docsLayout).toMatch(/function openOutlineDrawer\(\) \{[\s\S]*mountDocsOutline\(\)[\s\S]*outlineVisible\.value = true/)
    expect.soft(docsLayout).toContain('@click="openSidebarDrawer"')
    expect.soft(docsLayout).toContain('@click="openOutlineDrawer"')
    expect.soft(docsLayout).toContain('<LazyDocsOutline v-if="shouldMountDocsOutline"')
    expect.soft(docsLayout).toContain('v-else class="docs-outline-shell"')
    expect.soft(docsLayout).toContain('.docs-outline-shell__line')
    expect.soft(docsLayout).toContain('<LazyDocsOutline v-if="outlineVisible && shouldMountDocsOutline"')
    expect.soft(docsLayout).not.toContain('<DocsOutline />')
    expect.soft(docsLayout).not.toContain('<DocsOutline v-if="outlineVisible"')
    expect.soft(docsLayout).toContain('<LazyDocsAsideCards\n                  v-if="shouldMountDocsAsideCards"')
    expect.soft(docsLayout).toContain(':assistant-open-request="docsAssistantOpenRequest"')
    expect.soft(docsLayout).toContain(':assistant-source="docsAssistantSource"')
    expect.soft(docsLayout).toMatch(/<section[\s\S]*v-if="shouldShowDocsAsideAiNotice"[\s\S]*class="docs-aside-ai-notice"[\s\S]*<\/section>/)
    expect.soft(docsLayout).toContain('<LazyDocsAsideCardsShell')
    expect.soft(docsLayout).toContain('v-if="shouldMountDocsAsideShell"')
    expect.soft(docsLayout).toContain('@open-assistant="openDocsAssistantFromShell"')
    expect.soft(docsLayout).toContain('class="docs-aside-assistant-shell"')
    expect.soft(docsLayout).toContain('@click="openDocsAssistantFromPlaceholder"')
    expect.soft(docsLayout).not.toContain('<DocsAsideCardsShell')
    expect.soft(docsLayout).not.toContain('<DocsAsideCards />')
    expect.soft(docsLayout).toContain('<DocsDrawer\n        v-if="sidebarDrawerMounted"')
    expect.soft(docsLayout).toContain('<DocsDrawer\n        v-if="outlineDrawerMounted"')
    expect.soft(docsLayout).toContain('<LazyBackToTop v-if="shouldMountBackToTop"')
    expect.soft(docsLayout).toContain('ref="docsFooterSentinelRef"')
    expect.soft(docsLayout).toContain('<LazyTuffFooter v-if="shouldMountDocsFooter"')
    expect.soft(docsLayout).not.toContain('<TuffFooter class="docs-layout-footer"')

    expect.soft(docSection).not.toContain('@talex-touch/tuffex/button')
    expect.soft(docSection).not.toContain('@talex-touch/tuffex/auto-sizer')
    expect.soft(docSection).not.toContain('<TxButton')
    expect.soft(docSection).not.toContain('<TxAutoSizer')
    expect.soft(docSection).toContain('<button\n      v-else')
    expect.soft(docSection).toContain('class="DocSection-Header bg-transparent"')
    expect.soft(docSection).toContain('class="DocSection-Body"')
    expect.soft(docSection).toContain('grid-template-rows: 0fr')
    expect.soft(docSection).toContain('grid-template-rows: 1fr')

    expect.soft(docsAsideCards).not.toContain('@talex-touch/tuffex/button')
    expect.soft(docsAsideCards).not.toContain('<TxButton')
    expect.soft(docsAsideCards).toContain("const LazyDocsAssistantDialog = defineAsyncComponent(() => import('./DocsAssistantDialog.vue'))")
    expect.soft(docsAsideCards).toContain('assistantOpenRequest?: number')
    expect.soft(docsAsideCards).toContain('assistantSource?: HTMLElement | null')
    expect.soft(docsAsideCards).toContain('() => props.assistantOpenRequest')
    expect.soft(docsAsideCards).toContain('assistantOpen.value = true')
    expect.soft(docsAsideCards).not.toContain('class="docs-aside-assistant"')
    expect.soft(docsAsideCards).not.toContain('syncStatus')
    expect.soft(docsAsideCards).not.toContain('showAiNotice')
    expect.soft(docsAsideCards).not.toContain('docs-aside-card--notice')

    expect.soft(docsAsideCardsShell).not.toContain("DocsAssistantDialog")
    expect.soft(docsAsideCardsShell).not.toContain('docs-meta')
    expect.soft(docsAsideCardsShell).toContain('class="docs-aside-assistant"')
    expect.soft(docsAsideCardsShell).toContain('emit(\'openAssistant\', assistantTriggerRef.value)')
    expect.soft(docsAsideCardsShell).toContain("t('docs.aside.askAi')")
    expect.soft(docsAsideCardsShell).toContain("t('docs.aside.resources')")
    expect.soft(docsAsideCardsShell).not.toContain("locale.value === 'zh'")
    expect.soft(i18nEn).toContain("askAi: 'Ask AI about this page'")
    expect.soft(i18nZh).toContain("askAi: '用 AI 解读本页'")

    expect.soft(theHeader).toContain("const HeaderUserMenu = defineAsyncComponent(() => import('./HeaderUserMenu.vue'))")
    expect.soft(theHeader).not.toContain("import HeaderUserMenu from './HeaderUserMenu.vue'")
    expect.soft(theHeader).toContain('<HeaderUserMenu />')

    expect.soft(headerControls).not.toContain('@talex-touch/tuffex/button')
    expect.soft(headerControls).not.toContain('<TxButton')
    expect.soft(headerControls).not.toContain('<TxDivider')
    expect.soft(headerControls).toContain('class="HeaderControls-IconButton"')
    expect.soft(headerControls).toContain('class="HeaderControls-Divider"')

    expect.soft(languageToggle).not.toContain('@talex-touch/tuffex/icon-button')
    expect.soft(languageToggle).not.toContain('<TxIconButton')
    expect.soft(languageToggle).toContain('class="LanguageToggle-Trigger"')
    expect.soft(languageToggle).not.toContain('@floating-ui/vue')
    expect.soft(languageToggle).not.toContain("import Icon from './icon/Icon.vue'")
    expect.soft(languageToggle).toContain("defineAsyncComponent(() => import('./LanguageToggleMenu.vue'))")
    expect.soft(languageToggle).toContain('<LazyLanguageToggleMenu')
    expect.soft(languageToggle).toContain('v-if="isMenuRequested"')
    expect.soft(languageToggle).toContain('function requestMenu()')
    expect.soft(languageToggle).toContain('function handleTriggerClick()')
    expect.soft(languageToggle).toContain('@focus="requestMenu"')
    expect.soft(languageToggleMenu).toContain('@floating-ui/vue')

    expect.soft(darkToggle).not.toContain('@talex-touch/tuffex/icon-button')
    expect.soft(darkToggle).not.toContain('<TxIconButton')
    expect.soft(darkToggle).toContain('class="DarkToggle"')

    expect.soft(iconComposer).not.toContain('fonts.googleapis.com')
    expect.soft(iconComposer).not.toContain('Space Grotesk')
    expect.soft(iconComposer).toContain('font-nexus-display')

    expect.soft(backToTop).not.toContain('<TxButton')
    expect.soft(backToTop).toContain('<button v-show="visible"')
    expect.soft(backToTop).toContain('class="back-to-top"')

    expect.soft(toastHost).not.toContain('@talex-touch/tuffex/button')
    expect.soft(toastHost).not.toContain('<TxButton')
    expect.soft(toastHost).toContain('class="toast-dismiss"')

    expect.soft(tuffDemoWrapper).not.toContain('<TxButton')
    expect.soft(tuffDemoWrapper).toContain('class="tuff-demo__reset-btn"')
    expect.soft(tuffDemoWrapper).toContain('class="tuff-demo__toggle-btn"')
    expect.soft(tuffDemoWrapper).not.toContain('class="tuff-demo__run-btn"')
    expect.soft(tuffDemoWrapper).toContain('<LazyTuffDemoClientRenderer')
    expect.soft(tuffDemoWrapper).not.toContain('<TuffDemoClientRenderer')
    expect.soft(tuffDemoWrapper).toContain("const LazyEmbeddedCodeBlock = defineAsyncComponent(() => import('./TuffCodeBlock.vue'))")
    expect.soft(tuffDemoWrapper).toContain('<LazyEmbeddedCodeBlock')
    expect.soft(tuffDemoWrapper).toContain('v-if="hasCode && showCode"')
    expect.soft(tuffDemoWrapper).not.toContain('<LazyTuffCodeBlock')
    expect.soft(tuffDemoWrapper).not.toContain('<TuffCodeBlock')
    expect.soft(tuffDemoWrapper).toContain('new IntersectionObserver')
    expect.soft(tuffDemoWrapper).not.toContain('scheduleDemoActivation')

    expect.soft(tuffCodeBlock).not.toContain("from '~/utils/highlight'")
    expect.soft(tuffCodeBlock).toContain("const LazyTuffCodeBlockRenderer = defineAsyncComponent(() => import('./TuffCodeBlockRenderer.vue'))")
    expect.soft(tuffCodeBlock).not.toContain('<style')
    expect.soft(tuffCodeBlockRenderer).toContain("await import('~/utils/highlight')")
    expect.soft(tuffCodeBlockRenderer).toContain("await import('~/utils/mermaid-renderer')")
    expect.soft(tuffCodeBlock).not.toContain('<TxButton')
    expect.soft(tuffCodeBlockRenderer).not.toContain('<TxButton')
    expect.soft(tuffCodeBlockRenderer).toContain('class="tuff-code-block__copy"')

    expect.soft(tuffPropsTable).not.toContain("from 'vue-sonner'")
    expect.soft(tuffPropsTable).not.toContain('<TxButton')
    expect.soft(tuffPropsTable).not.toContain('<TxTag')
    expect.soft(tuffPropsTable).toContain('class="tuff-props-table__copy-status"')
    expect.soft(tuffPropsTable).toContain('class="tuff-props-table__tag"')
    expect.soft(tuffPropsTable).toContain('class="tuff-props-table__mono"')
  })

  it('keeps route-local locale payloads out of the docs base i18n chunk', () => {
    expect.soft(i18nEn).not.toContain('\n  dashboard: {')
    expect.soft(i18nEn).not.toContain('\n  landing: {')
    expect.soft(i18nZh).not.toContain('\n  dashboard: {')
    expect.soft(i18nZh).not.toContain('\n  landing: {')

    expect.soft(routeLocaleChunks).toContain("dashboard: () => import('../../i18n/locales/route/en/dashboard')")
    expect.soft(routeLocaleChunks).toContain("landing: () => import('../../i18n/locales/route/en/landing')")
    expect.soft(routeLocaleChunks).toContain("dashboard: () => import('../../i18n/locales/route/zh/dashboard')")
    expect.soft(routeLocaleChunks).toContain("landing: () => import('../../i18n/locales/route/zh/landing')")
    expect.soft(routeLocaleChunks).toContain('loadingChunks')
    expect.soft(routeLocaleChunks).not.toContain('loadedChunks')

    expect.soft(routeLocaleComposable).toContain('mergeLocaleMessage')
    expect.soft(routeLocaleComposable).toContain('[chunk]: messages')

    expect.soft(routeLocaleChunks).toContain("normalized === '/' || normalized === '/new' || normalized.startsWith('/new/') || normalized === '/next' || normalized.startsWith('/next/')")
    expect.soft(routeLocaleChunks).toContain("normalized === '/dashboard'")
    expect.soft(routeLocaleChunks).toContain("normalized.startsWith('/dashboard/')")
    expect.soft(routeLocaleChunks).toContain("normalized === '/store'")
    expect.soft(routeLocaleChunks).toContain("normalized === '/team/join'")
    expect.soft(routeLocaleMiddleware).toContain("import { resolveRouteLocaleChunks } from '~/utils/route-locale-chunks'")
    expect.soft(localeOrchestrator).toContain("import { resolveRouteLocaleChunks } from '~/utils/route-locale-chunks'")
    expect.soft(localeOrchestrator).toContain('await ensureCurrentRouteLocaleChunks(normalized)')
    expect.soft(localeOrchestrator).toContain("const chunks = resolveRouteLocaleChunks(route.path || '/')")
    expect.soft(routeLocaleMiddleware).not.toMatch(/docs[^\\n]*push\\('(dashboard|landing)'\\)/)

    expect.soft(tuffFooter).toContain("await ensureRouteLocaleChunk(normalizeLocale(locale.value) || 'en', 'landing')")
  })

  it('keeps syntax and diagram rendering out of the global first-paint plugin list', () => {
    expect.soft(nuxtConfig).toContain("'app/plugins/highlight.client.ts'")
    expect.soft(nuxtConfig).toContain("'app/plugins/mermaid.client.ts'")
    expect.soft(tuffCodeBlock).toContain("defineAsyncComponent(() => import('./TuffCodeBlockRenderer.vue'))")
    expect.soft(tuffCodeBlock).not.toContain("await import('~/utils/highlight')")
    expect.soft(tuffCodeBlockRenderer).toContain("await import('~/utils/highlight')")
    expect.soft(page).toContain('function renderMermaidBlocks()')
    expect.soft(page).toContain("await import('~/utils/mermaid-renderer')")

    expect.soft(mermaidRenderer).toContain("await import('mermaid')")
    expect.soft(mermaidRenderer).toContain('renderMermaidInDocument')
    expect.soft(mermaidRenderer).not.toContain("from 'mermaid'")
  })

  it('keeps global search indexes behind explicit search intent', () => {
    expect.soft(appRoot).not.toContain('useGlobalSearch()')
    expect.soft(appRoot).toContain('useGlobalSearchState()')
    expect.soft(headerControls).not.toContain("import { useGlobalSearch } from '~/composables/useGlobalSearch'")
    expect.soft(headerControls).toContain('~/composables/useGlobalSearchState')

    expect.soft(globalSearchState).not.toContain('@talex-touch/utils/search')
    expect.soft(globalSearchState).not.toContain('~/data/search/featureIndex')
    expect.soft(globalSearchState).not.toContain('~/data/search/pageIndex')
    expect.soft(globalSearchState).not.toContain('queryCollection')

    expect.soft(globalSearch).not.toContain("from '@talex-touch/utils/search'")
    expect.soft(globalSearch).not.toContain("import('@talex-touch/utils/search')")
    expect.soft(globalSearch).not.toContain("from '~/data/search/featureIndex'")
    expect.soft(globalSearch).not.toContain("from '~/data/search/pageIndex'")
    expect.soft(globalSearch).toContain("import('@talex-touch/utils/search/feature-matcher')")
    expect.soft(globalSearch).toContain("import('~/data/search/featureIndex')")
    expect.soft(globalSearch).toContain("import('~/data/search/pageIndex')")
    expect.soft(globalSearch).toMatch(/fetchContentApi<DocsSearchResponse>\(`\/api\/docs\/search\/\$\{locale\}`/)
    expect.soft(globalSearch).toMatch(/fetchContentApi<SidebarComponentItem\[]>\(`\/api\/docs\/sidebar-components\/\$\{locale\}`/)
    expect.soft(globalSearch).not.toContain('queryCollection(')
    expect.soft(globalSearch).not.toContain('searchContent(')
    expect.soft(legacySearch).toMatch(/fetchContentApi<DocsSearchResponse>\(`\/api\/docs\/search\/\$\{targetLocale\}`/)
    expect.soft(legacySearch).not.toContain('searchContent(')
  })

  it('loads policy Markdown through the server content boundary', () => {
    expect.soft(policyMarkdown).toContain("fetchContentApi<PolicyContentResponse>('/api/content/policy'")
    expect.soft(policyMarkdown).not.toContain('queryCollection(')
  })

  it('keeps the global toast host out of first-paint docs modules', () => {
    expect.soft(constants).toContain("toastHostRequestedEvent = 'nexus:toast-host-requested'")
    expect.soft(appRoot).not.toContain('<ToastContainer />')
    expect.soft(appRoot).toContain("const LazyToastContainer = defineAsyncComponent(() => import('~/components/ToastContainer.vue'))")
    expect.soft(appRoot).toContain('const toastHostMounted = ref(false)')
    expect.soft(appRoot).toContain('function mountToastHost()')
    expect.soft(appRoot).toMatch(/window\.addEventListener\(toastHostRequestedEvent, mountToastHost\)/)
    expect.soft(appRoot).toMatch(/window\.removeEventListener\(toastHostRequestedEvent, mountToastHost\)/)
    expect.soft(appRoot).toContain('<LazyToastContainer v-if="toastHostMounted"')
    expect.soft(useToast).toContain("import { toastHostRequestedEvent } from '~/constants'")
    expect.soft(useToast).toContain('function requestToastHost()')
    expect.soft(useToast).toContain('window.dispatchEvent(new CustomEvent(toastHostRequestedEvent))')
    expect.soft(useToast).toMatch(/toastItems\.value = \[\.\.\.toastItems\.value, toast\][\s\S]*requestToastHost\(\)[\s\S]*scheduleDismiss\(id, toast\.duration\)/)
  })

  it('lets Nuxt i18n lazy load locale messages instead of bundling both languages into first paint', () => {
    expect.soft(i18nConfig).not.toContain('../i18n/locales/en')
    expect.soft(i18nConfig).not.toContain('../i18n/locales/zh')
    expect.soft(i18nConfig).not.toMatch(/\bmessages\s*:/)
    expect.soft(nuxtConfig).toMatch(/i18n: \{[\s\S]*locales: \[[\s\S]*\{ code: 'en', file: 'en\.ts' \}[\s\S]*\{ code: 'zh', file: 'zh\.ts' \}[\s\S]*langDir: 'locales'[\s\S]*defaultLocale: 'en'/)
  })

  it('keeps the browser title reactive when a reused docs route changes', () => {
    expect.soft(page).toMatch(/useHead\(\(\) => \(\{[\s\S]*title: docSeoHead\.value\.pageTitle[\s\S]*\}\)\)/)
  })

  it('preserves Vue Router history state when syncing the outline hash', () => {
    expect.soft(docsOutline).not.toContain("history.replaceState(null, '', next)")
    expect.soft(docsOutline).toMatch(/history\.replaceState\(history\.state, '', `\$\{window\.location\.pathname\}\$\{window\.location\.search\}\$\{next\}`\)/)
  })

  it('keeps docs outline scroll behavior off first-paint VueUse imports', () => {
    expect.soft(docsOutline).not.toContain('@vueuse/core')
    expect.soft(docsOutline).not.toContain('useEventListener')
    expect.soft(docsOutline).not.toContain('useResizeObserver')
    expect.soft(docsOutline).not.toContain('useThrottleFn')
    expect.soft(docsOutline).toContain('function createThrottleFn')
    expect.soft(docsOutline).toContain("window.addEventListener('scroll', onScroll, { passive: true })")
    expect.soft(docsOutline).toContain('new ResizeObserver')
    expect.soft(docsOutline).toContain("window.removeEventListener('scroll', onScroll)")
  })

  it('does not register VueUse as a global Nuxt module for docs first paint', () => {
    expect.soft(nuxtConfig).not.toContain("'@vueuse/nuxt'")
    expect.soft(packageJson).not.toContain('"@vueuse/nuxt"')
    expect.soft(packageJson).toContain('"@vueuse/core"')
    expect.soft(page).not.toContain('@vueuse/core')
    expect.soft(page).not.toContain('useTimeAgoIntl')
    expect.soft(page).toContain('function formatRelativeTimeFromNow(date: Date, locale: string)')
    expect.soft(page).toContain('new Intl.RelativeTimeFormat(locale, { numeric: \'auto\' })')
    expect.soft(pageView).toContain("import { useTimeAgo } from '@vueuse/core'")
    expect.soft(vortexBackground).toContain("import { templateRef, useDebounceFn } from '@vueuse/core'")
  })

  it('keeps Vue devtools API bridge modules out of docs dev first paint by default', () => {
    expect.soft(nuxtConfig).toContain('NUXT_DISABLE_VUE_DEVTOOLS_API_NOOP')
    expect.soft(nuxtConfig).toMatch(/const useVueDevtoolsApiNoop = isDev && process\.env\.NUXT_DISABLE_VUE_DEVTOOLS_API_NOOP !== 'true'/)
    expect.soft(nuxtConfig).toContain("const vueDevtoolsApiNoopEntry = resolve(currentDir, 'app/utils/vue-devtools-api-noop.ts')")
    expect.soft(nuxtConfig).toMatch(/\.\.\.\(useVueDevtoolsApiNoop \? \[\{ find: \/\^@vue\\\/devtools-api\$\/, replacement: vueDevtoolsApiNoopEntry \}\] : \[\]\)/)

    expect.soft(vueDevtoolsApiNoop).toContain('export function setupDevToolsPlugin()')
    expect.soft(vueDevtoolsApiNoop).toContain('export const setupDevtoolsPlugin = setupDevToolsPlugin')
    expect.soft(vueDevtoolsApiNoop).toContain('export function addCustomCommand()')
    expect.soft(vueDevtoolsApiNoop).toContain('export function addCustomTab()')
    expect.soft(vueDevtoolsApiNoop).not.toContain('@vue/devtools-kit')
  })

  it('keeps the PWA client plugin out of normal docs dev first paint', () => {
    expect.soft(nuxtConfig).toContain("const enablePwaModule = isProd || process.env.VITE_PLUGIN_PWA === 'true'")
    expect.soft(nuxtConfig).toMatch(/\.\.\.\(enablePwaModule \? \['@vite-pwa\/nuxt'\] : \[\]\)/)
    expect.soft(nuxtConfig).not.toMatch(/^[\s]*'@vite-pwa\/nuxt',/m)
    expect.soft(packageJson).toContain('"dev:pwa": "VITE_PLUGIN_PWA=true nuxt dev"')
    expect.soft(appRoot).toContain("import NexusPwaManifest from '~/components/NexusPwaManifest.vue'")
    expect.soft(appRoot).toContain('<NexusPwaManifest />')
    expect.soft(appRoot).not.toContain('<VitePwaManifest />')
    expect.soft(nexusPwaManifest).toContain("const shouldRenderPwaManifest = import.meta.env.PROD || import.meta.env.VITE_PLUGIN_PWA === 'true'")
    expect.soft(nexusPwaManifest).toContain("resolveComponent('VitePwaManifest')")
    expect.soft(nexusPwaManifest).not.toContain("from '@vite-pwa/nuxt")
  })

  it('requests prerenderable locale-specific component sidebar metadata', () => {
    expect.soft(docsSidebar).toMatch(/const sidebarComponentsEndpoint = computed\(\(\) => `\/api\/docs\/sidebar-components\/\$\{docsLocale\.value\}`\)/)
    expect.soft(docsSidebar).toMatch(/key: computed\(\(\) => `docs-components-meta:\$\{docsLocale\.value\}`\)/)
    expect.soft(docsSidebar).toContain('sidebarComponentsEndpoint,')
    expect.soft(docsSidebar).toContain('immediate: false')
    expect.soft(docsSidebar).toContain('COMPONENT_DOCS_METADATA_DELAY_MS = 360')
    expect.soft(docsSidebar).toContain('COMPONENT_DOCS_METADATA_INTENT_DELAY_MS = 180')
    expect.soft(docsSidebar).toContain('function requestComponentDocsMetadata()')
    expect.soft(docsSidebar).toContain('function requestComponentDocsMetadataOnIntent()')
    expect.soft(docsSidebar).toContain('function scheduleComponentDocsMetadata()')
    expect.soft(docsSidebar).toMatch(/componentDocsMetadataTimer = setTimeout\(\(\) => \{[\s\S]*requestComponentDocsMetadata\(\)[\s\S]*COMPONENT_DOCS_METADATA_INTENT_DELAY_MS/)
    expect.soft(docsSidebar).toContain('@pointerenter="requestComponentDocsMetadataOnIntent"')
    expect.soft(docsSidebar).toContain('@focusin="requestComponentDocsMetadataOnIntent"')
    expect.soft(docsSidebar).toContain('@touchstart.passive="requestComponentDocsMetadataOnIntent"')
    expect.soft(docsSidebar).toMatch(/const componentItems = computed\(\s*\(\) =>\s*coerceJsonArray<SidebarComponentDoc>\(componentDocsPayload\.value\)[\s\S]*\.filter\(\s*item => item\.locale === docsLocale\.value,?\s*\)/)
  })

  it('requests prerenderable locale and scope-specific docs navigation', () => {
    expect.soft(page).toContain("const docsNavigationScope = computed(() => (docPath.value.includes('/docs/dev/components') ? 'components' : undefined))")
    expect.soft(docsSidebar).toContain("const docsNavigationScope = computed(() => (isComponentDocsRoute.value ? 'components' : undefined))")
    expect.soft(page).toMatch(/const docsNavigationEndpoint = computed\(\(\) => `\/api\/docs\/navigation\/\$\{docsLocale\.value\}\/\$\{docsNavigationScope\.value \?\? 'all'\}`\)/)
    expect.soft(docsSidebar).toMatch(/const docsNavigationEndpoint = computed\(\s*\(\) => `\/api\/docs\/navigation\/\$\{docsLocale\.value\}\/\$\{docsNavigationScope\.value \?\? 'all'\}`,?\s*\)/)
    expect.soft(page).toMatch(/key: computed\(\(\) => `docs-navigation:\$\{docsLocale\.value\}:\$\{docsNavigationScope\.value \?\? 'all'\}`\)/)
    expect.soft(docsSidebar).toMatch(/key: computed\(\(\) => `docs-navigation:\$\{docsLocale\.value\}:\$\{docsNavigationScope\.value \?\? 'all'\}`\)/)
    expect.soft(page).toMatch(/useTypedFetch<unknown>\([\s\S]*docsNavigationEndpoint,[\s\S]*server: false,[\s\S]*lazy: true,[\s\S]*responseType: 'json'/)
    expect.soft(docsSidebar).toMatch(/useTypedFetch<unknown>\([\s\S]*docsNavigationEndpoint,[\s\S]*server: false,[\s\S]*lazy: true,[\s\S]*responseType: 'json'/)
  })

  it('warms component docs links on sidebar intent without enabling bulk NuxtLink prefetch', () => {
    expect.soft(docsSidebar).toContain("import { requestDocsPage } from '~/utils/docs-page-client-cache'")
    expect.soft(docsSidebar).toContain("import { useTypedFetch } from '~/utils/request'")
    expect.soft(docsSidebar).toContain('COMPONENT_DOCS_FULL_BODY_PREFETCH_DELAY_MS = 900')
    expect.soft(docsSidebar).toContain('COMPONENT_DOCS_FULL_BODY_PREFETCH_IDLE_TIMEOUT_MS = 2400')
    expect.soft(docsSidebar).toContain('const prefetchedDocsMetadataTargets = new Set<string>()')
    expect.soft(docsSidebar).toContain('const prefetchedDocsFullBodyTargets = new Set<string>()')
    expect.soft(docsSidebar).toContain('const pendingDocsFullBodyPrefetchTimers = new Map<string, ReturnType<typeof setTimeout>>()')
    expect.soft(docsSidebar).toContain('const pendingDocsFullBodyPrefetchIdleIds = new Map<string, number>()')
    expect.soft(docsSidebar).toMatch(/function shouldPrefetchDocsTarget\(path: string \| null \| undefined\) \{[\s\S]*normalized\?\.startsWith\('\/docs\/dev\/components\/'\)/)
    expect.soft(docsSidebar).toMatch(/function prefetchDocsMetadataTarget\(normalized: string, locale: 'en' \| 'zh'\) \{[\s\S]*prefetchedDocsMetadataTargets\.has\(cacheKey\)[\s\S]*prefetchedDocsMetadataTargets\.add\(cacheKey\)[\s\S]*void preloadRouteComponents\(routeTarget\)[\s\S]*requestDocsPage\(\{ path: normalized, locale, body: '0' \}\)/)
    expect.soft(docsSidebar).toMatch(/function scheduleDocsFullBodyPrefetch\(normalized: string, locale: 'en' \| 'zh'\) \{[\s\S]*pendingDocsFullBodyPrefetchTimers\.has\(cacheKey\)[\s\S]*const timer = setTimeout\(\(\) => \{[\s\S]*window\.requestIdleCallback\(prefetchFullDoc, \{\s*timeout: COMPONENT_DOCS_FULL_BODY_PREFETCH_IDLE_TIMEOUT_MS,?\s*\}\)[\s\S]*COMPONENT_DOCS_FULL_BODY_PREFETCH_DELAY_MS/)
    expect.soft(docsSidebar).toMatch(/function prefetchDocsTarget\(path: string \| null \| undefined\) \{[\s\S]*if \(import\.meta\.server \|\| !shouldPrefetchDocsTarget\(path\)\)[\s\S]*return/)
    expect.soft(docsSidebar).toMatch(/prefetchDocsMetadataTarget\(normalized, locale\)[\s\S]*scheduleDocsFullBodyPrefetch\(normalized, locale\)/)
    expect.soft(docsSidebar).toMatch(/function cancelDocsFullBodyPrefetch\(path: string \| null \| undefined\) \{[\s\S]*clearTimeout\(timer\)[\s\S]*window\.cancelIdleCallback\(idleId\)/)
    expect.soft(docsSidebar).toContain('@mouseenter="prefetchDocsTarget(linkTarget(child))"')
    expect.soft(docsSidebar).toContain('@mouseleave="cancelDocsFullBodyPrefetch(linkTarget(child))"')
    expect.soft(docsSidebar).toContain('@focus="prefetchDocsTarget(linkTarget(child))"')
    expect.soft(docsSidebar).toContain('@blur="cancelDocsFullBodyPrefetch(linkTarget(child))"')
    expect.soft(docsSidebar).toContain('@touchstart.passive="prefetchDocsTarget(linkTarget(child))"')
    expect.soft(docsSidebar).toContain(':prefetch="false"')
  })

  it('keeps decorative footer aurora from throwing when WebGL2 is unavailable', () => {
    expect.soft(touchAurora).toContain('let auroraDisabled = false')
    expect.soft(touchAurora).toContain("const gl = canvas.getContext('webgl2')")
    expect.soft(touchAurora).toContain('function hasAuroraWebglSupport()')
    expect.soft(touchAurora).toMatch(/if \(!hasAuroraWebglSupport\(\)\) \{[\s\S]*auroraDisabled = true[\s\S]*return[\s\S]*\}/)
    expect.soft(touchAurora).toMatch(/try \{[\s\S]*renderer = new Renderer[\s\S]*\}[\s\S]*catch \{[\s\S]*auroraDisabled = true[\s\S]*renderer = null[\s\S]*return[\s\S]*\}/)
  })

  it('keeps migrated avatar variants demos self-contained for client rendering', () => {
    expect.soft(avatarVariantsDemo).toContain("import AvatarVariantCard from './AvatarVariantCard.vue'")
    expect.soft(avatarVariantsDemo).toContain('<AvatarVariantCard')
  })

  it('caches split full-body docs on the client without deep AST reactivity', () => {
    expect.soft(page).toContain("import { cacheDocsFullBody, hasCachedDocsFullBody, isDocsPageRecordForRoute, readCachedDocsFullBody, requestDocsPage, resolveDocsFullBodyCacheKey } from '~/utils/docs-page-client-cache'")
    expect.soft(page).toContain("import { useTypedFetch } from '~/utils/request'")
    expect.soft(docsPageClientCache).toContain('DOCS_FULL_BODY_CACHE_LIMIT = 24')
    expect.soft(page).toContain('DOCS_FULL_BODY_IDLE_DELAY_MS = 180')
    expect.soft(page).toContain('DOCS_FULL_BODY_IDLE_TIMEOUT_MS = 1200')
    expect.soft(page).toContain('DOCS_PAGER_FULL_BODY_PREFETCH_DELAY_MS = 900')
    expect.soft(page).toContain('DOCS_PAGER_FULL_BODY_PREFETCH_IDLE_TIMEOUT_MS = 2400')
    expect.soft(page).toContain("DOCS_CURRENT_PAGE_FETCH_KEY_PREFIX = 'docs-current-page'")
    expect.soft(page).not.toContain('DOCS_CURRENT_FULL_BODY_FETCH_KEY')
    expect.soft(docsPageClientCache).toContain('const docsFullBodyCache = new Map<string, DocsPageRecord>()')
    expect.soft(page).toContain('const shouldRequestMetadataOnlyDocBody = computed(() => shouldSplitDocBody.value)')
    expect.soft(page).toContain("const currentDocsPageBodyMode = computed(() => (shouldRequestMetadataOnlyDocBody.value ? '0' : '1'))")
    expect.soft(page).toMatch(/const currentDocsPageFetchKey = computed\(\(\) => `\$\{DOCS_CURRENT_PAGE_FETCH_KEY_PREFIX\}:\$\{docPath\.value\}:\$\{docsLocale\.value\}:\$\{currentDocsPageBodyMode\.value\}`\)/)
    // The rendered-body cache lives at module scope in the util, so it survives the
    // page remount that every docs navigation performs.
    expect.soft(page).not.toContain('const docsFullBodyCache = new Map')
    expect.soft(docsPageClientCache).toContain('const docsFullBodyCache = new Map<string, DocsPageRecord>()')
    expect.soft(docsPageClientCache).toContain('export function resolveDocsFullBodyCacheKey(path: string, locale: DocsPageLocale)')
    expect.soft(docsPageClientCache).toContain('export function readCachedDocsFullBody(cacheKey: string)')
    expect.soft(docsPageClientCache).toContain('export function hasCachedDocsFullBody(cacheKey: string)')
    expect.soft(docsPageClientCache).toContain('export function cacheDocsFullBody(value: DocsPageRecord)')
    expect.soft(docsPageClientCache).toMatch(/return `doc-full:\$\{normalizeDocsPagePath\(path\)\}:\$\{locale\}`/)
    expect.soft(docsPageClientCache).toContain('while (docsFullBodyCache.size > DOCS_FULL_BODY_CACHE_LIMIT)')
    expect.soft(page).toMatch(/const fullDocCacheKey = computed\(\(\) => resolveDocsFullBodyCacheKey\(docPath\.value, docsLocale\.value\)\)/)
    // The page owns its document locally: Nuxt seeds a newly keyed asyncData entry
    // with the previous key's data, and the outgoing page instance must not be able
    // to write into the incoming one.
    expect.soft(page).toContain('const { data: docPayload, status } = await useTypedFetch<Record<string, any> | null>(')
    expect.soft(docsPageClientCache).toContain('export function isDocsPageRecordForRoute(')
    expect.soft(page).toMatch(/const doc = shallowRef<Record<string, any> \| null>\([\s\S]*isDocsPageRecordForRoute\(docPayload\.value, docPath\.value, docsLocale\.value\)/)
    expect.soft(page).toContain('const fullDoc = shallowRef<Record<string, any> | null>(null)')
    expect.soft(page).toContain('const fullDocLoading = ref(false)')
    expect.soft(page).toContain('key: currentDocsPageFetchKey')
    expect.soft(page).toMatch(/key: currentDocsPageFetchKey,[\s\S]*immediate: import\.meta\.server \|\| !shouldSplitDocBody\.value,[\s\S]*watch: false/)
    expect.soft(page).toContain('body: currentDocsPageBodyMode.value')
    expect.soft(page).toContain("const currentDocsPageBodyMode = computed(() => (shouldRequestMetadataOnlyDocBody.value ? '0' : '1'))")
    expect.soft(page).not.toContain('key: DOCS_CURRENT_PAGE_FETCH_KEY')
    expect.soft(page).toMatch(/const renderDoc = computed\(\(\) => \(shouldSplitDocBody\.value \? fullDoc\.value \?\? doc\.value : doc\.value\)\)/)
    expect.soft(page).toContain('let activeDocFetchId = 0')
    expect.soft(page).toContain('let fullDocIdleId: number | null = null')
    expect.soft(page).toContain('let fullDocTimer: ReturnType<typeof setTimeout> | null = null')
    expect.soft(page).toContain('function clearFullDocFetchSchedule()')
    expect.soft(page).toMatch(/if \(fullDocIdleId !== null && 'cancelIdleCallback' in window\) \{[\s\S]*window\.cancelIdleCallback\(fullDocIdleId\)[\s\S]*fullDocIdleId = null/)
    expect.soft(page).toMatch(/if \(fullDocTimer\) \{[\s\S]*clearTimeout\(fullDocTimer\)[\s\S]*fullDocTimer = null/)
    expect.soft(page).toContain('async function loadFullDocForRoute(fetchId: number, path: string, locale: \'en\' | \'zh\')')
    expect.soft(page).toMatch(/const cacheKey = resolveDocsFullBodyCacheKey\(path, locale\)[\s\S]*if \(hasCachedDocsFullBody\(cacheKey\)\) \{[\s\S]*settleFullDoc\(readCachedDocsFullBody\(cacheKey\) \?\? null\)/)
    expect.soft(page).toMatch(/fullDocLoading\.value = true[\s\S]*requestDocsPage\(\{ path, locale, body: '1' \}\)/)
    expect.soft(page).toMatch(/settleFullDoc\(cacheDocsFullBody\(nextFullDoc\)\)/)
    // Every exit from the body fetch resolves the view — a spinner must never outlive
    // the data that would replace it.
    expect.soft(page).toContain('function settleFullDoc(value: Record<string, any> | null)')
    expect.soft(page).toMatch(/finally \{[\s\S]*if \(!isStaleDocFetch\(fetchId, path, locale\)\) \{[\s\S]*fullDocLoading\.value = false[\s\S]*isLoading\.value = false[\s\S]*\}/)
    expect.soft(page).toMatch(/const viewState = computed\(\(\) => \{[\s\S]*if \(doc\.value \|\| renderDoc\.value\)[\s\S]*return 'content'[\s\S]*if \(isLoading\.value\)[\s\S]*return 'loading'/)
    // The incoming instance drives its own load; the outgoing one no longer can.
    expect.soft(page).toMatch(/if \(import\.meta\.client\)\s*\n\s*void loadActiveDocForRoute\(\)/)
    expect.soft(page).toContain('function seedFullDocFromCurrentDoc()')
    expect.soft(page).toMatch(/function seedFullDocFromCurrentDoc\(\) \{[\s\S]*if \(!shouldSplitDocBody\.value \|\| !doc\.value\?\.body\)[\s\S]*return false[\s\S]*settleFullDoc\(cacheDocsFullBody\(doc\.value as Record<string, any>\)\)[\s\S]*return true[\s\S]*\}/)
    expect.soft(page).toContain('function scheduleFullDocFetchForRoute(fetchId: number, path: string, locale: \'en\' | \'zh\')')
    expect.soft(page).toMatch(/function scheduleFullDocFetchForRoute\(fetchId: number, path: string, locale: 'en' \| 'zh'\) \{[\s\S]*clearFullDocFetchSchedule\(\)[\s\S]*const load = \(\) => \{[\s\S]*if \(isStaleDocFetch\(fetchId, path, locale\)\)[\s\S]*return[\s\S]*void loadFullDocForRoute\(fetchId, path, locale\)/)
    expect.soft(page).toMatch(/fullDocTimer = setTimeout\(\(\) => \{[\s\S]*window\.requestIdleCallback\(load, \{ timeout: DOCS_FULL_BODY_IDLE_TIMEOUT_MS \}\)[\s\S]*load\(\)[\s\S]*DOCS_FULL_BODY_IDLE_DELAY_MS/)
    expect.soft(page).toContain('function startFullDocFetchForRoute()')
    expect.soft(page).toMatch(/function startFullDocFetchForRoute\(\) \{[\s\S]*if \(seedFullDocFromCurrentDoc\(\)\)[\s\S]*return[\s\S]*const fetchId = \+\+activeDocFetchId[\s\S]*scheduleFullDocFetchForRoute\(fetchId, docPath\.value, docsLocale\.value\)[\s\S]*\}/)
    expect.soft(page).toContain('async function loadActiveDocForRoute()')
    expect.soft(page).toMatch(/const fetchId = \+\+activeDocFetchId[\s\S]*const path = docPath\.value[\s\S]*const locale = docsLocale\.value/)
    // A cached rendered body short-circuits straight to content; otherwise a document
    // already resolved for this route stays on screen instead of flashing a spinner.
    expect.soft(page).toMatch(/const cachedFullDoc = splitBody \? readCachedDocsFullBody\(fullDocCacheKey\.value\) : undefined[\s\S]*if \(cachedFullDoc !== undefined\) \{[\s\S]*settleFullDoc\(cachedFullDoc\)[\s\S]*return/)
    expect.soft(page).toContain('const hasResolvedDoc = isDocsPageRecordForRoute(doc.value, path, locale)')
    expect.soft(page).toMatch(/if \(!hasResolvedDoc\) \{[\s\S]*doc\.value = null[\s\S]*fullDoc\.value = null[\s\S]*\}[\s\S]*isLoading\.value = !hasResolvedDoc/)
    expect.soft(page).toMatch(/try \{[\s\S]*requestDocsPage\(\{ path, locale, body: splitBody \? '0' : '1' \}\)/)
    expect.soft(page).toMatch(/function isStaleDocFetch\(fetchId: number, path: string, locale: 'en' \| 'zh'\) \{[\s\S]*return fetchId !== activeDocFetchId \|\| path !== docPath\.value \|\| locale !== docsLocale\.value/)
    expect.soft(page).not.toContain('const fullDocRequest = splitBody && !hasCachedBody')
    expect.soft(page).not.toContain('void fullDocRequest')
    expect.soft(page).toMatch(/if \(!splitBody \|\| seedFullDocFromCurrentDoc\(\)\)[\s\S]*return[\s\S]*scheduleFullDocFetchForRoute\(fetchId, path, locale\)/)
    expect.soft(page).toMatch(/catch \{[\s\S]*fullDocLoading\.value = false[\s\S]*clearFullDocFetchSchedule\(\)/)
    expect.soft(page).toMatch(/watch\(requestKey, \(\) => \{[\s\S]*void loadActiveDocForRoute\(\)[\s\S]*\}\)/)
    expect.soft(page).toMatch(/onMounted\(\(\) => \{[\s\S]*startFullDocFetchForRoute\(\)[\s\S]*\}\)/)
    expect.soft(page).toMatch(/onBeforeUnmount\(\(\) => \{[\s\S]*clearFullDocFetchSchedule\(\)/)
    expect.soft(page).toMatch(/return `\$\{path\}:\$\{docsLocale\.value\}:\$\{source\?\.body \? 'body' : 'meta'\}`/)
    expect.soft(page).not.toContain('shouldClientRenderDocBody')
    expect.soft(page).not.toContain('<ClientOnly v-if="shouldClientRenderDocBody">')
    expect.soft(page).toMatch(/<template v-if="renderDoc\?\.body">[\s\S]*<ContentRenderer[\s\S]*:value="primaryRenderDoc \?\? \{\}"/)
    expect.soft(page).toContain('const deferredBodySplitIndex = computed(() => resolveDeferredBodySplitIndex(renderDoc.value?.body))')
    expect.soft(page).toContain('const isDocPerformancePending = computed(() => {')
    expect.soft(page).toMatch(/const isDocPerformancePending = computed\(\(\) => \{[\s\S]*docMeta\.value\.syncStatus\.trim\(\)\.toLowerCase\(\)[\s\S]*hasReviewedSyncStatus = raw === 'reviewed' \|\| normalizedSyncStatus === 'verified'[\s\S]*return !hasReviewedSyncStatus \|\| !isDocVerified\.value[\s\S]*\}/)
    expect.soft(page).not.toMatch(/shouldDeferDocBodySections[\s\S]*docSyncStatus\.value !== 'verified'/)
    expect.soft(page).toMatch(/const shouldDeferDocBodySections = computed\(\(\) =>[\s\S]*import\.meta\.dev[\s\S]*import\.meta\.client[\s\S]*docScope\.value\.isComponent[\s\S]*isDocPerformancePending\.value[\s\S]*deferredBodySplitIndex\.value > 0/)
    expect.soft(page).toContain('const primaryRenderDoc = computed(() => {')
    expect.soft(page).toContain('const deferredRenderDoc = computed(() => {')
    expect.soft(page).toContain('function readBodyNodeTag(node: unknown)')
    expect.soft(page).toContain('function isDeferredBoundaryNode(node: unknown)')
    expect.soft(page).toContain("tag === 'tuff-demo-wrapper'")
    expect.soft(page).toContain("tag === 'tuff-props-table'")
    expect.soft(page).toMatch(/function resolveDeferredBodySplitIndex\(body: unknown\) \{[\s\S]*let secondH2SplitIndex = -1[\s\S]*h2Count === 2[\s\S]*secondH2SplitIndex = index[\s\S]*let deferredBoundaryCount = 0[\s\S]*deferredBoundaryCount < 2 && secondH2SplitIndex > 0[\s\S]*return Math\.min\(secondH2SplitIndex, boundarySplitIndex\)[\s\S]*return secondH2SplitIndex/)
    expect.soft(page).toContain('let secondH2SplitIndex = -1')
    expect.soft(page).toContain('let deferredBoundaryCount = 0')
    expect.soft(page).toContain('if (deferredBoundaryCount < 2 && secondH2SplitIndex > 0)')
    expect.soft(page).toContain('return Math.min(secondH2SplitIndex, boundarySplitIndex)')
    expect.soft(page).toContain('if (Array.isArray(record.value))')
    expect.soft(page).toContain('if (Array.isArray(node))')
    expect.soft(page).toContain('return node[0] === tag')
    expect.soft(page).toContain("Array.isArray(body.value)")
    expect.soft(page).toContain('[childKey]: children')
    expect.soft(page).toContain('function scheduleDeferredDocBodySections()')
    expect.soft(page).toContain('DOCS_DEFERRED_BODY_IDLE_TIMEOUT_MS = 3200')
    expect.soft(page).toContain("DOCS_DEFERRED_BODY_INTENT_EVENTS = ['scroll', 'wheel', 'keydown', 'touchstart'] as const")
    expect.soft(page).toContain('function bindDeferredDocBodyIntentListeners()')
    expect.soft(page).toContain('function handleDeferredDocBodyIntent()')
    expect.soft(page).toMatch(/window\.addEventListener\(eventName, handleDeferredDocBodyIntent, \{ passive: true \}\)/)
    expect.soft(page).toMatch(/setTimeout\(\(\) => \{[\s\S]*mountDeferredDocBodySections\(\)[\s\S]*\}, DOCS_DEFERRED_BODY_IDLE_TIMEOUT_MS\)/)
    expect.soft(page).toMatch(/watch\([\s\S]*\(\) => route\.hash,[\s\S]*revealDeferredDocBodyForHash\(hash\)/)
    expect.soft(page).toContain('ref="deferredDocBodySentinelRef"')
    expect.soft(page).toContain('class="docs-deferred-body-shell"')
    expect.soft(page).toMatch(/<ContentRenderer[\s\S]*v-if="shouldRenderDeferredDocBody && deferredRenderDoc\?\.body"[\s\S]*:value="deferredRenderDoc \?\? \{\}"/)
    expect.soft(page).toContain(':prose="false"')
    expect.soft(page).toContain(':components="docsProseComponents"')
    expect.soft(page).toContain("import DocsProseHeading from '~/components/docs/DocsProseHeading.vue'")
    expect.soft(page).toContain("function createDocsProseHeading(tag: 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6')")
    expect.soft(page).toContain("h1: createDocsProseHeading('h1')")
    expect.soft(page).toContain("h6: createDocsProseHeading('h6')")
    expect.soft(docsProseHeading).toContain('<component :is="props.tag"')
    expect.soft(docsProseHeading).toContain(':href="`#${props.id')
    expect.soft(page).not.toContain('proseComponentMap')
  })

  it('keeps default MDC prose wrappers out of content renderer routes', () => {
    expect.soft(nuxtConfig).toContain("'/@nuxtjs/mdc/dist/runtime/components/prose/'")
    expect.soft(nuxtConfig).toContain("'/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/'")

    for (const contentPage of [page, licensePage, privacyPage, protocolPage]) {
      expect.soft(contentPage).toContain('<ContentRenderer')
      expect.soft(contentPage).toContain(':prose="false"')
    }
  })

  it('keeps dev fallback metadata requests off full Markdown body parsing', () => {
    expect.soft(docsPageApi).toContain('function parseFrontmatterMetadata(raw: string)')
    expect.soft(docsPageApi).toContain('async function readDevDocsPageFromFile(contentPath: string, includeBody: boolean)')
    expect.soft(docsPageApi).toContain('function shouldPreferDevDocsMetadataFileLookup(docPath: string, includeBody: boolean)')
    expect.soft(docsPageApi).toMatch(/function shouldPreferDevDocsMetadataFileLookup\(docPath: string, includeBody: boolean\) \{[\s\S]*return process\.env\.NODE_ENV === 'development' && !includeBody && docPath\.includes\('\/docs\/dev\/components'\)[\s\S]*\}/)
    expect.soft(docsPageApi).toMatch(/if \(shouldPreferDevDocsMetadataFileLookup\(docPath, includeBody\)\) \{[\s\S]*readDevDocsPageFallback\(lookupPaths, includeBody\)[\s\S]*return serializeDoc\(fallbackDoc, includeBody\)[\s\S]*\}/)
    expect.soft(docsPageApi).toMatch(/if \(!includeBody\) \{[\s\S]*parseFrontmatterMetadata\(raw\)[\s\S]*metaDoc = doc[\s\S]*return doc[\s\S]*\}/)
    expect.soft(docsPageApi).toMatch(/const \{ parseMarkdown \} = await import\('@nuxtjs\/mdc\/runtime'\)/)
    expect.soft(docsPageApi).not.toContain("import('@nuxtjs/mdc/runtime'),")
    expect.soft(docsPageApi).toContain('fullDoc?: DocsPageRecord')
    expect.soft(docsPageApi).toContain('metaDoc?: DocsPageRecord')
  })

  it('warms pager docs targets with cancelable full-body prefetch on sustained user intent', () => {
    expect.soft(page).toContain('const prefetchedDocMetadataTargets = new Set<string>()')
    expect.soft(page).toContain('const prefetchedDocFullBodyTargets = new Set<string>()')
    expect.soft(page).toContain('const pendingPagerFullBodyPrefetchTimers = new Map<string, ReturnType<typeof setTimeout>>()')
    expect.soft(page).toContain('const pendingPagerFullBodyPrefetchIdleIds = new Map<string, number>()')
    expect.soft(page).toContain('function prefetchDocMetadataForTarget(normalized: string, locale: \'en\' | \'zh\')')
    expect.soft(page).toMatch(/function prefetchDocMetadataForTarget\(normalized: string, locale: 'en' \| 'zh'\) \{[\s\S]*prefetchedDocMetadataTargets\.has\(prefetchKey\)[\s\S]*prefetchedDocMetadataTargets\.add\(prefetchKey\)[\s\S]*void preloadRouteComponents\(toLocalizedDocsPath\(normalized, locale\)\)[\s\S]*requestDocsPage\(\{ path: normalized, locale, body: '0' \}\)/)
    expect.soft(page).toContain('function clearPagerFullBodyPrefetchSchedule(prefetchKey: string)')
    expect.soft(page).toMatch(/function clearPagerFullBodyPrefetchSchedule\(prefetchKey: string\) \{[\s\S]*clearTimeout\(timer\)[\s\S]*window\.cancelIdleCallback\(idleId\)/)
    expect.soft(page).toContain('function clearPagerFullBodyPrefetchSchedules()')
    expect.soft(page).toContain('function schedulePagerFullDocPrefetch(normalized: string, locale: \'en\' | \'zh\')')
    expect.soft(page).toMatch(/function schedulePagerFullDocPrefetch\(normalized: string, locale: 'en' \| 'zh'\) \{[\s\S]*hasCachedDocsFullBody\(cacheKey\)[\s\S]*pendingPagerFullBodyPrefetchTimers\.has\(prefetchKey\)[\s\S]*const timer = setTimeout\(\(\) => \{[\s\S]*window\.requestIdleCallback\(prefetchFullDoc, \{ timeout: DOCS_PAGER_FULL_BODY_PREFETCH_IDLE_TIMEOUT_MS \}\)[\s\S]*DOCS_PAGER_FULL_BODY_PREFETCH_DELAY_MS/)
    expect.soft(page).toContain('function prefetchDocForPath(path: string | null | undefined)')
    expect.soft(page).toMatch(/prefetchDocMetadataForTarget\(normalized, locale\)[\s\S]*schedulePagerFullDocPrefetch\(normalized, locale\)/)
    expect.soft(page).toContain('function cancelPrefetchDocForPath(path: string | null | undefined)')
    expect.soft(page).toMatch(/function cancelPrefetchDocForPath\(path: string \| null \| undefined\) \{[\s\S]*clearPagerFullBodyPrefetchSchedule\(`\$\{normalized\}:\$\{docsLocale\.value\}`\)/)
    expect.soft(page).toMatch(/watch\(requestKey, \(\) => \{[\s\S]*clearPagerFullBodyPrefetchSchedules\(\)/)
    expect.soft(page).toMatch(/onBeforeUnmount\(\(\) => \{[\s\S]*clearPagerFullBodyPrefetchSchedules\(\)/)
    expect.soft(page).toContain('@mouseenter="prefetchDocForPath(pagerPrevPath)"')
    expect.soft(page).toContain('@mouseleave="cancelPrefetchDocForPath(pagerPrevPath)"')
    expect.soft(page).toContain('@focus="prefetchDocForPath(pagerPrevPath)"')
    expect.soft(page).toContain('@blur="cancelPrefetchDocForPath(pagerPrevPath)"')
    expect.soft(page).toContain('@touchstart.passive="prefetchDocForPath(pagerPrevPath)"')
    expect.soft(page).toContain('@mouseenter="prefetchDocForPath(pagerNextPath)"')
    expect.soft(page).toContain('@mouseleave="cancelPrefetchDocForPath(pagerNextPath)"')
    expect.soft(page).toContain('@focus="prefetchDocForPath(pagerNextPath)"')
    expect.soft(page).toContain('@blur="cancelPrefetchDocForPath(pagerNextPath)"')
    expect.soft(page).toContain('@touchstart.passive="prefetchDocForPath(pagerNextPath)"')
  })

  it('dedupes docs page client requests shared by sidebar prefetch and route loads', () => {
    expect.soft(docsPageClientCache).toContain('const docsPageRequestPending = new Map<string, Promise<DocsPageRecord>>()')
    expect.soft(docsPageClientCache).toContain('const docsPageRequestCache = new Map<string, DocsPageRequestCacheEntry>()')
    expect.soft(docsPageClientCache).toContain('DOCS_PAGE_REQUEST_CACHE_TTL_MS = 30_000')
    expect.soft(docsPageClientCache).toContain('export function resolveDocsPageRequestCacheKey')
    expect.soft(docsPageClientCache).toContain('export function primeDocsPageRequestCache')
    expect.soft(docsPageClientCache).toContain('export function requestDocsPage')
    expect.soft(docsPageClientCache).toMatch(/const pending = docsPageRequestPending\.get\(cacheKey\)[\s\S]*if \(pending\)[\s\S]*return pending/)
    expect.soft(docsPageClientCache).toMatch(/requestJson<DocsPageRecord>\('\/api\/docs\/page'[\s\S]*path,[\s\S]*locale,[\s\S]*body/)
    expect.soft(docsPageClientCache).toMatch(/docsPageRequestPending\.set\(cacheKey, request\)/)
    // Caching a rendered body also primes the request cache, so a later body=1 fetch
    // for the same page is a cache hit rather than a second round trip.
    expect.soft(docsPageClientCache).toContain('primeDocsPageRequestCache({ path, locale: locale as DocsPageLocale, body: \'1\' }, value)')
    expect.soft(page).toContain("requestDocsPage({ path, locale, body: '1' })")
    expect.soft(docsSidebar).toContain("requestDocsPage({ path: normalized, locale, body: '1' })")
    expect.soft(docsSidebar).toMatch(/const prefetchFullDoc = \(\) => \{[\s\S]*void requestDocsPage\(\{ path: normalized, locale, body: '1' \}\)/)
    expect.soft(docsSidebar).not.toMatch(/void requestDocsPage\(\{ path: normalized, locale, body: '0' \}\)\.catch\(\(\) => \{\}\)\n\s*void requestDocsPage\(\{ path: normalized, locale, body: '1' \}\)/)
  })
})
