import { readFileSync } from 'node:fs'
import { describe, expect, it } from 'vitest'

describe('dashboard data governance UI contract', () => {
  it('exposes notification channel test controls wired to the admin test API', () => {
    const page = readFileSync(new URL('./governance.vue', import.meta.url), 'utf8')

    expect(page).toContain("requestJson<NotificationChannelTestResponse>('/api/dashboard/notifications/channels/test'")
    expect(page).toContain("testNotificationChannel('plan')")
    expect(page).toContain("testNotificationChannel('send')")
    expect(page).toContain('notificationTestForm.configId')
    expect(page).toContain('notificationTestResult.deliveries')
    expect(page).toContain('dashboard.governance.notificationTest.dryRun')
    expect(page).toContain('dashboard.governance.notificationTest.send')
  })

  it('exposes granular anonymized search context analytics', () => {
    const page = readFileSync(new URL('./governance.vue', import.meta.url), 'utf8')

    expect(page).toContain('analyticsData.searches.byLocalHour')
    expect(page).toContain('analyticsData.searches.byLocalDayOfWeek')
    expect(page).toContain('analyticsData.searches.byLocalTimeSlot')
    expect(page).toContain('analyticsData.searches.byContextAppCategory')
    expect(page).toContain('analyticsData.searches.byTriggerType')
    expect(page).toContain('analyticsData.searches.byUserPreferenceMode')
    expect(page).toContain('analyticsData.searches.byPluginId')
    expect(page).toContain('analyticsData.searches.byPluginCategory')
    expect(page).toContain('analyticsData.searches.bySelectedProvider')
    expect(page).toContain('analyticsData.searches.bySelectedCategory')
    expect(page).toContain('analyticsData.searches.bySelectedPluginId')
    expect(page).toContain('analyticsData.searches.bySelectedRankBucket')
    expect(page).toContain('analyticsData.searches.byResultCountBucket')
    expect(page).toContain('analyticsData.searches.byFirstResultLatencyBucket')
    expect(page).toContain('analyticsData.searches.byTotalDurationBucket')
    expect(page).toContain('selectionSummary: {')
    expect(page).toContain('analyticsData.searches.selectionSummary.selectionRate')
    expect(page).toContain('reliabilitySummary: {')
    expect(page).toContain('analyticsData.searches.reliabilitySummary.zeroResultRate')
    expect(page).toContain('analyticsData.searches.reliabilitySummary.problemRate')
    expect(page).toContain('analyticsData.searches.reliabilityTrend')
    expect(page).toContain('dashboard.governance.analytics.searchPreference')
    expect(page).toContain('dashboard.governance.analytics.searchLocalTimeSlot')
    expect(page).toContain('dashboard.governance.analytics.searchLocalWeekday')
    expect(page).toContain('dashboard.governance.analytics.searchZeroResultRate')
    expect(page).toContain('dashboard.governance.analytics.searchProblemRate')
    expect(page).toContain('dashboard.governance.analytics.searchSelectionRate')
    expect(page).toContain('dashboard.governance.analytics.searchSelectedRank')
    expect(page).toContain('dashboard.governance.analytics.searchResultBuckets')
    expect(page).toContain('dashboard.governance.analytics.searchFirstResultLatency')
    expect(page).toContain('dashboard.governance.analytics.searchTotalDuration')
    expect(page).toContain('dashboard.governance.analytics.searchSelectedProvider')
    expect(page).toContain('dashboard.governance.analytics.searchSelectedCategory')
    expect(page).toContain('dashboard.governance.analytics.searchSelectedPlugin')
  })

  it('exposes hot plugin leaderboard score and action mix', () => {
    const page = readFileSync(new URL('./governance.vue', import.meta.url), 'utf8')

    expect(page).toContain('hotScore: number')
    expect(page).toContain('growthRate: number')
    expect(page).toContain('formatNumber(item.hotScore)')
    expect(page).toContain('formatDelta(item.growth.growthRate)')
    expect(page).toContain('item.byAction.slice(0, 3)')
    expect(page).toContain('formatNumber(action.quantity)')
  })

  it('exposes user signup growth amount and growth-rate trend', () => {
    const page = readFileSync(new URL('./governance.vue', import.meta.url), 'utf8')

    expect(page).toContain('interface GovernanceGrowthTrendPoint')
    expect(page).toContain('signupGrowthTrend: GovernanceGrowthTrendPoint[]')
    expect(page).toContain('analyticsData.users.signupGrowthTrend')
    expect(page).toContain('formatNumber(item.cumulative)')
    expect(page).toContain('formatDelta(item.growthRate)')
    expect(page).toContain('dashboard.governance.analytics.userGrowthTrend')
    expect(page).toContain('dashboard.governance.analytics.userGrowthTotal')
  })

  it('exposes operations dashboard summary for growth, risks, leaderboards, tokens, and models', () => {
    const page = readFileSync(new URL('./governance.vue', import.meta.url), 'utf8')

    expect(page).toContain('dashboard: {')
    expect(page).toContain('leaderboards: {')
    expect(page).toContain('riskSummary: {')
    expect(page).toContain('const dashboardRiskTotal = computed')
    expect(page).toContain('analyticsData.dashboard.growth.userSignups')
    expect(page).toContain('analyticsData.dashboard.growth.searches')
    expect(page).toContain('analyticsData.dashboard.growth.pluginInstalls')
    expect(page).toContain('analyticsData.dashboard.growth.providerUsage.tokens')
    expect(page).toContain('analyticsData.dashboard.growth.uploads.failureRate')
    expect(page).toContain('analyticsData.dashboard.leaderboards.hotPlugins')
    expect(page).toContain('analyticsData.dashboard.leaderboards.topModels')
    expect(page).toContain('dashboard.governance.analytics.operationsDashboard')
    expect(page).toContain('dashboard.governance.analytics.dashboardHotPlugins')
    expect(page).toContain('dashboard.governance.analytics.dashboardModelDistribution')
  })

  it('exposes anonymized app visit hotspots and visit trend', () => {
    const page = readFileSync(new URL('./governance.vue', import.meta.url), 'utf8')

    expect(page).toContain('byRoute: GovernanceMetric[]')
    expect(page).toContain('bySurface: GovernanceMetric[]')
    expect(page).toContain('byLocalTimeSlot: GovernanceMetric[]')
    expect(page).toContain('analyticsData.visits.byRoute')
    expect(page).toContain('analyticsData.visits.bySurface')
    expect(page).toContain('analyticsData.visits.byLocalTimeSlot')
    expect(page).toContain('analyticsData.visits.trend')
    expect(page).toContain('dashboard.governance.analytics.visitHotspot')
    expect(page).toContain('dashboard.governance.analytics.visitRoute')
    expect(page).toContain('dashboard.governance.analytics.visitLocalTimeSlot')
  })

  it('exposes upload reliability diagnostics for stuck attempts and failures', () => {
    const page = readFileSync(new URL('./governance.vue', import.meta.url), 'utf8')

    expect(page).toContain('analyticsData.uploads.stuckAttempts')
    expect(page).toContain('analyticsData.uploads.stuckAttemptAgeMs')
    expect(page).toContain('analyticsData.uploads.stuckRate')
    expect(page).toContain('analyticsData.uploads.uploadDurationMs.average')
    expect(page).toContain('formatDurationMs(analyticsData.uploads.uploadDurationMs.average)')
    expect(page).toContain('analyticsData.uploads.byStatusCode')
    expect(page).toContain('analyticsData.uploads.bySurface')
    expect(page).toContain('analyticsData.uploads.byStorageProvider')
    expect(page).toContain('analyticsData.uploads.statusTrend')
    expect(page).toContain('analyticsData.uploads.retrySummary.retryableFailures')
    expect(page).toContain('analyticsData.uploads.retrySummary.scheduledRetries')
    expect(page).toContain('analyticsData.uploads.retrySummary.exhaustedFailures')
    expect(page).toContain('analyticsData.uploads.retrySummary.nextRetryDelayMs.average')
    expect(page).toContain('analyticsData.uploads.byRetryDisposition')
    expect(page).toContain('analyticsData.uploads.retryTrend')
    expect(page).toContain('analyticsData.uploads.problemAttempts')
    expect(page).toContain('attempt.attemptHash')
    expect(page).toContain('attempt.resourceType')
    expect(page).toContain('attempt.retryable')
    expect(page).toContain('attempt.nextRetryDelayMs')
    expect(page).toContain('dashboard.governance.analytics.uploadRetryableFailures')
    expect(page).toContain('dashboard.governance.analytics.uploadRetryDisposition')
    expect(page).toContain('dashboard.governance.analytics.uploadRetryState')
    expect(page).toContain('dashboard.governance.analytics.uploadStuckAttempts')
    expect(page).toContain('dashboard.governance.analytics.uploadProblemAttempts')
  })

  it('exposes browser push subscription analytics in the notification cockpit', () => {
    const page = readFileSync(new URL('./governance.vue', import.meta.url), 'utf8')

    expect(page).toContain('browserPushSubscriptions: {')
    expect(page).toContain('analyticsData.notifications.browserPushSubscriptions.total')
    expect(page).toContain('analyticsData.notifications.browserPushSubscriptions.registered')
    expect(page).toContain('analyticsData.notifications.browserPushSubscriptions.deleted')
    expect(page).toContain('analyticsData.notifications.browserPushSubscriptions.byEndpointHost')
    expect(page).toContain('analyticsData.notifications.browserPushSubscriptions.byAction')
    expect(page).toContain('dashboard.governance.analytics.browserPushSubscriptions')
  })

  it('exposes per-provider notification delivery health and latest failure reason', () => {
    const page = readFileSync(new URL('./governance.vue', import.meta.url), 'utf8')

    expect(page).toContain('channelSummary: {')
    expect(page).toContain('channelRisks: Array<{')
    expect(page).toContain('analyticsData.notifications.channelSummary.enabled')
    expect(page).toContain('analyticsData.notifications.channelSummary.credentialMissing')
    expect(page).toContain('analyticsData.notifications.channelRisks')
    expect(page).toContain('notificationChannelLabel(channel.status)')
    expect(page).toContain('notificationChannelCredentialLabel(channel)')
    expect(page).toContain('notificationChannelCredentialMissing')
    expect(page).toContain('notificationChannelCredentialBound')
    expect(page).toContain('providerHealth: Array<{')
    expect(page).toContain('deliveryTrend: Array<GovernanceTrendPoint')
    expect(page).toContain('analyticsData.notifications.deliveryTrend')
    expect(page).toContain('analyticsData.notifications.providerHealth')
    expect(page).toContain('dashboard.governance.analytics.notificationProviderHealth')
    expect(page).toContain('formatPercent(item.sentRate)')
    expect(page).toContain('formatPercent(item.failureRate)')
    expect(page).toContain('item.latestFailureReason')
  })

  it('exposes storage policy alerts for storage limit and traffic risk', () => {
    const page = readFileSync(new URL('./governance.vue', import.meta.url), 'utf8')

    expect(page).toContain('interface StoragePolicyAlert')
    expect(page).toContain('alerts: StoragePolicyAlert[]')
    expect(page).toContain('limitKey: StorageAlertLimitKey')
    expect(page).toContain('const derivedStoragePolicyAlerts = computed<StoragePolicyAlert[]>')
    expect(page).toContain('const storagePolicyAlerts = computed(() => storagePoliciesData.value?.alerts')
    expect(page).toContain("metric: 'storedBytes'")
    expect(page).toContain("metric: 'trafficBytes'")
    expect(page).toContain("metric: 'operations'")
    expect(page).toContain('dashboard.governance.storageAlerts.title')
    expect(page).toContain('storagePolicyAlerts.some(item => item.status ===')
    expect(page).toContain('formatStorageAlertValue(alert, alert.usage)')
  })

  it('exposes storage alert notification controls', () => {
    const page = readFileSync(new URL('./governance.vue', import.meta.url), 'utf8')

    expect(page).toContain("requestJson<StorageAlertNotifyResponse>('/api/dashboard/storage/alerts/notify'")
    expect(page).toContain("notifyStorageAlerts('plan')")
    expect(page).toContain("notifyStorageAlerts('send')")
    expect(page).toContain('storageAlertNotifyResult.dispatches')
    expect(page).toContain('dashboard.governance.storageAlerts.dryRun')
    expect(page).toContain('dashboard.governance.storageAlerts.send')
  })

  it('exposes storage channel usage analytics for traffic and capacity planning', () => {
    const page = readFileSync(new URL('./governance.vue', import.meta.url), 'utf8')

    expect(page).toContain('interface StorageUsageBreakdown')
    expect(page).toContain('analyticsData.storage.storedBytes')
    expect(page).toContain('analyticsData.storage.trafficBytes')
    expect(page).toContain('analyticsData.storage.operations')
    expect(page).toContain('analyticsData.storage.byChannelUsage')
    expect(page).toContain('analyticsData.storage.byProviderUsage')
    expect(page).toContain('analyticsData.storage.byResourceTypeUsage')
    expect(page).toContain('analyticsData.storage.byActionUsage')
    expect(page).toContain('analyticsData.storage.trend')
    expect(page).toContain('policySummary: {')
    expect(page).toContain('analyticsData.storage.policySummary.active')
    expect(page).toContain('analyticsData.storage.policySummary.blocked')
    expect(page).toContain('analyticsData.storage.policySummary.warning')
    expect(page).toContain('storagePolicyPeakUtilization')
    expect(page).toContain('analyticsData.storage.policyRisks')
    expect(page).toContain('storageEvaluationLabel(policy.status)')
    expect(page).toContain('formatRatio(policy.utilization.storedBytes)')
    expect(page).toContain('remaining: {')
    expect(page).toContain('overage: {')
    expect(page).toContain('policy.remaining.storedBytes')
    expect(page).toContain('policy.remaining.trafficBytes')
    expect(page).toContain('policy.remaining.operations')
    expect(page).toContain('item.remaining.storedBytes')
    expect(page).toContain('item.overage.alertBytes')
    expect(page).toContain('formatStorageBudgetValue')
    expect(page).toContain('dashboard.governance.analytics.storagePolicyRemainingStored')
    expect(page).toContain('dashboard.governance.storagePolicy.alertOverage')
    expect(page).toContain('dashboard.governance.analytics.storageUsage')
    expect(page).toContain('dashboard.governance.analytics.storageProvider')
    expect(page).toContain('dashboard.governance.analytics.storageAction')
    expect(page).toContain('dashboard.governance.analytics.storagePolicyUtilization')
  })

  it('exposes provider quota utilization and risk status in the provider cockpit', () => {
    const page = readFileSync(new URL('./governance.vue', import.meta.url), 'utf8')

    expect(page).toContain('type ProviderQuotaStatus')
    expect(page).toContain('quotaSummary: {')
    expect(page).toContain('analyticsData.providers.quotaSummary.active')
    expect(page).toContain('analyticsData.providers.quotaSummary.blocked')
    expect(page).toContain('analyticsData.providers.quotaSummary.warning')
    expect(page).toContain('providerQuotaPeakUtilization')
    expect(page).toContain('usageSummary: {')
    expect(page).toContain('analyticsData.providers.usageSummary.tokens')
    expect(page).toContain('analyticsData.providers.usageSummary.requests')
    expect(page).toContain('analyticsData.providers.trend')
    expect(page).toContain('dashboard.governance.analytics.providerTrend')
    expect(page).toContain('interface ProviderModelDistributionItem')
    expect(page).toContain('modelDistribution: ProviderModelDistributionItem[]')
    expect(page).toContain('analyticsData.providers.modelDistribution')
    expect(page).toContain('item.byProvider[0]?.providerId')
    expect(page).toContain('item.byProviderType.slice(0, 2)')
    expect(page).toContain('dashboard.governance.analytics.providerModelBreakdown')
    expect(page).toContain('analyticsData.providers.quotas')
    expect(page).toContain('providerQuotaLabel(quota.status)')
    expect(page).toContain('providerQuotaTone(quota.status)')
    expect(page).toContain('formatRatio(quota.utilization.requests)')
    expect(page).toContain('formatRatio(quota.utilization.tokens)')
    expect(page).toContain('remaining: {')
    expect(page).toContain('overage: {')
    expect(page).toContain('quota.remaining.requests')
    expect(page).toContain('quota.remaining.tokens')
    expect(page).toContain('dashboard.governance.analytics.providerQuotaRemainingRequests')
    expect(page).toContain('dashboard.governance.analytics.providerQuotaRemainingTokens')
    expect(page).toContain('dashboard.governance.analytics.providerQuotaUtilization')
  })
})
