// Ported from Amicro, commit 43c29ce9cdd16459e3eab4992381b8d35b38776a.
// MIT License. Copyright (c) 2026 SYED  SUBHAN UDDIN.
import type { LoaderNode } from '../scene-types'
import type { MotionLoaderVariant } from '../types'

/** Dot matrices, grid phases and diagonal sequences. */
export const DOTS_GRID_SCENES: Record<Extract<MotionLoaderVariant, "grid-dots" | "morph-dot-ring" | "spring-dot-matrix" | "zig-zag-pulse">, LoaderNode> = {
  // GridDots: registry/ui/loading/grid-dots.tsx
  'grid-dots': {"tag":"div","style":{"display":"grid","gridTemplateColumns":"repeat(3, minmax(0, 1fr))","gap":"6px"},"children":[{"tag":"div","style":{"width":"10px","height":"10px","backgroundColor":"var(--tx-text-color-primary)","borderRadius":"999px"},"motion":{"values":{"scale":[1,0.5,1],"opacity":[1,0.3,1]},"timing":{"duration":1.5,"delay":0,"ease":"easeInOut"}}},{"tag":"div","style":{"width":"10px","height":"10px","backgroundColor":"var(--tx-text-color-primary)","borderRadius":"999px"},"motion":{"values":{"scale":[1,0.5,1],"opacity":[1,0.3,1]},"timing":{"duration":1.5,"delay":0.2,"ease":"easeInOut"}}},{"tag":"div","style":{"width":"10px","height":"10px","backgroundColor":"var(--tx-text-color-primary)","borderRadius":"999px"},"motion":{"values":{"scale":[1,0.5,1],"opacity":[1,0.3,1]},"timing":{"duration":1.5,"delay":0.4,"ease":"easeInOut"}}},{"tag":"div","style":{"width":"10px","height":"10px","backgroundColor":"var(--tx-text-color-primary)","borderRadius":"999px"},"motion":{"values":{"scale":[1,0.5,1],"opacity":[1,0.3,1]},"timing":{"duration":1.5,"delay":0.2,"ease":"easeInOut"}}},{"tag":"div","style":{"width":"10px","height":"10px","backgroundColor":"var(--tx-text-color-primary)","borderRadius":"999px"},"motion":{"values":{"scale":[1,0.5,1],"opacity":[1,0.3,1]},"timing":{"duration":1.5,"delay":0.4,"ease":"easeInOut"}}},{"tag":"div","style":{"width":"10px","height":"10px","backgroundColor":"var(--tx-text-color-primary)","borderRadius":"999px"},"motion":{"values":{"scale":[1,0.5,1],"opacity":[1,0.3,1]},"timing":{"duration":1.5,"delay":0.6,"ease":"easeInOut"}}},{"tag":"div","style":{"width":"10px","height":"10px","backgroundColor":"var(--tx-text-color-primary)","borderRadius":"999px"},"motion":{"values":{"scale":[1,0.5,1],"opacity":[1,0.3,1]},"timing":{"duration":1.5,"delay":0.4,"ease":"easeInOut"}}},{"tag":"div","style":{"width":"10px","height":"10px","backgroundColor":"var(--tx-text-color-primary)","borderRadius":"999px"},"motion":{"values":{"scale":[1,0.5,1],"opacity":[1,0.3,1]},"timing":{"duration":1.5,"delay":0.6,"ease":"easeInOut"}}},{"tag":"div","style":{"width":"10px","height":"10px","backgroundColor":"var(--tx-text-color-primary)","borderRadius":"999px"},"motion":{"values":{"scale":[1,0.5,1],"opacity":[1,0.3,1]},"timing":{"duration":1.5,"delay":0.8,"ease":"easeInOut"}}}]},
  // MorphDotRing: registry/ui/loading/morph-dot-ring.tsx
  'morph-dot-ring': {"tag":"div","style":{"display":"grid","gridTemplateColumns":"repeat(2, minmax(0, 1fr))","gap":"4px","width":"24px","height":"24px"},"children":[{"tag":"div","style":{"width":"100%","height":"100%","backgroundColor":"var(--tx-text-color-primary)","borderRadius":"999px"}},{"tag":"div","style":{"width":"100%","height":"100%","backgroundColor":"var(--tx-text-color-primary)","borderRadius":"999px"}},{"tag":"div","style":{"width":"100%","height":"100%","backgroundColor":"var(--tx-text-color-primary)","borderRadius":"999px"}},{"tag":"div","style":{"width":"100%","height":"100%","backgroundColor":"var(--tx-text-color-primary)","borderRadius":"999px"}}],"motion":{"values":{"rotate":180,"gap":["4px","0px","4px"]},"timing":{"duration":2,"ease":"easeInOut"}}},
  // SpringDotMatrix: registry/ui/loading/spring-dot-matrix.tsx
  'spring-dot-matrix': {"tag":"div","style":{"display":"grid","gridTemplateColumns":"repeat(3, minmax(0, 1fr))","gap":"10px"},"children":[{"tag":"div","style":{"width":"8px","height":"8px","backgroundColor":"var(--tx-text-color-primary)","borderRadius":"999px"},"motion":{"values":{"scale":[1,0.4,1]},"timing":{"duration":1.5,"ease":"easeInOut","delay":0}}},{"tag":"div","style":{"width":"8px","height":"8px","backgroundColor":"var(--tx-text-color-primary)","borderRadius":"999px"},"motion":{"values":{"scale":[1,0.4,1]},"timing":{"duration":1.5,"ease":"easeInOut","delay":0.15}}},{"tag":"div","style":{"width":"8px","height":"8px","backgroundColor":"var(--tx-text-color-primary)","borderRadius":"999px"},"motion":{"values":{"scale":[1,0.4,1]},"timing":{"duration":1.5,"ease":"easeInOut","delay":0.3}}},{"tag":"div","style":{"width":"8px","height":"8px","backgroundColor":"var(--tx-text-color-primary)","borderRadius":"999px"},"motion":{"values":{"scale":[1,0.4,1]},"timing":{"duration":1.5,"ease":"easeInOut","delay":0.15}}},{"tag":"div","style":{"width":"8px","height":"8px","backgroundColor":"var(--tx-text-color-primary)","borderRadius":"999px"},"motion":{"values":{"scale":[1,0.4,1]},"timing":{"duration":1.5,"ease":"easeInOut","delay":0.3}}},{"tag":"div","style":{"width":"8px","height":"8px","backgroundColor":"var(--tx-text-color-primary)","borderRadius":"999px"},"motion":{"values":{"scale":[1,0.4,1]},"timing":{"duration":1.5,"ease":"easeInOut","delay":0.45}}},{"tag":"div","style":{"width":"8px","height":"8px","backgroundColor":"var(--tx-text-color-primary)","borderRadius":"999px"},"motion":{"values":{"scale":[1,0.4,1]},"timing":{"duration":1.5,"ease":"easeInOut","delay":0.3}}},{"tag":"div","style":{"width":"8px","height":"8px","backgroundColor":"var(--tx-text-color-primary)","borderRadius":"999px"},"motion":{"values":{"scale":[1,0.4,1]},"timing":{"duration":1.5,"ease":"easeInOut","delay":0.45}}},{"tag":"div","style":{"width":"8px","height":"8px","backgroundColor":"var(--tx-text-color-primary)","borderRadius":"999px"},"motion":{"values":{"scale":[1,0.4,1]},"timing":{"duration":1.5,"ease":"easeInOut","delay":0.6}}}]},
  // ZigZagPulse: registry/ui/loading/zig-zag-pulse.tsx
  'zig-zag-pulse': {"tag":"div","style":{"display":"grid","gridTemplateColumns":"repeat(3, minmax(0, 1fr))","gap":"8px","width":"48px","height":"48px"},"children":[{"tag":"div","style":{"width":"10px","height":"10px","backgroundColor":"var(--tx-text-color-primary)","borderRadius":"999px","gridColumn":1,"gridRow":1},"motion":{"values":{"opacity":[0.2,1,0.2]},"timing":{"duration":1.2,"delay":0,"ease":"easeInOut"}}},{"tag":"div","style":{"width":"10px","height":"10px","backgroundColor":"var(--tx-text-color-primary)","borderRadius":"999px","gridColumn":2,"gridRow":2},"motion":{"values":{"opacity":[0.2,1,0.2]},"timing":{"duration":1.2,"delay":0.1,"ease":"easeInOut"}}},{"tag":"div","style":{"width":"10px","height":"10px","backgroundColor":"var(--tx-text-color-primary)","borderRadius":"999px","gridColumn":3,"gridRow":1},"motion":{"values":{"opacity":[0.2,1,0.2]},"timing":{"duration":1.2,"delay":0.2,"ease":"easeInOut"}}},{"tag":"div","style":{"width":"10px","height":"10px","backgroundColor":"var(--tx-text-color-primary)","borderRadius":"999px","gridColumn":1,"gridRow":3},"motion":{"values":{"opacity":[0.2,1,0.2]},"timing":{"duration":1.2,"delay":0.3,"ease":"easeInOut"}}},{"tag":"div","style":{"width":"10px","height":"10px","backgroundColor":"var(--tx-text-color-primary)","borderRadius":"999px","gridColumn":2,"gridRow":2},"motion":{"values":{"opacity":[0.2,1,0.2]},"timing":{"duration":1.2,"delay":0.4,"ease":"easeInOut"}}},{"tag":"div","style":{"width":"10px","height":"10px","backgroundColor":"var(--tx-text-color-primary)","borderRadius":"999px","gridColumn":3,"gridRow":3},"motion":{"values":{"opacity":[0.2,1,0.2]},"timing":{"duration":1.2,"delay":0.5,"ease":"easeInOut"}}}]},
}
