// Ported from Amicro, commit 43c29ce9cdd16459e3eab4992381b8d35b38776a.
// MIT License. Copyright (c) 2026 SYED  SUBHAN UDDIN.
import type { LoaderNode } from '../scene-types'
import type { MotionLoaderVariant } from '../types'

/** Dots arranged in rows or moving along linear tracks. */
export const DOTS_LINEAR_SCENES: Record<Extract<MotionLoaderVariant, "apple-pulse-dots" | "bobbing-dots" | "bounce-dots" | "bouncing-dots" | "conveyor-loop" | "drop-dot" | "fade-dots" | "liquid-dots" | "magnetic-dots" | "newtons-cradle" | "pulsating-dots" | "pulse-dot" | "pulse-dots" | "anim-pulse-dots" | "smooth-dot-shift" | "swapping-dots" | "trailing-dots" | "typing" | "typing-indicator" | "wave-dots">, LoaderNode> = {
  // ApplePulseDots: registry/ui/loading/apple-pulse-dots.tsx
  'apple-pulse-dots': {"tag":"div","style":{"display":"flex"},"children":[{"tag":"div","style":{"width":"10px","height":"10px","backgroundColor":"var(--tx-text-color-primary)","borderRadius":"999px"},"motion":{"values":{"scale":[0.5,1,0.5],"opacity":[0.3,1,0.3]},"timing":{"duration":1.2,"delay":0,"ease":"easeInOut"}}},{"tag":"div","style":{"width":"10px","height":"10px","backgroundColor":"var(--tx-text-color-primary)","borderRadius":"999px","marginLeft":"8px"},"motion":{"values":{"scale":[0.5,1,0.5],"opacity":[0.3,1,0.3]},"timing":{"duration":1.2,"delay":0.15,"ease":"easeInOut"}}},{"tag":"div","style":{"width":"10px","height":"10px","backgroundColor":"var(--tx-text-color-primary)","borderRadius":"999px","marginLeft":"8px"},"motion":{"values":{"scale":[0.5,1,0.5],"opacity":[0.3,1,0.3]},"timing":{"duration":1.2,"delay":0.3,"ease":"easeInOut"}}}]},
  // BobbingDots: registry/ui/loading/bobbing-dots.tsx
  'bobbing-dots': {"tag":"div","style":{"display":"flex"},"children":[{"tag":"div","style":{"width":"12px","height":"12px","backgroundColor":"var(--tx-text-color-primary)","borderRadius":"999px"},"motion":{"values":{"y":[0,-10,0]},"timing":{"duration":1.2,"delay":0,"ease":"easeInOut"}}},{"tag":"div","style":{"width":"12px","height":"12px","backgroundColor":"var(--tx-text-color-primary)","borderRadius":"999px","marginLeft":"8px"},"motion":{"values":{"y":[0,-10,0]},"timing":{"duration":1.2,"delay":0.15,"ease":"easeInOut"}}},{"tag":"div","style":{"width":"12px","height":"12px","backgroundColor":"var(--tx-text-color-primary)","borderRadius":"999px","marginLeft":"8px"},"motion":{"values":{"y":[0,-10,0]},"timing":{"duration":1.2,"delay":0.3,"ease":"easeInOut"}}}]},
  // BounceDots: registry/ui/loading/bounce-dots.tsx
  'bounce-dots': {"tag":"div","style":{"display":"flex"},"children":[{"tag":"div","style":{"width":"10px","height":"10px","backgroundColor":"var(--tx-text-color-primary)","borderRadius":"999px"},"motion":{"values":{"y":[0,-8,0]},"timing":{"duration":0.6,"delay":0,"ease":"easeInOut"}}},{"tag":"div","style":{"width":"10px","height":"10px","backgroundColor":"var(--tx-text-color-primary)","borderRadius":"999px","marginLeft":"6px"},"motion":{"values":{"y":[0,-8,0]},"timing":{"duration":0.6,"delay":0.1,"ease":"easeInOut"}}},{"tag":"div","style":{"width":"10px","height":"10px","backgroundColor":"var(--tx-text-color-primary)","borderRadius":"999px","marginLeft":"6px"},"motion":{"values":{"y":[0,-8,0]},"timing":{"duration":0.6,"delay":0.2,"ease":"easeInOut"}}}]},
  // BouncingDots: registry/ui/loading/bouncing-dots.tsx
  'bouncing-dots': {"tag":"div","style":{"display":"flex","height":"48px","alignItems":"flex-end","paddingBottom":"8px","borderBottomWidth":"2px","borderBottomStyle":"solid","borderColor":"var(--tx-fill-color-dark)","width":"64px","justifyContent":"center","position":"relative"},"children":[{"tag":"div","style":{"width":"12px","height":"12px","backgroundColor":"var(--tx-text-color-primary)","borderRadius":"999px","position":"absolute","bottom":"8px","left":"10px"},"motion":{"values":{"y":[0,-20,0],"scaleY":[0.8,1.1,0.8]},"timing":{"duration":0.8,"delay":0,"ease":"easeInOut"}}},{"tag":"div","style":{"width":"12px","height":"12px","backgroundColor":"var(--tx-text-color-primary)","borderRadius":"999px","position":"absolute","bottom":"8px","left":"24px","marginLeft":"8px"},"motion":{"values":{"y":[0,-20,0],"scaleY":[0.8,1.1,0.8]},"timing":{"duration":0.8,"delay":0.1,"ease":"easeInOut"}}},{"tag":"div","style":{"width":"12px","height":"12px","backgroundColor":"var(--tx-text-color-primary)","borderRadius":"999px","position":"absolute","bottom":"8px","left":"38px","marginLeft":"8px"},"motion":{"values":{"y":[0,-20,0],"scaleY":[0.8,1.1,0.8]},"timing":{"duration":0.8,"delay":0.2,"ease":"easeInOut"}}}]},
  // ConveyorLoop: registry/ui/loading/conveyor-loop.tsx
  'conveyor-loop': {"tag":"div","style":{"width":"64px","height":"12px","overflow":"hidden","position":"relative","borderRadius":"999px","backgroundColor":"var(--tx-fill-color-dark)"},"children":[{"tag":"div","style":{"display":"flex","height":"100%","position":"absolute","top":"0px","alignItems":"center"},"children":[{"tag":"div","style":{"width":"6px","height":"6px","backgroundColor":"var(--tx-text-color-primary)","borderRadius":"999px","flexShrink":0}},{"tag":"div","style":{"width":"6px","height":"6px","backgroundColor":"var(--tx-text-color-primary)","borderRadius":"999px","flexShrink":0,"marginLeft":"8px"}},{"tag":"div","style":{"width":"6px","height":"6px","backgroundColor":"var(--tx-text-color-primary)","borderRadius":"999px","flexShrink":0,"marginLeft":"8px"}},{"tag":"div","style":{"width":"6px","height":"6px","backgroundColor":"var(--tx-text-color-primary)","borderRadius":"999px","flexShrink":0,"marginLeft":"8px"}},{"tag":"div","style":{"width":"6px","height":"6px","backgroundColor":"var(--tx-text-color-primary)","borderRadius":"999px","flexShrink":0,"marginLeft":"8px"}},{"tag":"div","style":{"width":"6px","height":"6px","backgroundColor":"var(--tx-text-color-primary)","borderRadius":"999px","flexShrink":0,"marginLeft":"8px"}},{"tag":"div","style":{"width":"6px","height":"6px","backgroundColor":"var(--tx-text-color-primary)","borderRadius":"999px","flexShrink":0,"marginLeft":"8px"}},{"tag":"div","style":{"width":"6px","height":"6px","backgroundColor":"var(--tx-text-color-primary)","borderRadius":"999px","flexShrink":0,"marginLeft":"8px"}}],"motion":{"values":{"x":[0,-32]},"timing":{"duration":1,"ease":"linear"}}}]},
  // DropDot: registry/ui/loading/drop-dot.tsx
  'drop-dot': {"tag":"div","style":{"position":"relative","width":"24px","height":"48px","display":"flex","flexDirection":"column","alignItems":"center"},"children":[{"tag":"div","style":{"width":"10px","height":"10px","backgroundColor":"var(--tx-text-color-primary)","borderRadius":"999px","position":"absolute","top":"0px","zIndex":10},"motion":{"values":{"y":[0,24,0],"scaleY":[1,1.2,1],"scaleX":[1,0.8,1]},"timing":{"duration":1,"ease":"circIn"}}},{"tag":"div","style":{"width":"16px","height":"4px","backgroundColor":"var(--tx-border-color)","borderRadius":"999px","position":"absolute","bottom":"8px","filter":"blur(1px)"}}]},
  // FadeDots: registry/ui/loading/fade-dots.tsx
  'fade-dots': {"tag":"div","style":{"display":"flex"},"children":[{"tag":"div","style":{"width":"10px","height":"10px","backgroundColor":"var(--tx-text-color-primary)","borderRadius":"999px"},"motion":{"values":{"opacity":[0,1,0]},"timing":{"duration":1.5,"delay":0,"ease":"linear"}}},{"tag":"div","style":{"width":"10px","height":"10px","backgroundColor":"var(--tx-text-color-primary)","borderRadius":"999px","marginLeft":"8px"},"motion":{"values":{"opacity":[0,1,0]},"timing":{"duration":1.5,"delay":0.2,"ease":"linear"}}},{"tag":"div","style":{"width":"10px","height":"10px","backgroundColor":"var(--tx-text-color-primary)","borderRadius":"999px","marginLeft":"8px"},"motion":{"values":{"opacity":[0,1,0]},"timing":{"duration":1.5,"delay":0.4,"ease":"linear"}}},{"tag":"div","style":{"width":"10px","height":"10px","backgroundColor":"var(--tx-text-color-primary)","borderRadius":"999px","marginLeft":"8px"},"motion":{"values":{"opacity":[0,1,0]},"timing":{"duration":1.5,"delay":0.6,"ease":"linear"}}}]},
  // LiquidDots: registry/ui/loading/liquid-dots.tsx
  'liquid-dots': {"tag":"div","style":{"position":"relative","width":"64px","height":"32px","display":"flex","alignItems":"center","justifyContent":"center","filter":"url(#goo)"},"children":[{"tag":"svg","style":{"position":"absolute","width":"0px","height":"0px","transformBox":"fill-box","transformOrigin":"center"},"children":[{"tag":"defs","style":{"transformBox":"fill-box","transformOrigin":"center"},"children":[{"tag":"filter","style":{"transformBox":"fill-box","transformOrigin":"center"},"attrs":{"id":"goo"},"children":[{"tag":"feGaussianBlur","style":{"transformBox":"fill-box","transformOrigin":"center"},"attrs":{"in":"SourceGraphic","stdDeviation":"4","result":"blur"}},{"tag":"feColorMatrix","style":{"transformBox":"fill-box","transformOrigin":"center"},"attrs":{"in":"blur","mode":"matrix","values":"1 0 0 0 0  0 1 0 0 0  0 0 1 0 0  0 0 0 18 -7","result":"goo"}},{"tag":"feBlend","style":{"transformBox":"fill-box","transformOrigin":"center"},"attrs":{"in":"SourceGraphic","in2":"goo"}}]}]}]},{"tag":"div","style":{"position":"absolute","width":"24px","height":"24px","backgroundColor":"var(--tx-text-color-primary)","borderRadius":"999px"},"motion":{"values":{"x":[-16,16,-16]},"timing":{"duration":2,"ease":"easeInOut"}}},{"tag":"div","style":{"position":"absolute","width":"24px","height":"24px","backgroundColor":"var(--tx-text-color-primary)","borderRadius":"999px"},"motion":{"values":{"x":[16,-16,16]},"timing":{"duration":2,"ease":"easeInOut"}}}]},
  // MagneticDots: registry/ui/loading/magnetic-dots.tsx
  'magnetic-dots': {"tag":"div","style":{"display":"flex","filter":"url(#goo)"},"children":[{"tag":"svg","style":{"position":"absolute","width":"0px","height":"0px","transformBox":"fill-box","transformOrigin":"center"},"attrs":{"width":"0","height":"0"},"children":[{"tag":"defs","style":{"transformBox":"fill-box","transformOrigin":"center"},"children":[{"tag":"filter","style":{"transformBox":"fill-box","transformOrigin":"center"},"attrs":{"id":"goo"},"children":[{"tag":"feGaussianBlur","style":{"transformBox":"fill-box","transformOrigin":"center"},"attrs":{"in":"SourceGraphic","stdDeviation":"2","result":"blur"}},{"tag":"feColorMatrix","style":{"transformBox":"fill-box","transformOrigin":"center"},"attrs":{"in":"blur","mode":"matrix","values":"1 0 0 0 0  0 1 0 0 0  0 0 1 0 0  0 0 0 15 -7","result":"goo"}},{"tag":"feComposite","style":{"transformBox":"fill-box","transformOrigin":"center"},"attrs":{"in":"SourceGraphic","in2":"goo","operator":"atop"}}]}]}]},{"tag":"div","style":{"width":"16px","height":"16px","backgroundColor":"var(--tx-text-color-primary)","borderRadius":"999px","marginLeft":"6px"},"motion":{"values":{"x":[0,8,0]},"timing":{"duration":1.5,"ease":"easeInOut"}}},{"tag":"div","style":{"width":"16px","height":"16px","backgroundColor":"var(--tx-text-color-primary)","borderRadius":"999px","marginLeft":"6px"},"motion":{"values":{"x":[0,-8,0]},"timing":{"duration":1.5,"ease":"easeInOut"}}}]},
  // NewtonsCradle: registry/ui/loading/newtons-cradle.tsx
  'newtons-cradle': {"tag":"div","style":{"display":"flex","alignItems":"center","justifyContent":"center"},"children":[{"tag":"div","style":{"width":"12px","height":"12px","backgroundColor":"var(--tx-text-color-primary)","borderRadius":"999px","transformOrigin":"top"},"motion":{"values":{"rotate":[25,0,0,0,0,25]},"timing":{"duration":1.5,"ease":"easeInOut"}}},{"tag":"div","style":{"width":"12px","height":"12px","backgroundColor":"var(--tx-text-color-primary)","borderRadius":"999px","marginLeft":"2px"}},{"tag":"div","style":{"width":"12px","height":"12px","backgroundColor":"var(--tx-text-color-primary)","borderRadius":"999px","marginLeft":"2px"}},{"tag":"div","style":{"width":"12px","height":"12px","backgroundColor":"var(--tx-text-color-primary)","borderRadius":"999px","transformOrigin":"top","marginLeft":"2px"},"motion":{"values":{"rotate":[0,0,0,-25,0,0]},"timing":{"duration":1.5,"ease":"easeInOut"}}}]},
  // PulsatingDots: registry/ui/loading/pulsating-dots.tsx
  'pulsating-dots': {"tag":"div","style":{"display":"flex"},"children":[{"tag":"div","style":{"width":"12px","height":"12px","backgroundColor":"var(--tx-text-color-primary)","borderRadius":"999px"},"motion":{"values":{"scale":[1,1.5,1],"opacity":[0.5,1,0.5]},"timing":{"duration":1.2,"delay":0,"ease":"easeInOut"}}},{"tag":"div","style":{"width":"12px","height":"12px","backgroundColor":"var(--tx-text-color-primary)","borderRadius":"999px","marginLeft":"8px"},"motion":{"values":{"scale":[1,1.5,1],"opacity":[0.5,1,0.5]},"timing":{"duration":1.2,"delay":0.2,"ease":"easeInOut"}}},{"tag":"div","style":{"width":"12px","height":"12px","backgroundColor":"var(--tx-text-color-primary)","borderRadius":"999px","marginLeft":"8px"},"motion":{"values":{"scale":[1,1.5,1],"opacity":[0.5,1,0.5]},"timing":{"duration":1.2,"delay":0.4,"ease":"easeInOut"}}}]},
  // PulseDot: registry/ui/loading/pulse-dot.tsx
  'pulse-dot': {"tag":"div","style":{"position":"relative","width":"40px","height":"40px","display":"flex","alignItems":"center","justifyContent":"center"},"children":[{"tag":"div","style":{"position":"absolute","width":"40px","height":"40px","backgroundColor":"var(--tx-text-color-primary)","borderRadius":"999px"},"motion":{"values":{"scale":[0,1],"opacity":[0.8,0]},"timing":{"duration":1.5,"ease":"easeOut"}}},{"tag":"div","style":{"width":"12px","height":"12px","backgroundColor":"var(--tx-text-color-primary)","borderRadius":"999px","position":"relative","zIndex":10}}]},
  // PulseDots: registry/ui/loading/pulse-dots.tsx
  'pulse-dots': {"tag":"div","style":{"display":"flex"},"children":[{"tag":"div","style":{"width":"10px","height":"10px","backgroundColor":"var(--tx-text-color-primary)","borderRadius":"999px"},"motion":{"values":{"opacity":[0.2,1,0.2]},"timing":{"duration":1.4,"delay":0}}},{"tag":"div","style":{"width":"10px","height":"10px","backgroundColor":"var(--tx-text-color-primary)","borderRadius":"999px","marginLeft":"6px"},"motion":{"values":{"opacity":[0.2,1,0.2]},"timing":{"duration":1.4,"delay":0.2}}},{"tag":"div","style":{"width":"10px","height":"10px","backgroundColor":"var(--tx-text-color-primary)","borderRadius":"999px","marginLeft":"6px"},"motion":{"values":{"opacity":[0.2,1,0.2]},"timing":{"duration":1.4,"delay":0.4}}}]},
  // PulseOrbitDots: src/components/css-animations/whimsical/AppleLoaders.tsx
  'anim-pulse-dots': {"tag":"div","style":{"display":"flex","alignItems":"center","gap":"10px"},"children":[{"tag":"div","style":{"width":"12px","height":"12px","borderRadius":"999px","backgroundColor":"var(--tx-color-primary)"},"motion":{"values":{"scale":[0.6,1.15,0.6],"opacity":[0.3,1,0.3]},"timing":{"duration":1.2,"ease":"easeInOut","delay":0}}},{"tag":"div","style":{"width":"12px","height":"12px","borderRadius":"999px","backgroundColor":"var(--tx-color-info)"},"motion":{"values":{"scale":[0.6,1.15,0.6],"opacity":[0.3,1,0.3]},"timing":{"duration":1.2,"ease":"easeInOut","delay":0.2}}},{"tag":"div","style":{"width":"12px","height":"12px","borderRadius":"999px","backgroundColor":"var(--tx-color-primary)"},"motion":{"values":{"scale":[0.6,1.15,0.6],"opacity":[0.3,1,0.3]},"timing":{"duration":1.2,"ease":"easeInOut","delay":0.4}}}]},
  // SmoothDotShift: registry/ui/loading/smooth-dot-shift.tsx
  'smooth-dot-shift': {"tag":"div","style":{"position":"relative","width":"48px","height":"12px","display":"flex","alignItems":"center"},"children":[{"tag":"div","style":{"position":"absolute","width":"12px","height":"12px","backgroundColor":"var(--tx-text-color-primary)","borderRadius":"999px","zIndex":10},"motion":{"values":{"x":[0,18,36,18,0]},"timing":{"duration":2,"ease":"easeInOut"}}},{"tag":"div","style":{"width":"12px","height":"12px","backgroundColor":"var(--tx-border-color)","borderRadius":"999px","position":"absolute","left":"0px"}},{"tag":"div","style":{"width":"12px","height":"12px","backgroundColor":"var(--tx-border-color)","borderRadius":"999px","position":"absolute","left":"18px"}},{"tag":"div","style":{"width":"12px","height":"12px","backgroundColor":"var(--tx-border-color)","borderRadius":"999px","position":"absolute","left":"36px"}}]},
  // SwappingDots: registry/ui/loading/swapping-dots.tsx
  'swapping-dots': {"tag":"div","style":{"position":"relative","width":"48px","height":"16px","display":"flex","alignItems":"center"},"children":[{"tag":"div","style":{"position":"absolute","left":"0px","width":"16px","height":"16px","backgroundColor":"var(--tx-text-color-primary)","borderRadius":"999px"},"motion":{"values":{"x":[0,32,0]},"timing":{"duration":1.5,"ease":"easeInOut"}}},{"tag":"div","style":{"position":"absolute","right":"0px","width":"16px","height":"16px","backgroundColor":"var(--tx-text-color-placeholder)","borderRadius":"999px"},"motion":{"values":{"x":[0,-32,0]},"timing":{"duration":1.5,"ease":"easeInOut"}}}]},
  // TrailingDots: registry/ui/loading/trailing-dots.tsx
  'trailing-dots': {"tag":"div","style":{"position":"relative","width":"40px","height":"40px"},"children":[{"tag":"div","style":{"position":"absolute","left":"0px","bottom":"0px","right":"0px","top":"0px"},"children":[{"tag":"div","style":{"width":"8px","height":"8px","borderRadius":"999px","position":"absolute","top":"0px","left":"50%","marginLeft":"-4px","backgroundColor":"var(--tx-text-color-primary)","opacity":1}}],"motion":{"values":{"rotate":360},"timing":{"duration":1.5,"delay":0,"ease":"easeInOut"}}},{"tag":"div","style":{"position":"absolute","left":"0px","bottom":"0px","right":"0px","top":"0px"},"children":[{"tag":"div","style":{"width":"8px","height":"8px","borderRadius":"999px","position":"absolute","top":"0px","left":"50%","marginLeft":"-4px","backgroundColor":"var(--tx-text-color-placeholder)","opacity":0.8}}],"motion":{"values":{"rotate":360},"timing":{"duration":1.5,"delay":0.1,"ease":"easeInOut"}}},{"tag":"div","style":{"position":"absolute","left":"0px","bottom":"0px","right":"0px","top":"0px"},"children":[{"tag":"div","style":{"width":"8px","height":"8px","borderRadius":"999px","position":"absolute","top":"0px","left":"50%","marginLeft":"-4px","backgroundColor":"var(--tx-text-color-placeholder)","opacity":0.6}}],"motion":{"values":{"rotate":360},"timing":{"duration":1.5,"delay":0.2,"ease":"easeInOut"}}},{"tag":"div","style":{"position":"absolute","left":"0px","bottom":"0px","right":"0px","top":"0px"},"children":[{"tag":"div","style":{"width":"8px","height":"8px","borderRadius":"999px","position":"absolute","top":"0px","left":"50%","marginLeft":"-4px","backgroundColor":"var(--tx-text-color-placeholder)","opacity":0.4}}],"motion":{"values":{"rotate":360},"timing":{"duration":1.5,"delay":0.3,"ease":"easeInOut"}}},{"tag":"div","style":{"position":"absolute","left":"0px","bottom":"0px","right":"0px","top":"0px"},"children":[{"tag":"div","style":{"width":"8px","height":"8px","borderRadius":"999px","position":"absolute","top":"0px","left":"50%","marginLeft":"-4px","backgroundColor":"var(--tx-text-color-placeholder)","opacity":0.2}}],"motion":{"values":{"rotate":360},"timing":{"duration":1.5,"delay":0.4,"ease":"easeInOut"}}}]},
  // Typing: registry/ui/loading/typing.tsx
  'typing': {"tag":"div","style":{"display":"flex","alignItems":"center","color":"var(--tx-text-color-primary)","fontWeight":500,"fontSize":"14px","width":"80px"},"children":[{"label":"loading"},{"tag":"span","style":{"width":"6px","height":"16px","backgroundColor":"var(--tx-text-color-primary)","marginLeft":"4px","display":"inline-block"},"motion":{"values":{"opacity":[1,0,1]},"timing":{"duration":0.8,"ease":"linear"}}}]},
  // TypingIndicator: registry/ui/loading/typing-indicator.tsx
  'typing-indicator': {"tag":"div","style":{"display":"flex","alignItems":"center","justifyContent":"center","paddingLeft":"16px","paddingRight":"16px","paddingTop":"8px","paddingBottom":"8px","backgroundColor":"var(--tx-fill-color-light)","borderRadius":"999px"},"children":[{"tag":"div","style":{"width":"6px","height":"6px","backgroundColor":"var(--tx-text-color-secondary)","borderRadius":"999px"},"motion":{"values":{"y":[0,-4,0]},"timing":{"duration":0.6,"delay":0,"ease":"easeInOut"}}},{"tag":"div","style":{"width":"6px","height":"6px","backgroundColor":"var(--tx-text-color-secondary)","borderRadius":"999px","marginLeft":"4px"},"motion":{"values":{"y":[0,-4,0]},"timing":{"duration":0.6,"delay":0.15,"ease":"easeInOut"}}},{"tag":"div","style":{"width":"6px","height":"6px","backgroundColor":"var(--tx-text-color-secondary)","borderRadius":"999px","marginLeft":"4px"},"motion":{"values":{"y":[0,-4,0]},"timing":{"duration":0.6,"delay":0.3,"ease":"easeInOut"}}}]},
  // WaveDots: registry/ui/loading/wave-dots.tsx
  'wave-dots': {"tag":"div","style":{"display":"flex","height":"24px","alignItems":"center"},"children":[{"tag":"div","style":{"width":"8px","height":"8px","backgroundColor":"var(--tx-text-color-primary)","borderRadius":"999px"},"motion":{"values":{"y":[4,-4,4]},"timing":{"duration":1,"delay":0,"ease":"easeInOut"}}},{"tag":"div","style":{"width":"8px","height":"8px","backgroundColor":"var(--tx-text-color-primary)","borderRadius":"999px","marginLeft":"6px"},"motion":{"values":{"y":[4,-4,4]},"timing":{"duration":1,"delay":0.15,"ease":"easeInOut"}}},{"tag":"div","style":{"width":"8px","height":"8px","backgroundColor":"var(--tx-text-color-primary)","borderRadius":"999px","marginLeft":"6px"},"motion":{"values":{"y":[4,-4,4]},"timing":{"duration":1,"delay":0.3,"ease":"easeInOut"}}},{"tag":"div","style":{"width":"8px","height":"8px","backgroundColor":"var(--tx-text-color-primary)","borderRadius":"999px","marginLeft":"6px"},"motion":{"values":{"y":[4,-4,4]},"timing":{"duration":1,"delay":0.45,"ease":"easeInOut"}}},{"tag":"div","style":{"width":"8px","height":"8px","backgroundColor":"var(--tx-text-color-primary)","borderRadius":"999px","marginLeft":"6px"},"motion":{"values":{"y":[4,-4,4]},"timing":{"duration":1,"delay":0.6,"ease":"easeInOut"}}}]},
}
