// Ported from Amicro, commit 43c29ce9cdd16459e3eab4992381b8d35b38776a.
// MIT License. Copyright (c) 2026 SYED  SUBHAN UDDIN.
import type { LoaderNode } from '../scene-types'
import type { MotionLoaderVariant } from '../types'

/** Squares, diamonds, polygons and folding shapes. */
export const SHAPE_SCENES: Record<Extract<MotionLoaderVariant, "apple-icon-morph" | "bouncing-square" | "breathing-square" | "concentric-squares" | "cross-spinner" | "cube-flip-spring" | "diamond-grid" | "diamond-rotate-spring" | "elastic-square" | "expanding-cross" | "flip-square" | "floating-diamonds" | "fluid-diamond" | "hexagon-spinner" | "hourglass" | "infinity-path" | "anim-matrix-loader" | "minimal-triangle" | "morph-loader" | "morphing-shape" | "origami-shape" | "pendulum" | "pulse-square" | "pumping-heart" | "rotating-cross" | "rotating-triangle" | "shape-shift-grid" | "smooth-rounded-square" | "spinning-squares" | "spring-hexagon" | "square-accordion" | "square-grid" | "square-snake" | "square-spinner" | "wandering-cube">, LoaderNode> = {
  // AppleIconMorph: registry/ui/loading/apple-icon-morph.tsx
  'apple-icon-morph': {"tag":"div","style":{"width":"32px","height":"32px","backgroundColor":"var(--tx-text-color-primary)"},"motion":{"values":{"borderRadius":["20%","50%","50%","20%"],"rotate":[0,90,180,270]},"timing":{"duration":2,"ease":"easeInOut"}}},
  // BouncingSquare: registry/ui/loading/bouncing-square.tsx
  'bouncing-square': {"tag":"div","style":{"position":"relative","width":"40px","height":"48px","display":"flex","alignItems":"flex-end","justifyContent":"center"},"children":[{"tag":"div","style":{"position":"absolute","bottom":"0px","width":"32px","height":"4px","backgroundColor":"var(--tx-fill-color-dark)","borderRadius":"999px","filter":"blur(4px)"}},{"tag":"div","style":{"width":"24px","height":"24px","backgroundColor":"var(--tx-text-color-primary)","borderRadius":"2px","transformOrigin":"bottom"},"motion":{"values":{"y":[0,-24,0],"scaleY":[0.8,1.1,0.8],"scaleX":[1.2,0.9,1.2]},"timing":{"duration":0.6,"ease":"easeInOut"}}}]},
  // BreathingSquare: registry/ui/loading/breathing-square.tsx
  'breathing-square': {"tag":"div","style":{"width":"32px","height":"32px","backgroundColor":"var(--tx-text-color-primary)"},"motion":{"values":{"scale":[1,1.2,1],"borderRadius":["0%","50%","0%"],"rotate":[0,90,180]},"timing":{"duration":2,"ease":"easeInOut"}}},
  // ConcentricSquares: registry/ui/loading/concentric-squares.tsx
  'concentric-squares': {"tag":"div","style":{"position":"relative","width":"48px","height":"48px","display":"flex","alignItems":"center","justifyContent":"center"},"children":[{"tag":"div","style":{"position":"absolute","width":"48px","height":"48px","borderWidth":"2px","borderStyle":"solid","borderColor":"var(--tx-text-color-primary)","borderRadius":"2px"},"motion":{"values":{"rotate":[0,90,90],"scale":[1,1,0.8,1]},"timing":{"duration":2,"ease":"easeInOut"}}},{"tag":"div","style":{"position":"absolute","width":"24px","height":"24px","borderWidth":"2px","borderStyle":"solid","borderColor":"var(--tx-text-color-secondary)","borderRadius":"2px"},"motion":{"values":{"rotate":[0,-90,-90],"scale":[1,1,1.2,1]},"timing":{"duration":2,"ease":"easeInOut"}}}]},
  // CrossSpinner: registry/ui/loading/cross-spinner.tsx
  'cross-spinner': {"tag":"div","style":{"position":"relative","width":"32px","height":"32px","display":"flex","alignItems":"center","justifyContent":"center"},"children":[{"tag":"div","style":{"position":"absolute","width":"100%","height":"6px","backgroundColor":"var(--tx-text-color-primary)","borderRadius":"999px"}},{"tag":"div","style":{"position":"absolute","height":"100%","width":"6px","backgroundColor":"var(--tx-text-color-primary)","borderRadius":"999px"}}],"motion":{"values":{"rotate":[0,90,180,270,360]},"timing":{"duration":2,"ease":"easeInOut"}}},
  // CubeFlipSpring: registry/ui/loading/cube-flip-spring.tsx
  'cube-flip-spring': {"tag":"div","style":{"width":"32px","height":"32px","backgroundColor":"var(--tx-text-color-primary)","borderRadius":"8px"},"motion":{"values":{"rotateX":[0,180,180],"rotateY":[0,0,180]},"timing":{"duration":2,"type":"spring","bounce":0.2}}},
  // DiamondGrid: registry/ui/loading/diamond-grid.tsx
  'diamond-grid': {"tag":"div","style":{"display":"grid","gridTemplateColumns":"repeat(2, minmax(0, 1fr))","gap":"8px","transform":"rotate(45deg)"},"children":[{"tag":"div","style":{"width":"12px","height":"12px","backgroundColor":"var(--tx-text-color-primary)","borderRadius":"2px"},"motion":{"values":{"scale":[1,0.5,1],"opacity":[1,0.3,1]},"timing":{"duration":1.5,"delay":0,"ease":"easeInOut"}}},{"tag":"div","style":{"width":"12px","height":"12px","backgroundColor":"var(--tx-text-color-primary)","borderRadius":"2px"},"motion":{"values":{"scale":[1,0.5,1],"opacity":[1,0.3,1]},"timing":{"duration":1.5,"delay":0.2,"ease":"easeInOut"}}},{"tag":"div","style":{"width":"12px","height":"12px","backgroundColor":"var(--tx-text-color-primary)","borderRadius":"2px"},"motion":{"values":{"scale":[1,0.5,1],"opacity":[1,0.3,1]},"timing":{"duration":1.5,"delay":0.4,"ease":"easeInOut"}}},{"tag":"div","style":{"width":"12px","height":"12px","backgroundColor":"var(--tx-text-color-primary)","borderRadius":"2px"},"motion":{"values":{"scale":[1,0.5,1],"opacity":[1,0.3,1]},"timing":{"duration":1.5,"delay":0.6,"ease":"easeInOut"}}}]},
  // DiamondRotateSpring: registry/ui/loading/diamond-rotate-spring.tsx
  'diamond-rotate-spring': {"tag":"div","style":{"width":"32px","height":"32px","backgroundColor":"var(--tx-text-color-primary)","borderRadius":"2px","transformOrigin":"center"},"motion":{"values":{"rotate":[45,135,225,315]},"timing":{"duration":2,"type":"spring","bounce":0.4}}},
  // ElasticSquare: registry/ui/loading/elastic-square.tsx
  'elastic-square': {"tag":"div","style":{"height":"48px","display":"flex","alignItems":"flex-end","borderBottomWidth":"2px","borderBottomStyle":"solid","borderColor":"var(--tx-fill-color-dark)","width":"48px","justifyContent":"center"},"children":[{"tag":"div","style":{"width":"24px","height":"24px","backgroundColor":"var(--tx-text-color-primary)","borderRadius":"2px","transformOrigin":"bottom"},"motion":{"values":{"y":[0,-20,0],"scaleY":[0.7,1.2,0.7],"scaleX":[1.3,0.8,1.3]},"timing":{"duration":0.8,"ease":"easeInOut"}}}]},
  // ExpandingCross: registry/ui/loading/expanding-cross.tsx
  'expanding-cross': {"tag":"div","style":{"position":"relative","width":"32px","height":"32px"},"children":[{"tag":"div","style":{"position":"absolute","top":"50%","left":"0px","width":"100%","height":"4px","backgroundColor":"var(--tx-text-color-primary)","marginTop":"-2px","borderRadius":"999px"},"motion":{"values":{"scaleX":[0.2,1,0.2]},"timing":{"duration":1.5,"ease":"easeInOut"}}},{"tag":"div","style":{"position":"absolute","left":"50%","top":"0px","height":"100%","width":"4px","backgroundColor":"var(--tx-text-color-primary)","marginLeft":"-2px","borderRadius":"999px"},"motion":{"values":{"scaleY":[0.2,1,0.2]},"timing":{"duration":1.5,"ease":"easeInOut","delay":0.75}}}]},
  // FlipSquare: registry/ui/loading/flip-square.tsx
  'flip-square': {"tag":"div","style":{"width":"32px","height":"32px","backgroundColor":"var(--tx-text-color-primary)","borderRadius":"6px","boxShadow":"var(--tx-elevation-1)"},"motion":{"values":{"rotateX":[0,180,180,0],"rotateY":[0,0,180,180]},"timing":{"duration":2,"ease":"easeInOut"}}},
  // FloatingDiamonds: registry/ui/loading/floating-diamonds.tsx
  'floating-diamonds': {"tag":"div","style":{"display":"flex"},"children":[{"tag":"div","style":{"width":"12px","height":"12px","backgroundColor":"var(--tx-text-color-primary)","borderRadius":"2px","transform":"rotate(45deg)"},"motion":{"values":{"y":[0,-10,0]},"timing":{"duration":1,"delay":0,"ease":"easeInOut"}}},{"tag":"div","style":{"width":"12px","height":"12px","backgroundColor":"var(--tx-text-color-primary)","borderRadius":"2px","transform":"rotate(45deg)","marginLeft":"8px"},"motion":{"values":{"y":[0,-10,0]},"timing":{"duration":1,"delay":0.2,"ease":"easeInOut"}}},{"tag":"div","style":{"width":"12px","height":"12px","backgroundColor":"var(--tx-text-color-primary)","borderRadius":"2px","transform":"rotate(45deg)","marginLeft":"8px"},"motion":{"values":{"y":[0,-10,0]},"timing":{"duration":1,"delay":0.4,"ease":"easeInOut"}}}]},
  // FluidDiamond: registry/ui/loading/fluid-diamond.tsx
  'fluid-diamond': {"tag":"div","style":{"width":"24px","height":"24px","backgroundColor":"var(--tx-text-color-primary)","borderRadius":"2px","transform":"rotate(45deg)"},"motion":{"values":{"scaleX":[1,1.5,1],"scaleY":[1,0.5,1]},"timing":{"duration":1.5,"ease":"easeInOut"}}},
  // HexagonSpinner: registry/ui/loading/hexagon-spinner.tsx
  'hexagon-spinner': {"tag":"svg","style":{"width":"40px","height":"40px","transformBox":"fill-box","transformOrigin":"center"},"attrs":{"viewBox":"0 0 50 50"},"children":[{"tag":"polygon","style":{"stroke":"var(--tx-fill-color-dark)","fill":"none","transformBox":"fill-box","transformOrigin":"center"},"attrs":{"points":"25,5 45,15 45,35 25,45 5,35 5,15","strokeWidth":"4"}},{"tag":"polygon","style":{"stroke":"var(--tx-text-color-primary)","fill":"none","transformBox":"fill-box","transformOrigin":"center"},"attrs":{"points":"25,5 45,15 45,35 25,45 5,35 5,15","strokeWidth":"4","strokeLinecap":"round","strokeDasharray":"120"},"motion":{"values":{"strokeDashoffset":[120,-120]},"timing":{"duration":2,"ease":"linear"}}}]},
  // Hourglass: registry/ui/loading/hourglass.tsx
  'hourglass': {"tag":"div","style":{"width":"32px","height":"40px","display":"flex","flexDirection":"column","alignItems":"center","justifyContent":"space-between"},"children":[{"tag":"div","style":{"width":"32px","height":"0px","borderTopWidth":"16px","borderTopStyle":"solid","borderTopColor":"var(--tx-text-color-primary)","borderLeftWidth":"16px","borderLeftStyle":"solid","borderLeftColor":"transparent","borderRightWidth":"16px","borderRightStyle":"solid","borderRightColor":"transparent","transformOrigin":"bottom"}},{"tag":"div","style":{"width":"32px","height":"0px","borderBottomWidth":"16px","borderBottomStyle":"solid","borderBottomColor":"var(--tx-text-color-primary)","borderLeftWidth":"16px","borderLeftStyle":"solid","borderLeftColor":"transparent","borderRightWidth":"16px","borderRightStyle":"solid","borderRightColor":"transparent","transformOrigin":"top"}}],"motion":{"values":{"rotate":[0,180,180,360,360]},"timing":{"duration":3,"ease":"easeInOut"}}},
  // InfinityPath: registry/ui/loading/infinity-path.tsx
  'infinity-path': {"tag":"svg","style":{"width":"48px","height":"24px","overflow":"visible","transformBox":"fill-box","transformOrigin":"center"},"attrs":{"viewBox":"0 0 60 30"},"children":[{"tag":"path","style":{"stroke":"var(--tx-fill-color-dark)","fill":"none","transformBox":"fill-box","transformOrigin":"center"},"attrs":{"d":"M 15 15 C 15 5, 25 5, 30 15 C 35 25, 45 25, 45 15 C 45 5, 35 5, 30 15 C 25 25, 15 25, 15 15","strokeWidth":"4","strokeLinecap":"round"}},{"tag":"path","style":{"stroke":"var(--tx-text-color-primary)","fill":"none","transformBox":"fill-box","transformOrigin":"center"},"attrs":{"d":"M 15 15 C 15 5, 25 5, 30 15 C 35 25, 45 25, 45 15 C 45 5, 35 5, 30 15 C 25 25, 15 25, 15 15","strokeWidth":"4","strokeLinecap":"round","strokeDasharray":"100"},"motion":{"values":{"strokeDashoffset":[100,-100]},"timing":{"duration":2,"ease":"linear"}}}]},
  // MatrixGridLoader: src/components/css-animations/whimsical/MatrixGridLoader.tsx
  'anim-matrix-loader': {"tag":"div","style":{"display":"grid","gridTemplateColumns":"repeat(2, 42px)","gap":"6px"},"children":[{"tag":"div","style":{"width":"42px","height":"42px","borderRadius":"8px","backgroundColor":"var(--tx-fill-color-dark)"},"motion":{"values":{"opacity":[0.25,0.55,0.8,1],"backgroundColor":["var(--tx-color-primary-dark-2)","var(--tx-color-primary)","var(--tx-color-primary-light-3)","var(--tx-color-primary-light-5)"]},"timing":{"duration":0.8,"ease":"easeInOut","times":[0,0.5,0.75,1],"delay":0.2}}},{"tag":"div","style":{"width":"42px","height":"42px","borderRadius":"8px","backgroundColor":"var(--tx-fill-color-dark)"},"motion":{"values":{"opacity":[0.25,0.55,0.8,1],"backgroundColor":["var(--tx-color-primary-dark-2)","var(--tx-color-primary)","var(--tx-color-primary-light-3)","var(--tx-color-primary-light-5)"]},"timing":{"duration":0.8,"ease":"easeInOut","times":[0,0.5,0.75,1],"delay":0.4}}},{"tag":"div","style":{"width":"42px","height":"42px","borderRadius":"8px","backgroundColor":"var(--tx-fill-color-dark)"},"motion":{"values":{"opacity":[0.25,0.55,0.8,1],"backgroundColor":["var(--tx-color-primary-dark-2)","var(--tx-color-primary)","var(--tx-color-primary-light-3)","var(--tx-color-primary-light-5)"]},"timing":{"duration":0.8,"ease":"easeInOut","times":[0,0.5,0.75,1],"delay":0.8}}},{"tag":"div","style":{"width":"42px","height":"42px","borderRadius":"8px","backgroundColor":"var(--tx-fill-color-dark)"},"motion":{"values":{"opacity":[0.25,0.55,0.8,1],"backgroundColor":["var(--tx-color-primary-dark-2)","var(--tx-color-primary)","var(--tx-color-primary-light-3)","var(--tx-color-primary-light-5)"]},"timing":{"duration":0.8,"ease":"easeInOut","times":[0,0.5,0.75,1],"delay":0.6}}}]},
  // MinimalTriangle: registry/ui/loading/minimal-triangle.tsx
  'minimal-triangle': {"tag":"svg","style":{"width":"40px","height":"40px","overflow":"visible","transformBox":"fill-box","transformOrigin":"center"},"attrs":{"viewBox":"0 0 50 50"},"children":[{"tag":"polygon","style":{"stroke":"var(--tx-fill-color-dark)","fill":"none","transformBox":"fill-box","transformOrigin":"center"},"attrs":{"points":"25,5 45,40 5,40","strokeWidth":"3"}},{"tag":"polygon","style":{"stroke":"var(--tx-text-color-primary)","fill":"none","transformBox":"fill-box","transformOrigin":"center"},"attrs":{"points":"25,5 45,40 5,40","strokeWidth":"3","strokeDasharray":"120"},"motion":{"values":{"strokeDashoffset":[120,0,-120]},"timing":{"duration":2,"ease":"easeInOut"}}}]},
  // MorphLoader: registry/ui/loading/morph-loader.tsx
  'morph-loader': {"tag":"div","style":{"position":"relative","display":"flex","alignItems":"center","justifyContent":"center","width":40,"height":40},"children":[{"tag":"div","style":{"borderRadius":"16px","backgroundColor":"var(--tx-color-primary)","boxShadow":"var(--tx-elevation-3)","width":40,"height":40},"motion":{"values":{"borderRadius":["25%","50%","50%","25%","25%"],"rotate":[0,90,180,270,360],"scale":[1,0.8,1.1,0.8,1]},"timing":{"duration":2.2,"ease":"easeInOut"}}}]},
  // MorphingShape: registry/ui/loading/morphing-shape.tsx
  'morphing-shape': {"tag":"div","style":{"width":"40px","height":"40px","backgroundColor":"var(--tx-text-color-primary)","boxShadow":"var(--tx-elevation-1)"},"motion":{"values":{"borderRadius":["10%","50%","10%"],"rotate":[0,90,180],"scale":[1,0.8,1]},"timing":{"duration":2,"ease":"easeInOut"}}},
  // OrigamiShape: registry/ui/loading/origami-shape.tsx
  'origami-shape': {"tag":"div","style":{"position":"relative","width":"40px","height":"40px"},"children":[{"tag":"div","style":{"position":"absolute","top":"0px","left":"0px","width":"20px","height":"20px","backgroundColor":"var(--tx-text-color-primary)","borderTopLeftRadius":"6px","transformOrigin":"right"},"motion":{"values":{"rotateY":[0,180,0]},"timing":{"duration":2,"ease":"easeInOut"}}},{"tag":"div","style":{"position":"absolute","bottom":"0px","right":"0px","width":"20px","height":"20px","backgroundColor":"var(--tx-text-color-secondary)","borderBottomRightRadius":"6px","transformOrigin":"left"},"motion":{"values":{"rotateY":[0,180,0]},"timing":{"duration":2,"ease":"easeInOut"}}}]},
  // Pendulum: registry/ui/loading/pendulum.tsx
  'pendulum': {"tag":"div","style":{"position":"relative","width":"64px","height":"48px","display":"flex","alignItems":"flex-start","justifyContent":"center"},"children":[{"tag":"div","style":{"width":"100%","height":"4px","backgroundColor":"var(--tx-fill-color-dark)","borderRadius":"999px","borderBottomLeftRadius":"0","borderBottomRightRadius":"0","position":"absolute","top":"0px"}},{"tag":"div","style":{"position":"absolute","top":"0px","width":"4px","backgroundColor":"var(--tx-text-color-primary)","transformOrigin":"top","display":"flex","flexDirection":"column","alignItems":"center"},"children":[{"tag":"div","style":{"width":"4px","height":"32px","backgroundColor":"var(--tx-text-color-primary)"}},{"tag":"div","style":{"width":"16px","height":"16px","backgroundColor":"var(--tx-text-color-primary)","borderRadius":"999px"}}],"motion":{"values":{"rotate":[-45,45,-45]},"timing":{"duration":1.5,"ease":"easeInOut"}}}]},
  // PulseSquare: registry/ui/loading/pulse-square.tsx
  'pulse-square': {"tag":"div","style":{"width":"32px","height":"32px","borderWidth":"4px","borderStyle":"solid","borderColor":"var(--tx-text-color-primary)","borderRadius":"6px"},"motion":{"values":{"scale":[1,1.2,1],"opacity":[1,0.3,1],"borderRadius":["20%","50%","20%"]},"timing":{"duration":1.5,"ease":"easeInOut"}}},
  // PumpingHeart: registry/ui/loading/pumping-heart.tsx
  'pumping-heart': {"tag":"div","style":{"width":"32px","height":"32px"},"children":[{"tag":"svg","style":{"fill":"var(--tx-text-color-primary)","transformBox":"fill-box","transformOrigin":"center"},"attrs":{"viewBox":"0 0 24 24"},"children":[{"tag":"path","style":{"transformBox":"fill-box","transformOrigin":"center"},"attrs":{"d":"M12 21.35l-1.45-1.32C5.4 15.36 2 12.28 2 8.5 2 5.42 4.42 3 7.5 3c1.74 0 3.41.81 4.5 2.09C13.09 3.81 14.76 3 16.5 3 19.58 3 22 5.42 22 8.5c0 3.78-3.4 6.86-8.55 11.54L12 21.35z"}}]}],"motion":{"values":{"scale":[1,1.25,1,1.25,1]},"timing":{"duration":1.5,"ease":"easeInOut"}}},
  // RotatingCross: registry/ui/loading/rotating-cross.tsx
  'rotating-cross': {"tag":"div","style":{"position":"relative","width":"32px","height":"32px","display":"flex","alignItems":"center","justifyContent":"center"},"children":[{"tag":"div","style":{"position":"absolute","width":"100%","height":"6px","backgroundColor":"var(--tx-text-color-primary)","borderRadius":"2px"}},{"tag":"div","style":{"position":"absolute","height":"100%","width":"6px","backgroundColor":"var(--tx-text-color-primary)","borderRadius":"2px"}}],"motion":{"values":{"rotate":180},"timing":{"duration":0.8,"ease":"easeInOut"}}},
  // RotatingTriangle: registry/ui/loading/rotating-triangle.tsx
  'rotating-triangle': {"tag":"svg","style":{"width":"40px","height":"40px","overflow":"visible","transformBox":"fill-box","transformOrigin":"center"},"attrs":{"viewBox":"0 0 50 50"},"children":[{"tag":"polygon","style":{"stroke":"var(--tx-text-color-primary)","fill":"none","transformOrigin":"center","transformBox":"fill-box"},"attrs":{"points":"25,5 45,40 5,40","strokeWidth":"4","strokeLinejoin":"round"},"motion":{"values":{"rotate":360},"timing":{"duration":2,"ease":"linear"}}}]},
  // ShapeShiftGrid: registry/ui/loading/shape-shift-grid.tsx
  'shape-shift-grid': {"tag":"div","style":{"display":"grid","gridTemplateColumns":"repeat(2, minmax(0, 1fr))","gap":"4px","width":"32px","height":"32px"},"children":[{"tag":"div","style":{"width":"100%","height":"100%","backgroundColor":"var(--tx-text-color-primary)"},"motion":{"values":{"borderRadius":["10%","50%","10%"],"scale":[1,0.8,1]},"timing":{"duration":1.5,"delay":0,"ease":"easeInOut"}}},{"tag":"div","style":{"width":"100%","height":"100%","backgroundColor":"var(--tx-text-color-primary)"},"motion":{"values":{"borderRadius":["10%","50%","10%"],"scale":[1,0.8,1]},"timing":{"duration":1.5,"delay":0.1,"ease":"easeInOut"}}},{"tag":"div","style":{"width":"100%","height":"100%","backgroundColor":"var(--tx-text-color-primary)"},"motion":{"values":{"borderRadius":["10%","50%","10%"],"scale":[1,0.8,1]},"timing":{"duration":1.5,"delay":0.2,"ease":"easeInOut"}}},{"tag":"div","style":{"width":"100%","height":"100%","backgroundColor":"var(--tx-text-color-primary)"},"motion":{"values":{"borderRadius":["10%","50%","10%"],"scale":[1,0.8,1]},"timing":{"duration":1.5,"delay":0.3,"ease":"easeInOut"}}}]},
  // SmoothRoundedSquare: registry/ui/loading/smooth-rounded-square.tsx
  'smooth-rounded-square': {"tag":"div","style":{"width":"40px","height":"40px","borderWidth":"3px","borderStyle":"solid","borderColor":"var(--tx-text-color-primary)"},"motion":{"values":{"borderRadius":["10%","50%","10%"]},"timing":{"duration":2,"ease":"easeInOut"}}},
  // SpinningSquares: registry/ui/loading/spinning-squares.tsx
  'spinning-squares': {"tag":"div","style":{"position":"relative","width":"40px","height":"40px"},"children":[{"tag":"div","style":{"position":"absolute","top":"0px","left":"0px","width":"16px","height":"16px","backgroundColor":"var(--tx-text-color-primary)","borderRadius":"2px"},"motion":{"values":{"x":[0,24,24,0,0],"y":[0,0,24,24,0]},"timing":{"duration":2,"ease":"easeInOut"}}},{"tag":"div","style":{"position":"absolute","bottom":"0px","right":"0px","width":"16px","height":"16px","backgroundColor":"var(--tx-border-color)","borderRadius":"2px"},"motion":{"values":{"x":[0,-24,-24,0,0],"y":[0,0,-24,-24,0]},"timing":{"duration":2,"ease":"easeInOut"}}}]},
  // SpringHexagon: registry/ui/loading/spring-hexagon.tsx
  'spring-hexagon': {"tag":"svg","style":{"width":"40px","height":"40px","transformBox":"fill-box","transformOrigin":"center"},"attrs":{"viewBox":"0 0 50 50"},"children":[{"tag":"polygon","style":{"fill":"var(--tx-text-color-primary)","transformBox":"fill-box","transformOrigin":"center"},"attrs":{"points":"25,5 45,15 45,35 25,45 5,35 5,15"}}],"motion":{"values":{"scale":[1,1.15,1],"rotate":[0,60,60]},"timing":{"duration":2,"type":"spring","bounce":0.3}}},
  // SquareAccordion: registry/ui/loading/square-accordion.tsx
  'square-accordion': {"tag":"div","style":{"display":"flex","width":"48px","height":"48px","justifyContent":"center","alignItems":"center"},"children":[{"tag":"div","style":{"width":"12px","backgroundColor":"var(--tx-text-color-primary)","borderRadius":"2px"},"motion":{"values":{"height":[12,32,12]},"timing":{"duration":1.5,"delay":0,"ease":"easeInOut"}}},{"tag":"div","style":{"width":"12px","backgroundColor":"var(--tx-text-color-primary)","borderRadius":"2px","marginLeft":"4px"},"motion":{"values":{"height":[12,32,12]},"timing":{"duration":1.5,"delay":0.2,"ease":"easeInOut"}}},{"tag":"div","style":{"width":"12px","backgroundColor":"var(--tx-text-color-primary)","borderRadius":"2px","marginLeft":"4px"},"motion":{"values":{"height":[12,32,12]},"timing":{"duration":1.5,"delay":0.4,"ease":"easeInOut"}}}]},
  // SquareGrid: registry/ui/loading/square-grid.tsx
  'square-grid': {"tag":"div","style":{"display":"grid","gridTemplateColumns":"repeat(2, minmax(0, 1fr))","gap":"6px"},"children":[{"tag":"div","style":{"width":"16px","height":"16px","backgroundColor":"var(--tx-text-color-primary)","borderRadius":"2px"},"motion":{"values":{"scale":[1,0.5,1],"opacity":[1,0.3,1]},"timing":{"duration":1.5,"delay":0,"ease":"easeInOut"}}},{"tag":"div","style":{"width":"16px","height":"16px","backgroundColor":"var(--tx-text-color-primary)","borderRadius":"2px"},"motion":{"values":{"scale":[1,0.5,1],"opacity":[1,0.3,1]},"timing":{"duration":1.5,"delay":0.2,"ease":"easeInOut"}}},{"tag":"div","style":{"width":"16px","height":"16px","backgroundColor":"var(--tx-text-color-primary)","borderRadius":"2px"},"motion":{"values":{"scale":[1,0.5,1],"opacity":[1,0.3,1]},"timing":{"duration":1.5,"delay":0.4,"ease":"easeInOut"}}},{"tag":"div","style":{"width":"16px","height":"16px","backgroundColor":"var(--tx-text-color-primary)","borderRadius":"2px"},"motion":{"values":{"scale":[1,0.5,1],"opacity":[1,0.3,1]},"timing":{"duration":1.5,"delay":0.6,"ease":"easeInOut"}}}]},
  // SquareSnake: registry/ui/loading/square-snake.tsx
  'square-snake': {"tag":"div","style":{"display":"grid","gridTemplateColumns":"repeat(3, minmax(0, 1fr))","gap":"4px","width":"40px","height":"40px"},"children":[{"tag":"div","style":{"backgroundColor":"var(--tx-text-color-primary)","borderRadius":"2px","width":"100%","height":"100%"},"motion":{"values":{"opacity":[0.1,1,0.1]},"timing":{"duration":1.5,"delay":0,"ease":"easeInOut"}}},{"tag":"div","style":{"backgroundColor":"var(--tx-text-color-primary)","borderRadius":"2px","width":"100%","height":"100%"},"motion":{"values":{"opacity":[0.1,1,0.1]},"timing":{"duration":1.5,"delay":0.15,"ease":"easeInOut"}}},{"tag":"div","style":{"backgroundColor":"var(--tx-text-color-primary)","borderRadius":"2px","width":"100%","height":"100%"},"motion":{"values":{"opacity":[0.1,1,0.1]},"timing":{"duration":1.5,"delay":0.3,"ease":"easeInOut"}}},{"tag":"div","style":{"backgroundColor":"var(--tx-text-color-primary)","borderRadius":"2px","width":"100%","height":"100%"},"motion":{"values":{"opacity":[0.1,1,0.1]},"timing":{"duration":1.5,"delay":0.15,"ease":"easeInOut"}}},{"tag":"div","style":{"backgroundColor":"var(--tx-text-color-primary)","borderRadius":"2px","width":"100%","height":"100%"},"motion":{"values":{"opacity":[0.1,1,0.1]},"timing":{"duration":1.5,"delay":0.3,"ease":"easeInOut"}}},{"tag":"div","style":{"backgroundColor":"var(--tx-text-color-primary)","borderRadius":"2px","width":"100%","height":"100%"},"motion":{"values":{"opacity":[0.1,1,0.1]},"timing":{"duration":1.5,"delay":0.45,"ease":"easeInOut"}}},{"tag":"div","style":{"backgroundColor":"var(--tx-text-color-primary)","borderRadius":"2px","width":"100%","height":"100%"},"motion":{"values":{"opacity":[0.1,1,0.1]},"timing":{"duration":1.5,"delay":0.3,"ease":"easeInOut"}}},{"tag":"div","style":{"backgroundColor":"var(--tx-text-color-primary)","borderRadius":"2px","width":"100%","height":"100%"},"motion":{"values":{"opacity":[0.1,1,0.1]},"timing":{"duration":1.5,"delay":0.45,"ease":"easeInOut"}}},{"tag":"div","style":{"backgroundColor":"var(--tx-text-color-primary)","borderRadius":"2px","width":"100%","height":"100%"},"motion":{"values":{"opacity":[0.1,1,0.1]},"timing":{"duration":1.5,"delay":0.6,"ease":"easeInOut"}}}]},
  // SquareSpinner: registry/ui/loading/square-spinner.tsx
  'square-spinner': {"tag":"div","style":{"width":"32px","height":"32px","borderWidth":"2px","borderStyle":"solid","borderColor":"var(--tx-text-color-primary)","display":"flex","alignItems":"center","justifyContent":"center"},"children":[{"tag":"div","style":{"width":"8px","height":"8px","backgroundColor":"var(--tx-text-color-primary)"}}],"motion":{"values":{"rotate":90},"timing":{"duration":0.6,"ease":"easeInOut"}}},
  // WanderingCube: registry/ui/loading/wandering-cube.tsx
  'wandering-cube': {"tag":"div","style":{"position":"relative","width":"40px","height":"40px"},"children":[{"tag":"div","style":{"position":"absolute","top":"0px","left":"0px","width":"16px","height":"16px","backgroundColor":"var(--tx-text-color-primary)","borderRadius":"2px"},"motion":{"values":{"x":[0,24,24,0,0],"y":[0,0,24,24,0],"rotate":[0,-90,-180,-270,-360]},"timing":{"duration":2.5,"ease":"easeInOut"}}}]},
}
