// Ported from Amicro, commit 43c29ce9cdd16459e3eab4992381b8d35b38776a.
// MIT License. Copyright (c) 2026 SYED  SUBHAN UDDIN.
import type { LoaderNode } from '../scene-types'
import type { MotionLoaderVariant } from '../types'

/** Icon hosts, scans, cards, skeletons and shimmer surfaces. */
export const SURFACE_SCENES: Record<Extract<MotionLoaderVariant, "app-icon-load" | "dynamic-island" | "face-id-scan" | "fluid-skeleton" | "glassmorphic-card" | "shimmer-line" | "skeleton" | "skeleton-loader">, LoaderNode> = {
  // AppIconLoad: registry/ui/loading/app-icon-load.tsx
  'app-icon-load': {"tag":"div","style":{"position":"relative","width":"48px","height":"48px","backgroundColor":"var(--tx-fill-color-dark)","borderRadius":"12px","display":"flex","alignItems":"center","justifyContent":"center","overflow":"hidden"},"children":[{"tag":"svg","style":{"width":"32px","height":"32px","position":"absolute","transformBox":"fill-box","transformOrigin":"center"},"attrs":{"viewBox":"0 0 50 50"},"children":[{"tag":"circle","style":{"stroke":"var(--tx-border-color)","fill":"none","transformBox":"fill-box","transformOrigin":"center"},"attrs":{"cx":"25","cy":"25","r":"20","strokeWidth":"4"}},{"tag":"circle","style":{"stroke":"var(--tx-text-color-primary)","fill":"none","transformOrigin":"center","transform":"rotate(-90deg)","transformBox":"fill-box"},"attrs":{"cx":"25","cy":"25","r":"20","strokeWidth":"4","strokeDasharray":"125"},"motion":{"values":{"strokeDashoffset":[125,0]},"timing":{"duration":2,"ease":"easeInOut"}}}]}]},
  // DynamicIsland: registry/ui/loading/dynamic-island.tsx
  'dynamic-island': {"tag":"div","style":{"backgroundColor":"var(--tx-text-color-primary)","borderWidth":"1px","borderStyle":"solid","borderColor":"color-mix(in srgb, var(--tx-text-color-primary) 10%, transparent)","borderRadius":"999px","display":"flex","alignItems":"center","justifyContent":"center","paddingLeft":"16px","paddingRight":"16px","paddingTop":"8px","paddingBottom":"8px","gap":"12px","height":"32px","boxShadow":"var(--tx-elevation-1)"},"children":[{"tag":"div","style":{"width":"6px","height":"6px","borderRadius":"999px","backgroundColor":"var(--tx-color-success)"},"motion":{"values":{"opacity":[0.4,1,0.4]},"timing":{"duration":1.1,"ease":"easeInOut"}}},{"tag":"div","style":{"display":"flex","gap":"4px","alignItems":"center","height":"8px"},"children":[{"tag":"div","style":{"width":"2px","backgroundColor":"var(--tx-border-color)","borderRadius":"999px"},"motion":{"values":{"height":[3,8,3]},"timing":{"duration":0.8,"ease":"easeInOut","delay":0}}},{"tag":"div","style":{"width":"2px","backgroundColor":"var(--tx-border-color)","borderRadius":"999px"},"motion":{"values":{"height":[3,8,3]},"timing":{"duration":0.8,"ease":"easeInOut","delay":0.15}}},{"tag":"div","style":{"width":"2px","backgroundColor":"var(--tx-border-color)","borderRadius":"999px"},"motion":{"values":{"height":[3,8,3]},"timing":{"duration":0.8,"ease":"easeInOut","delay":0.3}}}]}],"motion":{"values":{"width":[80,110,80]},"timing":{"duration":2.2,"ease":"easeInOut"}}},
  // FaceIDScan: registry/ui/loading/face-id-scan.tsx
  'face-id-scan': {"tag":"div","style":{"width":"48px","height":"48px","borderWidth":"2px","borderStyle":"solid","borderColor":"var(--tx-border-color)","borderRadius":"12px","position":"relative","overflow":"hidden","display":"flex","alignItems":"center","justifyContent":"center"},"children":[{"tag":"svg","style":{"width":"24px","height":"24px","fill":"var(--tx-border-color)","transformBox":"fill-box","transformOrigin":"center"},"attrs":{"viewBox":"0 0 24 24"},"children":[{"tag":"path","style":{"transformBox":"fill-box","transformOrigin":"center"},"attrs":{"d":"M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm0 18c-4.41 0-8-3.59-8-8s3.59-8 8-8 8 3.59 8 8-3.59 8-8 8z"}}]},{"tag":"div","style":{"position":"absolute","left":"0px","width":"100%","height":"32px","borderColor":"var(--tx-color-success)","backgroundImage":"linear-gradient(to bottom, transparent, color-mix(in srgb, var(--tx-color-success) 30%, transparent))","borderBottomWidth":"1px","borderBottomStyle":"solid"},"motion":{"values":{"top":["-100%","100%","-100%"]},"timing":{"duration":2.5,"ease":"linear"}}}]},
  // FluidSkeleton: registry/ui/loading/fluid-skeleton.tsx
  'fluid-skeleton': {"tag":"div","style":{"width":"96px","height":"40px","borderRadius":"12px","overflow":"hidden","position":"relative"},"children":[{"tag":"skeleton","attrs":{"width":"96px","height":"40px","radius":"12px","variant":"rect"}},{"tag":"div","style":{"position":"absolute","left":"0px","bottom":"0px","right":"0px","top":"0px","backgroundImage":"linear-gradient(to right, transparent, color-mix(in srgb, var(--tx-bg-color) 60%, transparent), transparent)"},"motion":{"values":{"x":["-100%","200%"]},"timing":{"duration":1.5,"ease":"linear"}}}]},
  // GlassmorphicCard: registry/ui/loading/glassmorphic-card.tsx
  'glassmorphic-card': {"tag":"div","style":{"width":"80px","height":"64px","backgroundColor":"var(--tx-fill-color-light)","backdropFilter":"blur(12px)","borderWidth":"1px","borderStyle":"solid","borderColor":"color-mix(in srgb, var(--tx-bg-color) 50%, transparent)","borderRadius":"16px","boxShadow":"var(--tx-elevation-1)","display":"flex","alignItems":"center","justifyContent":"center","position":"relative","overflow":"hidden"},"children":[{"tag":"div","style":{"position":"absolute","width":"48px","height":"48px","backgroundColor":"var(--tx-border-color)","borderRadius":"999px","filter":"blur(24px)","zIndex":-10},"motion":{"values":{"x":[-20,20,-20],"y":[-10,10,-10]},"timing":{"duration":3,"ease":"easeInOut"}}},{"tag":"div","style":{"width":"20px","height":"20px","borderWidth":"2px","borderStyle":"solid","borderColor":"var(--tx-text-color-primary)","borderTopColor":"transparent","borderRadius":"999px"},"motion":{"values":{"rotate":360},"timing":{"duration":1,"ease":"linear"}}}]},
  // ShimmerLine: registry/ui/loading/shimmer-line.tsx
  'shimmer-line': {"tag":"div","style":{"width":"96px","height":"4px","backgroundColor":"var(--tx-fill-color-dark)","borderRadius":"999px","overflow":"hidden","position":"relative"},"children":[{"tag":"div","style":{"position":"absolute","top":"0px","left":"0px","bottom":"0px","width":"33.33333333333333%","backgroundColor":"var(--tx-text-color-primary)","borderRadius":"999px"},"motion":{"values":{"x":["-100%","300%"]},"timing":{"duration":1.5,"ease":"easeInOut"}}}]},
  // Skeleton: registry/ui/loading/skeleton.tsx
  'skeleton': {"tag":"div","style":{"position":"relative","overflow":"hidden","borderRadius":"6px","width":"96px","height":"40px"},"children":[{"tag":"skeleton","attrs":{"width":"96px","height":"40px","radius":"6px","variant":"rect"}},{"tag":"div","style":{"position":"absolute","left":"0px","bottom":"0px","right":"0px","top":"0px","width":"80%","height":"100%","background":"linear-gradient(90deg, color-mix(in srgb, var(--tx-bg-color) 0%, transparent) 0%, color-mix(in srgb, var(--tx-bg-color) 5%, transparent) 50%, color-mix(in srgb, var(--tx-bg-color) 0%, transparent) 100%)"},"motion":{"values":{"x":"150%"},"timing":{"duration":1.6,"ease":"easeInOut"},"initial":{"x":"-150%"}}}]},
  // SkeletonLoader: registry/ui/loading/skeleton-loader.tsx
  'skeleton-loader': {"tag":"div","style":{"width":"120px","maxWidth":"120px"},"children":[{"tag":"div","style":{"display":"flex","alignItems":"center"},"children":[{"tag":"div","style":{"width":"32px","height":"32px","borderRadius":"999px","flexShrink":0},"motion":{"values":{"opacity":[0.5,1,0.5]},"timing":{"duration":1.5,"ease":"easeInOut"}},"children":[{"tag":"skeleton","attrs":{"width":"32px","height":"32px","radius":"999px","variant":"circle"}}]},{"tag":"div","style":{"height":"12px","borderRadius":"999px","width":"100%","marginLeft":"8px"},"motion":{"values":{"opacity":[0.5,1,0.5]},"timing":{"duration":1.5,"ease":"easeInOut","delay":0.2}},"children":[{"tag":"skeleton","attrs":{"width":"100%","height":"12px","radius":"999px","variant":"circle"}}]}]},{"tag":"div","style":{"height":"8px","borderRadius":"999px","width":"100%","marginTop":"8px"},"motion":{"values":{"opacity":[0.5,1,0.5]},"timing":{"duration":1.5,"ease":"easeInOut","delay":0.4}},"children":[{"tag":"skeleton","attrs":{"width":"100%","height":"8px","radius":"999px","variant":"circle"}}]},{"tag":"div","style":{"height":"8px","borderRadius":"999px","width":"80%","marginTop":"8px"},"motion":{"values":{"opacity":[0.5,1,0.5]},"timing":{"duration":1.5,"ease":"easeInOut","delay":0.6}},"children":[{"tag":"skeleton","attrs":{"width":"80%","height":"8px","radius":"999px","variant":"circle"}}]}]},
}
