// Ported from Amicro, commit 43c29ce9cdd16459e3eab4992381b8d35b38776a.
// MIT License. Copyright (c) 2026 SYED  SUBHAN UDDIN.
import type { LoaderNode } from '../scene-types'
import type { MotionLoaderVariant } from '../types'

/** Localized status text, character reveals and terminal cursors. */
export const TEXT_SCENES: Record<Extract<MotionLoaderVariant, "apple-text-reveal" | "apple-unlock" | "mac-terminal" | "spring-text-pop" | "terminal-loader" | "text-blink" | "text-dots" | "text-morph" | "text-shimmer" | "text-shimmer-wave">, LoaderNode> = {
  // AppleTextReveal: registry/ui/loading/apple-text-reveal.tsx
  'apple-text-reveal': {"tag":"div","style":{"fontWeight":500,"fontSize":"14px","color":"var(--tx-text-color-primary)","overflow":"hidden","height":"24px","position":"relative"},"children":[{"tag":"div","style":{},"children":[{"label":"loading"}],"motion":{"values":{"y":["100%","0%","-100%"]},"timing":{"duration":2,"ease":"easeInOut"}}}]},
  // AppleUnlock: registry/ui/loading/apple-unlock.tsx
  'apple-unlock': {"tag":"div","style":{"position":"relative","fontWeight":500,"fontSize":"14px","userSelect":"none"},"children":[{"tag":"span","style":{"color":"var(--tx-text-color-placeholder)"},"children":[{"label":"unlock"}]},{"tag":"div","style":{"position":"absolute","left":"0px","bottom":"0px","right":"0px","top":"0px","color":"transparent","backgroundClip":"text","WebkitBackgroundClip":"text","backgroundImage":"linear-gradient(to right, transparent, var(--tx-text-color-primary), transparent)","backgroundSize":"200% 100%"},"children":[{"label":"unlock"}],"motion":{"values":{"backgroundPosition":["200% 0","-200% 0"]},"timing":{"duration":2.2,"ease":"linear"}}}]},
  // MacTerminal: registry/ui/loading/mac-terminal.tsx
  'mac-terminal': {"tag":"div","style":{"display":"flex","alignItems":"center","color":"var(--tx-text-color-primary)","fontFamily":"var(--tx-font-family-mono, monospace)","fontSize":"14px"},"children":[{"tag":"span","style":{},"children":["~ %"]},{"tag":"span","style":{"marginLeft":"6px","width":"8px","height":"16px","backgroundColor":"var(--tx-text-color-primary)","display":"inline-block"},"motion":{"values":{"opacity":[1,0,1]},"timing":{"duration":1,"ease":"linear"}}}]},
  // SpringTextPop: registry/ui/loading/spring-text-pop.tsx
  'spring-text-pop': {"tag":"div","style":{"display":"flex","fontWeight":500,"fontSize":"14px","color":"var(--tx-text-color-primary)"},"children":[{"tag":"span","style":{"transformOrigin":"bottom","display":"inline-block"},"children":[],"motion":{"values":{"y":[0,-6,0]},"timing":{"duration":1.2,"ease":"easeInOut","delay":0}}}],"characters":"loading","characterDelay":0.08,"characterSuffix":"..."},
  // TerminalLoader: registry/ui/loading/terminal-loader.tsx
  'terminal-loader': {"tag":"div","style":{"backgroundColor":"var(--tx-text-color-primary)","color":"var(--tx-fill-color-light)","fontFamily":"var(--tx-font-family-mono, monospace)","fontSize":"13px","padding":"12px","borderRadius":"6px","width":"100%","height":"64px","display":"flex","flexDirection":"column","justifyContent":"flex-end","overflow":"hidden","boxShadow":"var(--tx-elevation-1)"},"children":[{"tag":"div","style":{"display":"flex","color":"var(--tx-text-color-secondary)","marginBottom":"4px","lineHeight":1},"children":[{"tag":"span","style":{},"children":["$"]},{"tag":"span","style":{"marginLeft":"8px"},"children":[{"label":"terminal"}]}]},{"tag":"div","style":{"display":"flex","alignItems":"center","lineHeight":1},"children":[{"tag":"span","style":{"color":"var(--tx-color-success)"},"children":[">"]},{"tag":"span","style":{"marginLeft":"8px","width":"6px","height":"10px","backgroundColor":"var(--tx-fill-color-light)","display":"block"},"motion":{"values":{"opacity":[1,0,1]},"timing":{"duration":0.8,"ease":"linear"}}}]}]},
  // TextBlink: registry/ui/loading/text-blink.tsx
  'text-blink': {"tag":"div","style":{"color":"var(--tx-text-color-primary)","fontWeight":500,"fontSize":"14px"},"children":[{"label":"thinking"}],"motion":{"values":{"opacity":[1,0.2,1]},"timing":{"duration":1.5,"ease":"easeInOut"}}},
  // TextDots: registry/ui/loading/text-dots.tsx
  'text-dots': {"tag":"div","style":{"fontWeight":500,"fontSize":"14px","color":"var(--tx-text-color-primary)","display":"flex","width":"96px"},"children":[{"tag":"span","style":{},"children":[{"label":"thinking"}]},{"tag":"span","style":{"display":"flex","width":"24px","paddingLeft":"2px"},"children":[{"tag":"span","style":{},"children":["."],"motion":{"values":{"opacity":[0,1,1,0]},"timing":{"duration":2,"times":[0,0.2,0.8,1]}}},{"tag":"span","style":{},"children":["."],"motion":{"values":{"opacity":[0,0,1,0]},"timing":{"duration":2,"times":[0,0.4,0.8,1]}}},{"tag":"span","style":{},"children":["."],"motion":{"values":{"opacity":[0,0,1,0]},"timing":{"duration":2,"times":[0,0.6,0.8,1]}}}]}]},
  // TextMorph: registry/ui/loading/text-morph.tsx
  'text-morph': {"tag":"div","style":{"position":"relative","height":"24px","width":"96px","display":"flex","alignItems":"center","justifyContent":"center","fontWeight":500,"fontSize":"14px","color":"var(--tx-text-color-primary)","overflow":"hidden"},"children":[{"tag":"div","style":{"position":"absolute"},"children":[{"label":"loading"}],"motion":{"values":{"opacity":[1,0,0,1],"y":[0,-16,16,0]},"timing":{"duration":3,"ease":"easeInOut"}}},{"tag":"div","style":{"position":"absolute"},"children":[{"label":"waiting"}],"motion":{"values":{"opacity":[0,1,1,0],"y":[16,0,0,-16]},"timing":{"duration":3,"ease":"easeInOut"}}}]},
  // TextShimmer: registry/ui/loading/text-shimmer.tsx
  'text-shimmer': {"tag":"div","style":{"position":"relative","color":"var(--tx-fill-color-dark)","fontWeight":500,"fontSize":"14px"},"children":[{"label":"thinking"},{"tag":"div","style":{"position":"absolute","left":"0px","bottom":"0px","right":"0px","top":"0px","color":"var(--tx-text-color-primary)","WebkitMaskImage":"linear-gradient(90deg, transparent 0%, black 50%, transparent 100%)","WebkitMaskSize":"200% 100%"},"children":[{"label":"thinking"}],"motion":{"values":{"WebkitMaskPosition":["100% 0%","-100% 0%"]},"timing":{"duration":1.5,"ease":"linear"}}}]},
  // TextShimmerWave: registry/ui/loading/text-shimmer-wave.tsx
  'text-shimmer-wave': {"tag":"div","style":{"display":"flex","fontWeight":500,"fontSize":"14px"},"children":[{"tag":"span","style":{"color":"var(--tx-text-color-primary)"},"children":[],"motion":{"values":{"opacity":[0.3,1,0.3],"y":[0,-2,0]},"timing":{"duration":1.5,"delay":0,"ease":"easeInOut"}}}],"characters":"thinking","characterDelay":0.1,"characterSuffix":""},
}
