/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ProviderConfigModal: typeof import('./src/components/ProviderConfigModal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheCounter: typeof import('./src/components/TheCounter.vue')['default']
    TheFooter: typeof import('./src/components/TheFooter.vue')['default']
    TheInput: typeof import('./src/components/TheInput.vue')['default']
    TranslationCard: typeof import('./src/components/TranslationCard.vue')['default']
  }
}

// For TSX support
declare global {
  const ProviderConfigModal: typeof import('./src/components/ProviderConfigModal.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const TheCounter: typeof import('./src/components/TheCounter.vue')['default']
  const TheFooter: typeof import('./src/components/TheFooter.vue')['default']
  const TheInput: typeof import('./src/components/TheInput.vue')['default']
  const TranslationCard: typeof import('./src/components/TranslationCard.vue')['default']
}