import antfu from '@antfu/eslint-config'

export default antfu(
  {
    type: 'lib',
    vue: true,
    typescript: true,
    stylistic: false,
    unicorn: false,
    test: false,
    markdown: false,
    regexp: false,
    lessOpinionated: true,
    jsonc: false,
    yaml: false,
    toml: false,
    ignores: [
      '**/dist/**',
      '**/node_modules/**',
      'docs/**',
      'packages/**/dist/**',
      'packages/**/coverage/**',
      'packages/**/.vitepress/cache/**',
    ],
  },
  {
    rules: {
      'import/consistent-type-specifier-style': 'off',
      'import/first': 'off',
      'no-console': 'off',
      'no-unsafe-finally': 'off',
      'no-restricted-globals': 'off',
      'no-unused-expressions': 'off',
      'node/prefer-global/process': 'off',
      'prefer-exponentiation-operator': 'off',
      'prefer-template': 'off',
      'perfectionist/sort-exports': 'off',
      'perfectionist/sort-imports': 'off',
      'perfectionist/sort-named-exports': 'off',
      'perfectionist/sort-named-imports': 'off',
      'ts/ban-ts-comment': 'off',
      'ts/consistent-type-definitions': 'off',
      'ts/explicit-function-return-type': 'off',
      'ts/no-empty-object-type': 'off',
      'ts/no-namespace': 'off',
      'ts/no-unused-expressions': 'off',
      'ts/no-require-imports': 'off',
      'ts/no-unsafe-function-type': 'off',
      'ts/no-use-before-define': 'off',
      'unused-imports/no-unused-vars': 'off',
      'vue/block-order': 'off',
      'vue/custom-event-name-casing': 'off',
      'vue/define-macros-order': 'off',
      'vue/prefer-separate-static-class': 'off',
      'vue/attributes-order': 'off',
      'vue/html-self-closing': 'off',
      'vue/html-indent': 'off',
      'vue/no-unused-vars': 'off',
      'vue/require-default-prop': 'off',
      'vue/no-parsing-error': 'off',
      'vue/valid-template-root': 'off',
    },
  },
)
