name: Build and Release

on:
  # 手动触发
  workflow_dispatch:
    inputs:
      release_type:
        description: 'Release type'
        required: true
        default: 'snapshot'
        type: choice
        options:
          - snapshot
          - release
      version:
        description: 'Version number (e.g. 1.0.0)'
        required: true
        default: '1.0.0'

  # 标签触发
  push:
    tags:
      - v*.*.*

jobs:
  build-and-release:
    name: Build and Release Tuff App
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]

    steps:
      - name: Check out git repository
        uses: actions/checkout@v4

      - name: Setup Python (for native dependencies)
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: |
          python -m pip install setuptools

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install Dependencies
        run: npm install -g pnpm && pnpm i && pnpm approve-builds

      - name: Determine Release Type
        id: release-type
        run: |
          if [ "$EVENT_NAME" = "push" ]; then
            echo "type=release" >> $GITHUB_OUTPUT
            echo "tag=$REF_NAME" >> $GITHUB_OUTPUT
          else
            echo "type=$RELEASE_TYPE" >> $GITHUB_OUTPUT
            echo "tag=v$VERSION" >> $GITHUB_OUTPUT
          fi
        env:
          EVENT_NAME: ${{ github.event_name }}
          REF_NAME: ${{ github.ref_name }}
          RELEASE_TYPE: ${{ github.event.inputs.release_type }}
          VERSION: ${{ github.event.inputs.version }}

      - name: Build Tuff App
        run: |
          if [ "$RELEASE_TYPE" = "snapshot" ]; then
            if [ "$RUNNER_OS" = "Windows" ]; then
              pnpm core:build:snapshot:win
            elif [ "$RUNNER_OS" = "macOS" ]; then
              pnpm core:build:snapshot:mac
            else
              pnpm core:build:snapshot:linux
            fi
          else
            pnpm core:build
          fi
          # 将构建文件移动到正确的位置
          if [ -d "dist" ]; then
            mkdir -p apps/core-app
            mv dist apps/core-app/
          fi
        env:
          RELEASE_TYPE: ${{ steps.release-type.outputs.type }}
          RUNNER_OS: ${{ runner.os }}
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}

      - name: Cleanup Artifacts for Windows
        if: matrix.os == 'windows-latest'
        run: npx rimraf "apps/core-app/dist/!(*.exe)"

      - name: Cleanup Artifacts for MacOS
        if: matrix.os == 'macos-latest'
        run: npx rimraf "apps/core-app/dist/!(*.dmg)"

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}
          path: apps/core-app/dist

  create-release:
    name: Create Release
    needs: build-and-release
    runs-on: ubuntu-latest
    if: always() && (needs.build-and-release.result == 'success' || needs.build-and-release.result == 'skipped')

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Determine Release Type and Tag
        id: release-info
        run: |
          if [ "$EVENT_NAME" = "push" ]; then
            echo "type=release" >> $GITHUB_OUTPUT
            echo "tag=$REF_NAME" >> $GITHUB_OUTPUT
            echo "name=Release $REF_NAME" >> $GITHUB_OUTPUT
          else
            echo "type=$RELEASE_TYPE" >> $GITHUB_OUTPUT
            echo "tag=v$VERSION" >> $GITHUB_OUTPUT
            echo "name=Release v$VERSION" >> $GITHUB_OUTPUT
          fi
        env:
          EVENT_NAME: ${{ github.event_name }}
          REF_NAME: ${{ github.ref_name }}
          RELEASE_TYPE: ${{ github.event.inputs.release_type }}
          VERSION: ${{ github.event.inputs.version }}

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.release-info.outputs.tag }}
          name: ${{ steps.release-info.outputs.name }}
          draft: false
          prerelease: ${{ steps.release-info.outputs.type == 'snapshot' }}
          files: |
            artifacts/windows-latest/*
            artifacts/macos-latest/*
            artifacts/ubuntu-latest/*
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}

      - name: Create Git Tag (for manual trigger)
        if: github.event_name == 'workflow_dispatch'
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git tag v${{ github.event.inputs.version }}
          git push origin v${{ github.event.inputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
